### ISSUE TITLE
0.15.1 Crashing on Win7

### ISSUE THREAD

**Issue by RealityRipple** [Bitcoin-ABC/bitcoin-abc#100]
Having trouble keeping 0.15.1 up and running... Application keeps not responding while in the system tray. Running the program on my primary C drive with the blockchain stored on secondary D drive. Config set to a 20 connection max, 300 ban time, 8000000 byte max block size, and small text comment. Two receiving addresses in the wallet, and it's encrypted of course. [Here's some log.](https://github.com/Bitcoin-ABC/bitcoin-abc/files/1425595/Debug.log) Nothing really sticks out to me... Anything I can do to help narrow it down?

- OS: Windows 7 x64 SP1
- CPU: AMD FX 8370
- RAM: 16 GB Patriot DDR3 @ 1600 9-11-11
- Disk size: 1TB C, 4TB D [+ 4TB M, 4TB T, 4TB V]
- Disk Type: C is SSD, rest are platter

Addendum: Grabbed this on a crash using VS2010: `Unhandled exception at 0x01441b9e in bitcoin-qt.exe: 0xC0000005: Access violation reading location 0xffffffffffffffff.`

**Comment by tmtisfree** [comment]
Same here with 0.16 & 0.16.1: GUI crashes after a few minutes. When reloaded, a new analysis is performed (takes half an hour each time).

- OS: Windows 7 x64 SP1
- CPU: AMD FX 8370
- RAM: 16 GB GSkill DDR3 @ 1600 11-11-11
- Disk size: 240GB C, 1TB E
- Disk Type: C is OCZ RevoDriveX2 PCIe SSD, rest are platter
- GPU: AMD Radeon 7800 Series

No debug log yet.

**Comment by schancel** [comment]
Closing as resolved based on @tmtisfree's comment.
