### ISSUE TITLE
Fork is set for 7:06pm (UTC)

### ISSUE THREAD

**Issue by danny91** [Bitcoin-ABC/bitcoin-abc#103]
### Describe the issue
Website says that fork should occur  1510600000, which corresponds to November 13th, 2:06 PM GMT

### Actual behavior
 1510600000 UNIX time-stamp actually refers to  November 13th, 19:06 (GMT) (UTC)

Time-stamp should have been; 1510581960

**Comment by rojii** [comment]
good call.

**Comment by ftrader** [comment]
Thanks @danny91 for reporting, it has now been corrected.

**Comment by ta32** [comment]
just curious is there 100% miner support for this fork. Normally i thought forks start their activating countdown based on signaling in blocks
