### ISSUE TITLE
Proposal to bring back the alert system

### ISSUE THREAD

**Issue by priestc** [Bitcoin-ABC/bitcoin-abc#106]
Is there a bitcoin cash BIP (BCIP?) repo? if there is, this proposal should be post there instead of here...

Bitcoin originally came with a built-in "alert" system. This was used to notify node owners of an upcoming hard fork (or any upgrade).

Unfortunately the core developers, in their infinite wisdom, disabled this feature long before BCH forked off it's code. I think we should bring back this system.

Instead of bringing back the old alert system exactly how it was, I think a better system can take it's place instead. The biggest problem with the old alert system was that the ability to make new alerts was only given to a small group of people, and there was no policy in place to grant new keys. There also was no way to handle a situation where a alert key holder "goes rogue" and spams the alert system.

Here how I think it should be:

An alert key is granted to every member of the Bitcoin Unlimited "members". All existing members get a key. All future members will get a key.

To make a new alert, you write the message, and then sign it with your alert private key, and then send that message, along with the signature to an "alert node". The alert node verifies that the signature is valid, and that your public key belongs to a legit BU member.That message is then sent out to all other alert nodes.

All other members of BU will subscribe to a notification service that notifies them of a new alert when it has been created. Members that agree that the alert is a legit alert, will publish an "upvote" message that just says "I agree with this alert". You can also issue a "downvote" message if you don't agree the alert should happen.

If more than 75% of signers who vote, vote positive, then the alert becomes an "alert with consensus" and should be shown to users using the color red. If less than 75% of voters vote positively, then the alert is a "contentious alert" and should be shown to the user in the color yellow. If it gets lower than 50%, then the alert considered a "spam alert" and is not shown to the end user at all.

Alerts should be shown to all users of BCH, not just node operators. Exchanges should show these alerts to users who hold BCH, and lightweight wallets should also show them to users who carry a BCH balance.

**Comment by priestc** [comment]
Furthermore, Bitcoin Unlimited can publish their members' alert public keys in a file located at http://bitcoinunlimited.org/alert_keys.csv. Miners mining BCH with the BU client will signal in their blocks something like "[alerts:bitcoinunlimited.org]". Miners mining BitcoinABC will signal "[alerts:bitcoinabc.org]". If the BU client has 50% of the hashpower, then their votes only count for 50% when determining if the alert has 75% consensus. If ABC only has 25% of the hashpower, then votes coming from their keys will only count for 25%. If the bitcoin unlimited client experiences a bug and the entire hashpower switches away from that client, the alert votes coming from them will become meaningless. Other clients are free to dole out alert keys however they see fit. The person who owns the domain is essentially responsible for how they. BU can even give out their keys however they want, but since they have that membership thing they will probably use that.

**Comment by jli225** [comment]
ACK.
The original removal of this alert system by Bitcoin Core Group was not out of good will at all.

**Comment by ftrader** [comment]
Did you open a BUIP for this?

I'm not sure why you propose a mechanism to ABC's repo instead of BU, if you want to grant some alert capability to BU members specifically. I see no rationale for a privileged status. BU could certainly adopt and implement such a system in their client. But if you intend it to be a system-wide alert for Bitcoin Cash, then I think some discussion has to take place between co-operating parties.
I would suggest you table this proposal on the mailing list if that is the case.

**Comment by deadalnix** [comment]
Indeed, i'm closing this. This should go to BU in the form of a BUIP.

**Comment by priestc** [comment]
> if you want to grant some alert capability to BU members specifically.

I'm not. All implementations of BCH get to grant alert keys to whomever they want. I just used BU as an example because they already have an impartial vetting process in place, which is perfect for granting alert keys.

In my second post I describe how hashpower decides which implementations' set of keys are weighted the most. At this time I believe most hashpower mines with ABC, so the ABC project accepting this proposal is more important at this time than any other implementation approving it, hence me posting this here.

> But if you intend it to be a system-wide alert for Bitcoin Cash, then I think some discussion has to take place between co-operating parties

Its hard to do that when the proposal gets closed on the main implementation's issue tracker... People may assume that because the ABC devs closed this issue, that the ABC team is not on board with the idea, which will discourage other implementations from coming on board.

Does there even exist a cross implementation BCH discussion portal? If so, I'll post the proposal there.

**Comment by ftrader** [comment]
Chris,

I view this as a kind of meta-consensus mechanism if shared by various Bitcoin Cash implementations.
I'm not at all opposed to discussion around it, but viewed your original submission as strongly BU-focused. Thank you for clarifying that BU was only supposed to serve as an example.
The best place to discuss this across implementations, in my view, is the mailing list:

  https://lists.linuxfoundation.org/pipermail/bitcoin-ml/

That is probably as close to a cross implementation BCH discussion portal we have right now, besides the Slacks which are not frequented by all developers.
