### ISSUE TITLE
What is the equivalent of Bitcoin Core uptime? 

### ISSUE THREAD

**Issue by phuongnd08** [Bitcoin-ABC/bitcoin-abc#107]
Bitcoin Core RPC has `uptime` method which tells how long the node has been running. What is the equivalent in bitcoin-abc? Attempting `uptime` in the latest version results in a "method not found" error.

**Comment by deadalnix** [comment]
There is none, you can backport that functionality is you want it, it should be fairly straightforward.

**Comment by schancel** [comment]
@mbhinder is currently working on this.

**Comment by schancel** [comment]
This has been implemented.
