### ISSUE TITLE
Failed on make

### ISSUE THREAD

**Issue by belindabeach** [Bitcoin-ABC/bitcoin-abc#109]
Ubuntu 14.04,  64
./autogen.sh
./configure
make

Error:

  CXX      crypto/libbitcoinconsensus_la-aes.lo
  CXX      crypto/libbitcoinconsensus_la-chacha20.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha256.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
In file included from ./primitives/transaction.h:9:0,
                 from ./primitives/block.h:9,
                 from consensus/merkle.h:11,
                 from consensus/merkle.cpp:5:
./amount.h:76:63: error: can't initialize friend function 'operator*'
     friend Amount operator*(const double a, const Amount b) = delete;
                                                               ^
make[2]: *** [consensus/libbitcoinconsensus_la-merkle.lo] Error 1
make[2]: Leaving directory `/home/bitcoin-abc/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bitcoin-abc/src'
make: *** [all-recursive] Error 1

**Comment by bastienjalbert** [comment]
I think your problem has already be resolved .. Don't forget to use search feature on issues section ...
https://github.com/Bitcoin-ABC/bitcoin-abc/issues/98

**Comment by ftrader** [comment]
Thanks for crosslinking, @bastienjalbert .

@belindabeach , specifically look at this suggestion: 

https://github.com/Bitcoin-ABC/bitcoin-abc/issues/98#issuecomment-343698269

**Comment by schancel** [comment]
Closing as resolved.
