### ISSUE TITLE
ERROR: AcceptToMemoryPoolWorker

### ISSUE THREAD

**Issue by nshopik** [Bitcoin-ABC/bitcoin-abc#111]
Tried to send transaction after I rollback bitcoin core blockchain, but not fully synced ABC
```
ConnectInputs failed against MANDATORY but not STANDARD flags 1718fe01e4af7ffd90e3973bd2c0f22b5082aff859ee8634a6f463baee92573f, mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16)
2017-11-12 09:05:01 CommitTransaction(): Transaction cannot be broadcast immediately, mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
```

**Comment by deadalnix** [comment]
You probably have some core peers that are trying to send you bitcoin transactions.

**Comment by nshopik** [comment]
Yeah I've actually checked all peers was ABC 0.16

Chain was stuck on 478559, so I invalidated it `invalidateblock 00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148`  and even after this it never accepted new tip and won't send signed transaction to network. Even though new tip was send correct (checked by external block explorer)

**Comment by deadalnix** [comment]
The tip has probably been already marked invalid by bitcoin core. You should use reconsiderblock on it. Also make sure you are connected to cash peers, not core peers.

**Comment by nshopik** [comment]
Yeah I forgot to mention that I even tried `reconsiderblock` as I'm already done this procedure before back in august on other node. Also my node was pruned, could be this issue?

Anyway I'll probably be no help here since i decided just resync from scratch

**Comment by nshopik** [comment]
Yeah even after full sync I seems stuck with pre fork block. I did both commands
`invalidateblock 00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148`
`reconsiderblock 000000000000000000651ef99cb9fcbe0dadde1d424bd9f15ff20136191a5eec`

But for some reason it always mark 478559 block as invalid, I remeber when I was doing this on 0.14.6 it immediately start syncing.

```

**Comment by nshopik** [comment]
For some reason console in bitcoin-qt aren't working but `reconsiderblock 000000000000000000651ef99cb9fcbe0dadde1d424bd9f15ff20136191a5eec` applied with bitcoin-cli

**Comment by rebroad** [comment]
did this issue ever get fixed?

**Comment by Fabcien** [comment]
This issue is closed for 7 years, if you have a similar error please open a new issue with all the required information about your version and your system.

**Comment by rebroad** [comment]
@Fabcien Is it ok to raise new issues for versions that are 7 years old?
