### ISSUE TITLE
Noob question about the new DDA

### ISSUE THREAD

**Issue by cool007zqw** [Bitcoin-ABC/bitcoin-abc#112]
I read [this article](https://www.justcryptonews.com/194/bitcoin-cashs-new-hard-fork-how-new-difficulty-algorithm-will-work) about the DDA algorithm,

My question is in the second equation:
`G = (2^256 / Wn) - 1`
where does this 2^256 come from? What is the basis of the number?

Answers will be highly appreciated.

**Comment by davidmann4** [comment]
Bitcoin Cash uses SHA256 algorithm

that means the hash is a 256-bit number,

good question!

**Comment by schancel** [comment]
Closing as answered.  Feel free to reopen if you have more questions.
