### ISSUE TITLE
Copyright info incorrect: #bitcoinabc IRC channel missing on Freenode

### ISSUE THREAD

**Issue by Shellcat-Zero** [Bitcoin-ABC/bitcoin-abc#114]
As shown here:
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/contrib/debian/copyright

Freenode reports "no matching chatrooms":
http://irc.netsplit.de/channels/?net=freenode&chat=bitcoinabc

**Comment by dhjw** [comment]
Further, please apply for a Freenode [group](https://freenode.net/groupreg), take over #bitcoincash and make me an op so I can manage the angry Core trolls. :)

Talk to dax or some other staffer in PM or on #freenode.

> 13:05 <@dax> dw1: we only do single-# channel recovery/transfer if there's an approved group registration

**Comment by schancel** [comment]
Thanks.  This was recently fixed.
