### ISSUE TITLE
Requirement of censor-resistance

### ISSUE THREAD

**Issue by shogochiai** [Bitcoin-ABC/bitcoin-abc#117]
Does this project include censor-resistance of each cnnection as requirement?
The scenario is for example some goverment want to control money issueing rights and try to shut out all mining node connection.
Any idea?

**Comment by jli225** [comment]
in the scenario that global governments unite to shut down all mining node connection, the difficulty mechanism built in Bitcoin from day one would deal with it successfully. Large mining farms will no long be able to run, thus hashrate decreases then difficulty decreases thus individuals would mine with personal mining rigs. Anyway, in such extreme condition, you can't expect the price, or the economic incentives, to be high for whatever reason.

Moreover, if the Governments even decide that individual mining is illegal and if they can monitor  it technically, then thia community would hard fork to lower the blocklimit to ~10kb easily (actually that does not require any fork). If that's not enough to shun the monitoring, ~1kb would be okay. If not, we can increase the blocktime to 24hours. 1kb per day would be impossible to monitor by governments.

That's the extreme condition. However, we don't live in such extreme conditions today, so ae don't need to keep the  '1kb per day' Utopia today.

**Comment by shogochiai** [comment]
I could make sense the balance between usability and robustness. It is for now trade-off, and you would say we'd better to find out the good balance, right?

So the person who are optimistic for censor-resistance situation will define the requirement as "Bitcoin is able to deal with extreme situation when govs shut down all mining node connection by using blocklimit/blocktime change without fork, but it causes market mess. And daily users are able to enjoy useful and reasonably-robust cryptocurrency."

Then another person who are pessimistic for censor-resistance situation will define the requirement as "Bitcoin is always able to deal with the extreme situation without any modification/forks and it doesn't causes market mess. But daily users are not able to enjoy useful cryptocurrency, but it's always robust."

Regarding the vision of BitcoinCash, I think the former statement is suitable for realistic answer. To make constant to variable will give an important external-pressure-reactive-nature to the network.

**Comment by schancel** [comment]
Thank you for your question. Bitcoin Cash has many of the same properties as Bitcoin.  One of those is being censorship resistant.

**Comment by shogochiai** [comment]
But I assume that `hidden-mode` inheritance from "Bitcoin-legacy" would not work on highly block size dependent scaling scenario. When we beyond the limitation of Tor add-on, we may need to think about how we can work around.
