### ISSUE TITLE
Unable to build v0.16.1 on Linux

### ISSUE THREAD

**Issue by vogelito** [Bitcoin-ABC/bitcoin-abc#119]
### Describe the issue
I'm unable to build the v0.16.1 tag on linux.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
Please see [pastebin](https://pastebin.com/wtE79nrJ). I can do this over and over again.

### Expected behaviour
I didn't have this problem building any of the following tags:
v0.14.5
v0.14.6
v0.15.1

### Actual behaviour
Build fails with errors:
```
make[2]: *** No rule to make target 'seeder/dns.c', needed by 'seeder/libbitcoin_seeder_a-dns.o'.  Stop.
make[2]: Leaving directory '/home/bitcoincash/bitcoin/bitcoin-abc/src'
Makefile:9499: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bitcoincash/bitcoin/bitcoin-abc/src'
Makefile:690: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

### What version of bitcoin-core are you using?
Building from source (have double checked that hash matches tag hash). I have also tried to `make` after `make clean`

### Machine specs:
- OS: Ubuntu 16.04.2 LTS (Xenial Xerus)
- CPU: Quad Core
- RAM: 64GB
- Disk size: 512GB
- Disk Type: SSD

### Any extra information that might be useful in the debugging process.
Happy to provide anything useful.

**Comment by axelay** [comment]
Same error here - would really appreciate some help

**Comment by deadalnix** [comment]
You have some bad stuff in you build folder.

Run `make distclean` , rereun configure and rebuild.

**Comment by axelay** [comment]
All good thanks!

**Comment by vogelito** [comment]
Confirmed this worked. Thanks.

@axelay - we seem to be always duplicating work! ;)
