### ISSUE TITLE
maxuploadtarget.py fails reliably

### ISSUE THREAD

**Issue by ftrader** [Bitcoin-ABC/bitcoin-abc#12]
Assertion failed in maxuploadtarget.py (during run of extended tests):
```
maxuploadtarget.py:
Initializing test directory /tmp/testcflv3y34/161
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:12288
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:12288
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:12288
Assertion failed: not(3 == 2)
Stopping nodes
Not cleaning up dir /tmp/testcflv3y34/161
Failed

stderr:
  File "/home/ftrader/abc/qa/rpc-tests/test_framework/test_framework.py", line 145, in main
    self.run_test()
  File "/home/ftrader/abc/qa/rpc-tests/maxuploadtarget.py", line 165, in run_test
    assert_equal(len(self.nodes[0].getpeerinfo()), 2)
  File "/home/ftrader/abc/qa/rpc-tests/test_framework/util.py", line 520, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))

Pass: False, Duration: 110 s
```
Issue can be reliably reproduced on my system (Debian 7 x86_64) by running the test on its own:
`$ qa/pull-tester/rpc-tests.py maxuploadtarget`

I executed a comparison run on the same system with Bitcoin Core 0.14 branch (f2a96e7d0289682eb87877a3528cb6a170f8b786) - the test passed 10 / 10 times.

**Comment by ftrader** [comment]
git bisect says:

b569a7134199f898098b736341ef8bb4cceb6d11 is the first bad commit

**Comment by ftrader** [comment]
Problem was the test itself containing unreverted SegWit adaptations:

https://github.com/Bitcoin-ABC/bitcoin-abc/pull/15

**Comment by ftrader** [comment]
Tested locally with above PR, test passed.

**Comment by deadalnix** [comment]
Shall we close that one ?

**Comment by ftrader** [comment]
Yeah, I thought the reason for this tests failure is now cleared up, so I'm happy closing it.
