### ISSUE TITLE
This project needs someone to take responsibility for it.

### ISSUE THREAD

**Issue by dscotese** [Bitcoin-ABC/bitcoin-abc#121]
### Describe the issue
It is difficult to identify (and therefore plan for contact with) a person who vouches for the project as compiled, for example, at https://download.bitcoinabc.org/.  If you have provided a binary, please consider identifying yourself publicly to vouch for the fact that the code you claim to have compiled is the code you actually compiled.  Once you're identified, sign the binaries you create.  My (admittedly cursory) search for a responsible party has not been fruitful, and so I am without a working binary for the Windows 64-bit version of this project.

I realize that I can put my time and effort into compiling the binary myself, but I don't have time, and I am committed to seeing this project serve the masses who will certainly not compile their own binaries.

When creating this issue, there was a message, "Before you open an issue please review the contributing guidelines for this repository. " which points to https://reviews.bitcoinabc.org/ which appears to be broken.

**Comment by cryptorun** [comment]
from my readings, the actual development is not happening on github but on https://reviews.bitcoinabc.org/. You need to create an account to be able to see the development activity and address the guys who maintain the software.

**Comment by NiKiZe** [comment]
I'd say that the best way to handle this is to use https://gitian.org/
Same binary, built by and signed by multiple people. Don't rely on one centralized authority when it can be decentralized.

**Comment by schancel** [comment]
We are using Gitian, and do currently post binary hashes.  It sounds like you would also like developers to sign the binaries as well.  We can look at doing that in the near future.  At this moment, reproducible builds are the standard.

I have updated the gitian build documentation to make it easier for 3rd parties to build reproducibly.  We encourage any interested parties to verify our builds.
