### ISSUE TITLE
Why is this transaction won't be propagated to all nodes?

### ISSUE THREAD

**Issue by phuongnd08** [Bitcoin-ABC/bitcoin-abc#127]
### Describe the issue
I made a transaction with this payload:
```
010000000523098dba7ffe6cd0ff8737e3951b78704e1e7edd37abd669e2f9fac4f635583a000000006b483045022100930524906351a08ef95effa201deba373b4050d70e133bca46135ffc0fa4f1ef0220625834d573132816207e2b2735a525a624c2adc94cb380c5aaee6ca8d234ecce4121028524cf4750e26e9f4901dc3799a87fa4171f1a9089ba2bb4b6b202772bfa8320ffffffff3dafbc729e4789fc78dd5bf022dcab94fa3e499261557b8599d2dd46dc637375000000006a4730440220638819406e711a045edffbf8688006787e86300d3934a107c9622ec1c6abe85b0220170c4471383f171395dfdf15118c91dca496e58840fb2c3ac7630924bba715454121028524cf4750e26e9f4901dc3799a87fa4171f1a9089ba2bb4b6b202772bfa8320ffffffffe535ed250d1597fbe1d9e621a28ba76d3392da5606ea9525b525507851f73989000000006a47304402201c2047d294c5d5f2bb1f5ece375cf4e4185b02cbde403c58610baeb95f8ac78d02205be7b184e1b876649c7208629ffdef8e3f16f56d68bc2aeb7f8d194716f420624121028524cf4750e26e9f4901dc3799a87fa4171f1a9089ba2bb4b6b202772bfa8320ffffffff3b96bffc8d6a4168cf4d3b0464a74e2c81ec3661d4c18554a66ae93c4fb21277000000006b483045022100948e5c492b475adac42b37f26027a9cd2d3aa788f9af31b6eb5de0621eb1ab8702202b72fbc4623f1f6b2275847c054146a2e54849e0f83d78209cf78e0663e249be4121028524cf4750e26e9f4901dc3799a87fa4171f1a9089ba2bb4b6b202772bfa8320ffffffffc4fa47ec1943d3a722fd93a5ccc730cd5385977c0ab852cca1cf4ef5cd938837000000006b483045022100dc045187a7390513d6ee235e478d55aa4bc78bdf6597ff8d2eaab637f2b8e2b002201fd4016b08c1c5f2f9b55a42e6afff4ec4a661bc1c54b34ee6bad4fe5abd31f54121028524cf4750e26e9f4901dc3799a87fa4171f1a9089ba2bb4b6b202772bfa8320ffffffff024feedd81010000001976a9148b71feed12878aa02d491a765adf2044c30616ed88ac9a890d00000000001976a914c49cd40b1298fa92c367a756b4e34cd4d3d3170788ac00000000
```
The problem with it is that if I rely that transaction to a node, that node accept the transaction, but it will never be propagated across the network.
For example I publish it with `https://bitcoincash.blockexplorer.com/tx/send` then it's available on blockexplorer indexer:
`https://bitcoincash.blockexplorer.com/tx/aaf36a5b17d6071a3d1e96f5cd26d83ccccde9c0e1a1e48bd465635281724b6f`

But it won't be found on blockdozer.com.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Rely the transaction above on a node
2. Wait for some time for it to propagate
3. Check for that transaction in mempool of a second node

### Expected behaviour
The transaction is available in the mempool of a second node

### Actual behaviour
The transaction is unavailable in the mempool of a second node

### What version of bitcoin-abc are you using?
Bitcoin ABC:0.16.1(EB8.0; bitcoin-abc)

### Machine specs:
Not relevant because it happened with all the nodes I know off.

**Comment by ftrader** [comment]
Your fee rate is just below 1000 sat / KB , which is the default setting for minimum tx relay fee rate (mintxrelayfee) in ABC nodes. So most nodes with default settings will not relay this.

But you must have had luck getting it into the mempool of a miner, since it is now in block 506403.

FYI, I tried to submit in https://pool.viabtc.com/tools/BCH/broadcast -> "Raw transaction send failed."

**Comment by phuongnd08** [comment]
Thank you. I’ve just realized it recently as well.

**Comment by purplecity** [comment]
know  input and output how to estimate transaction size？
