### ISSUE TITLE
To add remark information into blockchain when transaction

### ISSUE THREAD

**Issue by william755** [Bitcoin-ABC/bitcoin-abc#132]
It's well known that in Europe and USA a payer (bank user) should add an order number or invoice number into his transaction request when the payer is paying money to his/her supplier/creditor. this is a typical payment scenario in business area. so that I submit this requirement to my dear ABC development team:
1. Please add a new line in the wallet application with remark information (e.g. payer name, invoice ID or order number) into blockchain when transaction. **at the same time BCH blockchain should also support remark information inside.**
2. this length of remark information should less than 30 characters.
3. Higher fees for more characters.
4. Default remark information should be empty.

it's a temporary solution to allocate different BCH address for different customers - it's too difficult for small company to manage so many different BCH address when this small company receives money without any recognizable remark information inside.

if this is not the correct way to submit my requirement to ABC team, please instruct me how to submit it. thanks.

**Comment by schancel** [comment]
Hi @william755, This sounds like an interesting idea.  Thank you for the feedback. Unfortunately goes against some of the ideals of a pseudonymous ledger.  This could be implemented as an additional output of a transaction, by wallet developers, if they wish.  It is unlikely that this would be adopted into the core protocol.

If you'd like to discuss it more, I would recommend posting on reddit.com/r/btc or yours.org and see what the community has to say.

**Comment by mbomaretoteamchevroletlvcom-lang** [comment]
I also lost about $75,000 to an IQ option broker and 2 fake binary option websites as well but I am sharing my experience here to enlighten and educate everyone who is losing money or has lost money to a scam including binary options dating scams Recover all your lost money to Bitcoin and other Cryptocurrency mortgage real estate scams and fake ICOs. However I have been able to recover all the money I lost to the scammers with the help of a recovery professional and I am pleased to inform you that there is hope for everyone who has lost money to scam  You can reach out to them at recoveryexpert326 at gmail dot com
