### ISSUE TITLE
Recovering funds from segwit (mutli-sig) address?

### ISSUE THREAD

**Issue by khelle** [Bitcoin-ABC/bitcoin-abc#135]
Hi, I have a question - we use segwit multi-sig addresses on our application to receive funds in Bitcoin, and standard ones in Bitcoin Cash. One of our users put BCH deposit to Bitcoin address instead of Bitcoin Cash. To fix that and take the ownership of the wrongly sent funds I copied witness address from Bitcoin to Bitcoin Cash node, generated the same address, but when I tried to call `addwitnessaddress` to get the multi-sig one I got the error of "Method not found". Is it possible for me to recover those funds or not?

**Comment by deadalnix** [comment]
It is possible if you cooperate with a miner. There is nothing Bitcoin ABC can do for you. The fund are secure as long as you do not use this address on the BTC chain. If you do, they become at risk of being stolen.

**Comment by stefment** [comment]
This might be relevant https://github.com/Bitcoin-ABC/bitcoin-abc/issues/35

**Comment by schancel** [comment]
@khelle Were you able to retrieve your funds?  Several miners were sweeping segwit addresses and allowing people to reclaim the funds.  I can see if I can point you in the correct direction if you'd like.

**Comment by dhjw** [comment]
[btc.com has a service](https://bch.btc.com/docs/help/bch_segwit_recovery)
