### ISSUE TITLE
Include a forwarding pointer

### ISSUE THREAD

**Issue by mikelambert** [Bitcoin-ABC/bitcoin-abc#136]
I was looking at this repo thinking code development had died, and was starting to go negative on bitcoin cash being all marketing.

You may want to include a forwarding pointer in your README and/or top-level github description, pointing people to: https://reviews.bitcoinabc.org/source/bitcoin-abc/

**Comment by deadalnix** [comment]
It's all marketing @mikelambert . This is because we are all Roger's sockpuppets around here.

More seriously the readme on the front page include this information. It was removed for a short period of time when the contributing guideline were rewritten, but it now back there.

**Comment by mikelambert** [comment]
Oh wow, I just noticed it at the very bottom of the README:
"Bitcoin ABC development takes place at https://reviews.bitcoinabc.org/"

I would imagine that might be more useful at the top of the README :)

Or perhaps you don't want to edit the README, if it's the same README shared with the official repo? In which case, perhaps you can edit the the github-specific metadata at the top of the entire-page, that currently says "No description, website, or topics provided."?

Thanks!
