### ISSUE TITLE
Third party transaction ID malleability

### ISSUE THREAD

**Issue by dhjw** [Bitcoin-ABC/bitcoin-abc#139]
Can someone please tell me if third party transaction ID malleability was patched with the DAA fork as [some people allege](https://www.reddit.com/r/btc/comments/7desa2/since_the_november_13_daa_hard_fork_also/)?

Where was the code changed to fix this?

Thanks

**Comment by schancel** [comment]
It was not completely patched.  There were a few changes to reduce what can be malleated. 

Here is the commit: https://github.com/Bitcoin-ABC/bitcoin-abc/commit/aeb72d7f3c737947090884390fbe28d00e4e0621
