### ISSUE TITLE
Please consider using "BCH" instead of "BCC" to avoid fragmentation

### ISSUE THREAD

**Issue by Polve** [Bitcoin-ABC/bitcoin-abc#140]
With a few notable exception (bittrex in particular) the whole ecosystem seems to have switched using BCH as ticker name for Bitcoin Cash, but in the documentation of Bitcoin ABC there are a few references to BCC.

I would like you could consider switching those references to BCH to avoid fragmentation and possible confusion for users.

I could prepare a pull request if you find this acceptable.

**Comment by paoloaga** [comment]
I agree. Switch everything to BCH and then to BTC when it will become the branch with more POW.

**Comment by schancel** [comment]
Most everything should have been changed to `BCH` already.  If you find references please do prepare a pull request.  I can move the patch over to phabricator if necessary.
