### ISSUE TITLE
unable to start bitcoin.ABC wit a running bitcoin CORE

### ISSUE THREAD

**Issue by aotto1968** [Bitcoin-ABC/bitcoin-abc#143]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
→ ~/bitcoin-abc-0.16.1> bin/bitcoin-qt
→ Error-Message: Datenverzeichnis ~/.bitcoin kann nicht gesperrt werden. Evtl. wurde Bitcoin ABC bereits gestartet.

### Can you reliably reproduce the issue?
→ YES
#### If so, please list the steps to reproduce below:
1. hust start the QT client if Bitcoin-CORE is active 
2.
3.

### Expected behaviour
Tell us what should happen
→ I expect that Bitcoin-ABC is using an OTHER directory as Bitcoin-CORE

### Actual behaviour
Tell us what happens instead
→Bitcoin-ABC is using the SAME directory as Bitcoin-CORE

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![image](https://user-images.githubusercontent.com/27886664/34409723-ea7ae8c0-ebcb-11e7-9cfe-2e8ffa645ec8.png)

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
Linux linux02 4.4.103-18.41-default #1 SMP Wed Dec 13 14:06:33 UTC 2017 (f66c68c) x86_64 x86_64 x86_64 GNU/Linux
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jli225** [comment]
The reason may be the same port they are using.
You can change the port, or uninstall Bitcoin Core like I did.

**Comment by aotto1968** [comment]
well today my Bitcoin-ABS destroy my Bitcoin-Core database… because after automatic restart…(using the option set on configuration)… the "datadir" commandline option from the previous start was NOT set… and Bitcoin-Cash start using the "default" datadir ".bitcoin"… starting immedietly destroying the Bitcoin-Core database.

→ that is the reason you should NEVER use the same default's as your competitor…

**Comment by Naturex1** [comment]
Default datadir

**Comment by jli225** [comment]
You can safely uninstall Bitcoin-Core and reinstall Bitcoin Cash. Then everything would work well.

**Comment by h908714124** [comment]
Suggesting to consolidate this and #141 into one ticket

**Comment by bioharz** [comment]
Hi. Why don't you change the default port and data-dir of your bitcoin fork?

**Comment by Dmatafonov** [comment]
> Hi. You could easily change the default port and data-dir of your bitcoin fork.

I have the same problem and cant figure out how to change default ports and directories. Could anyone give instruction on that?

I cant uninstall bitcoin-core, because I have merchants sending me bitcoins and I wand start accepting BCH as well.

I installed both chains to same server and now I have same account balance in BCH as in BTC.

![image](https://user-images.githubusercontent.com/8863854/36503800-7035f1d0-175f-11e8-9a1f-f791c363eac0.png)

**Comment by goodProjects** [comment]
You have to make a different user account for each software if you planning to use both on the same machine.

**Comment by bioharz** [comment]
Thank you very much for the answer! That should work!

What’s about the port?

**Comment by goodProjects** [comment]
in your bitcoin.conf file just set a different port than Bitcoin core
`rpcport=<anyPort>`

**Comment by bioharz** [comment]
Thanks!

**Comment by ddwrtmenace** [comment]
jli225 you are doing a great service reassuring everyone that bitcoin cash has crap engineers and is a piece of crap

**Comment by schancel** [comment]
This issue has been duplicated several times.
