### ISSUE TITLE
[feature-request] Masterblocks: Scaling Blockchain by summarizing balances

### ISSUE THREAD

**Issue by Technologov** [Bitcoin-ABC/bitcoin-abc#150]
https://docs.google.com/document/d/1usnNigTJw6cpone_xrcIMmzxF7U1MFrjb3y7aTsbDx0/edit

What do you think of it ?

**Comment by h908714124** [comment]
Looks like a google link

**Comment by schancel** [comment]
This sounds similar to including a utxo snapshot in the block.  This is possible, but needs more discussion: https://www.deadalnix.me/2016/09/29/using-merklix-tree-to-checkpoint-an-utxo-set/

**Comment by schancel** [comment]
It looks like you've taken this to the mailing list.  I'm going to close this particular issue in favor of discussing it there.
