### ISSUE TITLE
getblock with tx info

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Bitcoin-ABC/bitcoin-abc#152]
Hello.
Is it possible to get a block with transaction info in one request?
In bitcoin Core I can get it like 
```bitcoin-cli getblock  blockid 2```
How to make it on Bitcoin ABC?

**Comment by schancel** [comment]
No, that isn't currently supported in Bitcoin-ABC.  You need to make two requests:
```bash
bitcoin-cli getblock $(bitcoin-cli getblockhash 2)
```

**Comment by Vasiliy-Bondarenko** [comment]
Sorry, I think you didn't understand the question.
"2" - is not a block hight. it's a modificator to getblock command which returnes a block with all transaction expanded: https://bitcoin.org/en/developer-reference#getblock
I have a block hash. I just need to get all transactions info in that block.

**Comment by schancel** [comment]
No, it doesn't look like the CLI currently supports that.  It only has JSON and serialized mode.   If you'd like to backport that patch, it'd be welcome.

**Comment by Vasiliy-Bondarenko** [comment]
Thanx for clarification. 
I've decoded all data from HEX.
