### ISSUE TITLE
Ban invalid nodes

### ISSUE THREAD

**Issue by OverlordQ** [Bitcoin-ABC/bitcoin-abc#155]
### Describe the issue

Core/Old broken nodes inadvertantly DoS Cash nodes.

#### If so, please list the steps to reproduce below:
1. Start Bitcoin-ABC
2. View debug log
3.

### Expected behaviour

After a certain number of failed message's, erroneous nodes get blocked.

### Actual behaviour
Nodes continue to re-attempt a connection

### What version of bitcoin-abc are you using?
1.16.2

### Any extra information that might be useful in the debugging process.

https://hastebin.com/uziqavasiq.cs

**Comment by OverlordQ** [comment]
It got to an absurd connection count before I had to turn on network debugging to get IPs and block them at the firewall.

https://hastebin.com/hojatugego

**Comment by deadalnix** [comment]
Yes, thanks for the patch BTW.

**Comment by schancel** [comment]
I believe this is now fixed.  If not, please reopen.
