### ISSUE TITLE
OP_RETURN back to 80 bytes

### ISSUE THREAD

**Issue by onedrop** [Bitcoin-ABC/bitcoin-abc#160]
Just wondering if there are plans to bump OP_RETURN back to 80?

**Comment by dexX7** [comment]
It's been like this for a long time:

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/script/standard.h#L30

But see also: https://github.com/Bitcoin-ABC/bitcoin-abc/pull/41

**Comment by schancel** [comment]
I believe we will be bumping OP_RETURN to 220.
