### ISSUE TITLE
Bitcoin cash has not been transfered.

### ISSUE THREAD

**Issue by wolfomat** [Bitcoin-ABC/bitcoin-abc#164]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue

I tried to transfer an amount of bitcoin cash to another wallet. The transaction seems to be correct, i got over 3k confirmations. But when i try to find the transaction with the given id and receiver adress in the bitcoin cash blockchain with an bitcoin cash blockchain explorer, i can't find this transaction. 
Are my bitcoin cash lost, what can i do here? 
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
The bitcoin cash amount minus the TA fees should be transfered to the other wallet.

### Actual behaviour
the amount has not been received in the other wallet, neither I can't find anything in the blockchain explorer, see:

Status: 3583 Bestätigungen, über 3 Knoten übertragen
Datum: 04.02.2018 13:58
An: litebit 1D3ueWPVza6Z5w9hxzbnTfQqVJUY6qFWV8
Belastung: -0.45125060 BCC
Transaktionsgebühr: -0.00000340 BCC
Nettobetrag: -0.45125400 BCC
Transaktionskennung: 12afc5cf496022d4bf882a055d5af633cc23f00790447d8bbec1a2f2e8ca3992
Gesamte Transaktionsgröße: 339 bytes
Ausgabeindex: 0

### Screenshots.
![bcc_abc_wallet](https://user-images.githubusercontent.com/17848544/35996131-edc8b870-0d15-11e8-9d1c-c21e4147a1ca.JPG)

### What version of bitcoin-abc are you using?
Bitcoin ABC Version v0.14.6.0-a46e63c (64-Bit) 
build from official page
### Machine specs:
- OS: Windows 7 Pro, 6.1. Build 7601
- CPU: AMD A8-7100 Radeon R5
- RAM: 8192MB 
- Disk size:  260 GB free of 465 GB in sum
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred. 

https://pastebin.com/wPnyGvpa
and  please see (got the date of the TA)
https://pastebin.com/0PKQWjrF

**Comment by wolfomat** [comment]
okay, please before you debug this issue, i try to download the latest bitcoin abc wallet and re-sync the whole blockchain again on another computer.
because I just looked up the receiving transactions in the blockchain explorer and they are listed as unspent. 
i'll come back with feedback when the latest wallet and the blockchain is on sync. maybe it's a client side bug. but it is really strange.

**Comment by schancel** [comment]
I don't see that transaction ID in any the blockchain.  I believe you're using a version which is not able to validate the current protocol rules.  Downloading the latest ABC and letting it sync up should fix your problem.  You'll likely need to send your funds again.

**Comment by wolfomat** [comment]
latest wallet and after blockchain sync fixed the problem. i had to cancel the transactioon and my coins went back to my wallet. perfect.
