### ISSUE TITLE
Typo on web site

### ISSUE THREAD

**Issue by dhjw** [Bitcoin-ABC/bitcoin-abc#167]
On the [CashAddr page](https://www.bitcoinabc.org/cashaddr) it says:

> You can convert from the old format to the new format, or from the old format to the format. 

This should probably say:

> You can convert from the old format to the new format, or from the new format to the old format.

**Comment by schancel** [comment]
We need to get the website up in a public repository so we can all do PRs on it :)

**Comment by schancel** [comment]
We're going to start using this repo soon: https://github.com/Bitcoin-ABC/bitcoin-abc.github.io

If you want to put up any patches.

**Comment by schancel** [comment]
I've fixed the typo, but the website is not live yet.
