### ISSUE TITLE
Transactions appear with old format when calling "listtransactions"

### ISSUE THREAD

**Issue by goodProjects** [Bitcoin-ABC/bitcoin-abc#169]
Transactions appear in old format when calling `listtransactions` or `listunspent`

I have `usercashaddr` enabled in my config, transactions sent/received to new format address
 appear in the old format when calling listtransactions or listunspent.

### What version of bitcoin-abc are you using?
0.16.2

**Comment by schancel** [comment]
I cannot reproduce this.

**Comment by goodProjects** [comment]
Did you try on Testnet?
