### ISSUE TITLE
Build failure with boost 6.6.0

### ISSUE THREAD

**Issue by mgonzalezm** [Bitcoin-ABC/bitcoin-abc#178]
miner.cpp:378:74:   required from here
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1181:7: error: no match for call to '(const key_compare {aka const CompareModifiedEntry}) (const CTxMemPoolModifiedEntry&, CTxMemPoolModifiedEntry&)'
       if(comp_(key(v),key(y->value())))return false;
       ^~
In file included from miner.cpp:6:0:
miner.h:73:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a,
          ^~~~~~~~
miner.h:73:10: note:   passing 'const key_compare* {aka const CompareModifiedEntry*}' as 'this' argument discards qualifiers
In file included from /usr/include/boost/multi_index/ordered_index.hpp:17:0,
                 from txmempool.h:17,
                 from miner.h:10,
                 from miner.cpp:6:
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1186:25: error: no match for call to '(const key_compare {aka const CompareModifiedEntry}) (CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&)'
     return y==header()||!comp_(key(y->value()),key(v));
In file included from miner.cpp:6:0:
miner.h:73:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a,
          ^~~~~~~~
miner.h:73:10: note:   passing 'const key_compare* {aka const CompareModifiedEntry*}' as 'this' argument discards qualifiers

**Comment by you21979** [comment]
same issue https://github.com/Bitcoin-ABC/bitcoin-abc/issues/173

**Comment by schancel** [comment]
Closing as duplicate
