### ISSUE TITLE
Building for windows fails

### ISSUE THREAD

**Issue by ShanksPranks** [Bitcoin-ABC/bitcoin-abc#180]
Build using windows build fails due to gcc incompatibility

Following the build steps laid out in the building for windows md the following error occurs:

`  CXX      consensus/libbitcoinconsensus_la-merkle.lo
In file included from ./primitives/transaction.h:9:0,
                 from ./primitives/block.h:9,
                 from consensus/merkle.h:11,
                 from consensus/merkle.cpp:5:
./amount.h:123:73: error: can't initialize friend function 'operator*'
     friend constexpr Amount operator*(const double a, const Amount b) = delete;
                                                                         ^
make[2]: *** [consensus/libbitcoinconsensus_la-merkle.lo] Error 1
make[2]: Leaving directory `/mnt/c/Users/jafoo/Documents/bitcoin-abc/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/c/Users/jafoo/Documents/bitcoin-abc/src'
make: *** [all-recursive] Error 1`

According to issue #98 this is because bitcoin-abc is no longer compatible with older versions of gcc (4.8.2) and g++ but the build instructions are designed to use mingw which appears to be 4.8.2.  I see that this file (build-windows.md) is 9 months old so I am not sure if there is an easy fix of if we need to re-write some of the windows configuration section. I see that the core one is more up to date so I could try and build that then try update ours if it works?

I am using the main trunk. Windows 10 home edition with Linux subsystem.

**Comment by deadalnix** [comment]
Indeed, you need to update gcc. the bug is in gcc.
