### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by jdamhost** [Bitcoin-ABC/bitcoin-abc#185]
Hi when I try to run the make command I get this error : 

Making all in src
make[1]: Entering directory `/home/user/bitcoin-abc/src'
make[2]: Entering directory `/home/user/bitcoin-abc/src'
  CXX      consensus/libbitcoinconsensus_la-merkle.lo
In file included from ./primitives/transaction.h:9:0,
                 from ./primitives/block.h:9,
                 from consensus/merkle.h:11,
                 from consensus/merkle.cpp:5:
./amount.h:123:73: error: can't initialize friend function 'operator*'
     friend constexpr Amount operator*(const double a, const Amount b) = delete;
                                                                         ^
make[2]: *** [consensus/libbitcoinconsensus_la-merkle.lo] Error 1
make[2]: Leaving directory `/home/user/bitcoin-abc/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/bitcoin-abc/src'
make: *** [all-recursive] Error 1

**Comment by deadalnix** [comment]
This is a bug in older version of GCC. Please use GCC 5 or more recent.
