### ISSUE TITLE
Payment Protocol not supported

### ISSUE THREAD

**Issue by doubledave** [Bitcoin-ABC/bitcoin-abc#186]
### Describe the issue
Using payment protocol, for example, from bitpay, the address appears like:
`bitcoincash:?r=https://bitpay.com/i/xxxxxxxxx`
I am unable to paste this into the "pay to" field in the "send" tab of Bitcoin ABC 0.17.0 wallet.

#### If so, please list the steps to reproduce below:
1. Initiate a bitpay payment to a vendor, select bitcoin cash.
2. Bitpay website will provide a payment protocol URL which is valid on an increasing number of modern wallets.
3. Paste the payment protocol URL into Bitcoin ABC wallet's "pay to" field of the "send" tab.

### Expected behaviour
Payment protocol address accepted into wallet. Address, payment amount, and description gets filled in.

### Actual behaviour
"Send to" field remains empty, as it doesn't accept certain characters that exist in the payment protocol url such as "/"

### What version of bitcoin-abc are you using?
0.17.0 "bitcoind" and "bitcoin-qt" from repository at ppa:bitcoin-abc/ppa

### Machine specs:
- OS: 64-bit Ubuntu 16.04
- CPU: AMD FX-6300
- RAM: 32 GB
- Disk size: 19 TB usable
- Disk Type (HD/SDD): 10 drive raidz2 HDD ZFS array

**Comment by knoxcard** [comment]
You need to convert the Bitcoin Cash address you have now into a legacy address.  There are tools online that supposedly let you easily do this.  Someone referenced this site...

https://blockchair.com/bitcoin-cash/transactions

I thought there was an RPC command **translateaddress** to do this...

**Comment by TheDoktar** [comment]
I agree with doubledave's report and have this morning experienced the same issue with the v0.17.0.0 ABC client. 
I can report that I successfully used Bitpay protocol in the previous ABC release, probably 
bitcoin-abc-0.16.2-x86_64
knoxcard, this is NOT an issue with legacy addresses.  This is about the Bitpay payment protocol, Bitpay do not provide an address they provide an id (the xxxxxxxxx ) in doubleday's example that links to all your information, amount, delivery address etc.  But there is no easy way to extract a payment address from this id. 
Essentially this bug means that BitcoinCash with the ABC client is broken with Bitpay. 

This ought to be a high priority issue.

**Comment by jasonbcox** [comment]
If Bitpay is providing an ID instead of an address, what is the bug here?  I'm not aware of Bitcoin ABC supporting Bitpay's payment protocol at any point in time.  Closing this issue for now, as we don't intend on supporting it at this time.

**Comment by knoxcard** [comment]
I transferred my Bitcoin Cash to BitPay from my Bitcoin ABC full node, then to my Bitpay debit card with no issues.  Did this three times today.

**Comment by knoxcard** [comment]
I think this is the problem now, i could be wrong...

My Bitpay Address: qquc3f6044gyhrwm6h76kwmzt0qm7aaevvef0cv3y6
it is not ...
bitcoincash:qquc3f6044gyhrwm6h76kwmzt0qm7aaevvef0cv3y6

Just strip out the "bitcoincash:" protocol part and paste the address only.
