### ISSUE TITLE
future upgrades should use consensus signaling

### ISSUE THREAD

**Issue by ta32** [Bitcoin-ABC/bitcoin-abc#187]
I think its a bad practice to release protocol changes that activate at a certain block height unless its an emergency change that is not contentious and protects the social contract of bitcoin.

This ensures all miners, both large and small support the change.
If mining was more decentralized this would be the only way to upgrade. 

But right now its possible to directly approach the majority of the miners. I think important to have some kind of voting mechanism for future upgrades as it improves transparency and legitimizes any changes.

**Comment by ta32** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki

I think activating hard-forks shouldn't occur at a hard-coded block height. We should implement BIP9 or something similar. 

How much will it cost to implement this?

**Comment by deadalnix** [comment]
Upgrades do not happen at block height, but after MTP pass some value. This allow everybody to be able to predict when the upgrade will happen and organize accordingly.

**Comment by ta32** [comment]
Ok i understand, but the hard-fork is effectively scheduled. 

But how do you know every miner has upgraded to the new client? 

I thought this was the purpose of having miner activated hardfork's eg: when 98% of the last blocks signal changing of the rules the activation window starts.

**Comment by jasonbcox** [comment]
It's in the miner's best interest to be upgraded well before the fork.  To not do so will lose them money.  The economic incentives work and that should be enough.
