### ISSUE TITLE
Feature request: please tag releases properly on Bitcoin-ABC github's repository

### ISSUE THREAD

**Issue by gituser** [Bitcoin-ABC/bitcoin-abc#189]
Guys, can you properly tag the releases on github?

So it will be easier to get through API latest release number to stay updated.

Right now, what you do is only tag, but information on tags is very limited - there is no release date at all and hard to figure out what's the latest release.

Here is how you can do it via API call - https://developer.github.com/v3/repos/releases/#create-a-release

In this case for users simply calling https://developer.github.com/v3/repos/releases/#get-the-latest-release will fetch the latest release without any additional processing.

Thank you.

**Comment by jasonbcox** [comment]
Releases are currently tagged in Github: https://github.com/Bitcoin-ABC/bitcoin-abc/releases  I believe you're asking for git tags in the repo itself.  We're working on that, but it's low on our priority list right now.  I've created a Phabricator ticket to track this: https://reviews.bitcoinabc.org/T323

**Comment by gituser** [comment]
The releases link displays tags there instead (it's how github shows it). And if you try to get latest release via Github API you won't be able to do so on `Bitcoin-ABC/bitcoin-abc` repository, because `tag` != `release`.

**Comment by gituser** [comment]
It seems this issue has been fixed.

Thank you!
