### ISSUE TITLE
Compile errors for windows

### ISSUE THREAD

**Issue by toorq** [Bitcoin-ABC/bitcoin-abc#190]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
Compile error when  compile for windows.

cd depends
make HOST=x86_64-w64-mingw32
cd ..
 ./autogen.sh # not required when building from tarball
 CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
 make

Q1:
When executing "make HOST=x86_64-w64-mingw32"
It report error on windows linux system.
Because windows add windows paths to runtime paths.
It can be fix by 
https://github.com/toorq/bitcoin-abc/commit/a3e531d7aa586e46fa32c192afeef2053ac27398

Q2:
When executing " make"
It report a compile error

Making all in src
make[1]: Entering directory '/home/tq/prj/bitcoin-abc-tq/src'
make[2]: Entering directory '/home/tq/prj/bitcoin-abc-tq/src'
  CXX      seeder/bitcoin_seeder-main.o

seeder/main.cpp: In function ‘int main(int, char**)’:
seeder/main.cpp:471:12: error: ‘SIGPIPE’ was not declared in this scope
     signal(SIGPIPE, SIG_IGN);
            ^
Makefile:8312: recipe for target 'seeder/bitcoin_seeder-main.o' failed
make[2]: *** [seeder/bitcoin_seeder-main.o] Error 1
make[2]: Leaving directory '/home/tq/prj/bitcoin-abc-tq/src'
Makefile:9780: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tq/prj/bitcoin-abc-tq/src'
Makefile:721: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by schancel** [comment]
We don't have anyone currently supporting the windows build.  Is this something that you could look at submitting a patch for?  It looks like a header file is not being included that is needed on windows.

**Comment by joshuayabut** [comment]
The problem comes from bitcoin-seeder using Unix/Linux dependencies. 

You can get a working bitcoin build by using `CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --with-seeder=no` to disable compiling the seeder.

**Comment by cqtenq** [comment]
CXX    seeder/bitcoin_seeder-main.o
seeder/main.cpp: In function 'int main(int, char**)':
seeder/main.cpp:471:12: error: 'SIGPIPE' was not declared in this scope
     signal(SIGPIPE, SIG_IGN);
            ^
make[2]: *** [seeder/bitcoin_seeder-main.o] Error 1

I encountered the same error.

**Comment by jasonbcox** [comment]
I don't have a windows dev machine setup, but if someone can try to fix it, I think the issue needs to be fixed in a similar manner as it is in init.cpp:
```
54 #ifndef WIN32
55 #include <signal.h>
56 #endif
```
and
```
1294 #ifndef WIN32
...
1316     signal(SIGPIPE, SIG_IGN);
1317 #endif
```

**Comment by jasonbcox** [comment]
For posterity: https://reviews.bitcoinabc.org/D1602

**Comment by jasonbcox** [comment]
This fix will be in the upcoming release.
