### ISSUE TITLE
Is there any api to get the Legacy address in Version 0.17.0

### ISSUE THREAD

**Issue by bajian** [Bitcoin-ABC/bitcoin-abc#192]
I call `getnewaddress`  in Version 0.17.0
It returns the CashAddr . So how can i conver to the Legacy address?
As I known ,the `getnewaddress` has the params to get both CashAddr and Legacy in Version 0.16.2

**Comment by schancel** [comment]
https://cashaddr.bitcoincash.org

Otherwise there is a converted built into Electron Cash, or you may launch the ABC software with `-usercashaddr=0` and find the key again.

**Comment by axelay** [comment]
Correction - this should be ```-usecashaddr=0```

**Comment by gtabmx** [comment]
Quite frankly, this is a poor solution. Shipping without an RPC endpoint to convert from legacy to bech32, and vice versa, is short-sighted and negligent. Then, to further suggest using a online interface, is absurd.

**Comment by bajian** [comment]
@gtabmx I have found a local script to convert the address , and it does work well in my project!
https://github.com/schancel/cashaddr-converter/
it can be built into a script and be called by php ,java etc.

**Comment by gtabmx** [comment]
@bajian Thanks. I found an npm module and just spun up a microservice. However, given that everything necessary to do so was already loaded in my ABC node, it feels silly that I have to do this all all.
