### ISSUE TITLE
Illegal content on the blockchain with OP_RETURN

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [Bitcoin-ABC/bitcoin-abc#194]
What if someone posted for example child pornography using multiple OP_RETURN in few thousand transactions over time and accused miners of storing cp on their hard drives to make it illegal to store BCH chain in most of the countries and discredit bitcoin cash? I'm afraid that planned update and memo.cash protocol might make it pretty easy.

**Comment by rojii** [comment]
You're joking right? You have to be joking.

**Comment by NiKiZe** [comment]
There is already viruses and a lot of different things in the blockchain already. If this really is an issue for anyone running a node then you will just have to purge those transactions.

From a legal perspective I'm sure this will force updates of the laws itself since they don't make any sense.

**Comment by KarolTrzeszczkowski** [comment]
@NiKiZe So is it possible to delete all those transactions even if you don't know which one contains bad stuff which don't? I know you can reject OP_RETURN if you want but is it possible after the block is forged? Doesn't it make the whole chain invalid, with the wrong checksum? And as for updates of laws to make it possible for people to store cp for others - you have to be kidding me. 

@rojii That's not a joke. I'm completely serious.

**Comment by NiKiZe** [comment]
Search for blockchain pruning.
Yes transactions are needed to be available if they are unspent. OP_RETURN is always spent so as soon as the transaction has been validated you remove it.

But again, with enough random data you could find anything in it. And to anyone that stores the blockchain that contains "random data" there is no basis for claiming it to be anything other then transactions on the blockchain.

**Comment by KarolTrzeszczkowski** [comment]
Alright. I'm waiting for devs to comment.

**Comment by dexX7** [comment]
Even without OP_RETURN, there are always ways to embed data. In the last instance data can be encoded in P2PKH scripts and there is no way to avoid this.

**Comment by schancel** [comment]
This issue has already been beaten to death.  Anything can be illegal content under the right mathematical transformation.  There is no particular concern for OP_RETURN.
