### ISSUE TITLE
Have trouble when join bitcoin cash chat room

### ISSUE THREAD

**Issue by wu-sheng** [Bitcoin-ABC/bitcoin-abc#199]
Hello, everyone, I am new, and intend to join the bitcoin cash community.

I am an open source lover for several years, as a creator, PMC and committer of Apache SkyWalking project, contributor or member of CNCF, W3C and Apache projects. You could find my experiences from here : https://github.com/wu-sheng/me

I am facing the first blocking about join your chat room. In `CONTRIBUTING` guide, I found this URL: https://t.me/joinchat/HCYr50mxRWjA2uLqii-psw  But I received an access deny in browser.

I assume this may be caused by `https://t.me`/.....

Could some one help me on that? Or provide me a new or full url to the chat room. Thanks.

BTW, I have already registered and login https://reviews.bitcoinabc.org/ . Your code contribution way is new to me, (I and other projects always use GitHub pull request). But I could learn that when I want to contribute something.

**Comment by schancel** [comment]
Try joining the telegram group again.  Telegram was down most of yesterday.

**Comment by wu-sheng** [comment]
hi, I still got this,
>net::ERR_CONNECTION_REFUSED

Dont be sure why. I will try tomorrow, by using another internet access point.

**Comment by wu-sheng** [comment]
I installed telegram on my cell phone. Which should I search for your official channel?

Thanks.

**Comment by rojii** [comment]
https://t.me/joinchat/HCYr50mxRWjA2uLqii-psw

**Comment by wu-sheng** [comment]
Yes, I am aware of that. But sadly the link doesnot work for me. So I want to run the text/channel  name search in telegram. 

Could do provide me that?

**Comment by rojii** [comment]
Abc Development try that

**Comment by wu-sheng** [comment]
Only found a two people channel. Cant be right, I assume.
