### ISSUE TITLE
InvalidChainFound at block 478558

### ISSUE THREAD

**Issue by liv-io** [Bitcoin-ABC/bitcoin-abc#202]
# Description
I am unable to synchronize the full BCH blockchain with the latest 0.17.0 Bitcoin ABC node. The synchronization gets stuck at block 478558 (BTC/BCH hard fork).

## Error Message
```
2018-04-19 21:46:12 InvalidChainFound:  current best=0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43  height=478558  log2_work=86.861467  date=2017-08-01 13:16:14
```

# Steps to reproduce
1. Download Bitcoin ABC node in version **0.17.0**:
https://download.bitcoinabc.org/0.17.0/linux/bitcoin-abc-0.17.0-x86_64-linux-gnu.tar.gz
2. Install Bitcoin ABC node
3. Configure Bitcoin ABC node to synchronize full blockchain (default settings)
https://jlopp.github.io/bitcoin-core-config-generator/
4. Start Bitcoin ABC node and print logs

# Expected behaviour
Synchronization of full BCH blockchain should work with node versions released after BTC/BCH hard fork.

# Actual behaviour
Synchronization gets stuck at block 478558 (BTC/BCH hard fork) when running a Bitcoin ABC node in version 0.17.0 from scratch.

# Information
Bitcoin ABC version: 0.17.0
Operating System: CentOS 7 (x86_64)
Processor: 4 Cores
Memory: 8192 MB
Disk Size: 300 GB (on RAID5)
Disk Type: SSD ~500 MB/s sequential read and write

# Workaround
I was able to synchronize the full BCH blockchain with the following procedure:

1. Download Bitcoin ABC node in version **0.14.6**
https://download.bitcoinabc.org/0.14.6/linux/bitcoin-0.14.6-x86_64-linux-gnu.tar.gz
2. Start Bitcoin ABC node in version **0.14.6**
```/app/bitcoind-abc/bitcoin-0.14.6/bin/bitcoind```
3. Stop the synchronization in the beginning of November 2017 before the DAA hard fork (Difficulty Adjustment Algorithm Update)
4. Upgrade to first version supporting the DAA hard fork
https://download.bitcoinabc.org/0.16.0/linux/bitcoin-abc-0.16.0-x86_64-linux-gnu.tar.gz
5. Start Bitcoin ABC node in version **0.16.0**
```/app/bitcoind-abc/bitcoin-abc-0.16.0/bin/bitcoind```
6. Stop the synchronization in mid April before Network Upgrade hard fork
7. Upgrade to first version supporting the Network Upgrade hard fork
https://download.bitcoinabc.org/0.17.0/linux/bitcoin-abc-0.17.0-x86_64-linux-gnu.tar.gz
8. Start Bitcoin ABC node in version **0.17.0**
```/app/bitcoind-abc/bitcoin-abc-0.17.0/bin/bitcoind```

# Other

- Run the following commands, if the synchronisation gets stuck at BTC/BCH hard fork
```
/app/bitcoind-abc/bitcoin-0.14.6/bin/bitcoin-cli invalidateblock 0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43
/app/bitcoind-abc/bitcoin-0.14.6/bin/bitcoin-cli reconsiderblock 0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43
```

**Comment by schancel** [comment]
Please try updating to 0.17.1.  It includes a patch which may solve this issue for you.

**Comment by liv-io** [comment]
Many thanks for the quick reply 👍 
I could not find any release notes mentioning a fix for this issue, but I will give it a try and let you know.

**Comment by buzztiaan** [comment]
didnt fix it?

**Comment by deadalnix** [comment]
No new about this and it is presumably fixed. Closing.

**Comment by liv-io** [comment]
The new release `0.17.1` did fix the problem. I was able to synchronize the full blockchain from scratch. Thanks! (It took me a while to test, as I was short on SSD storage.)

Could you please mention this fix in the release notes? Complete synchronization with releases between `0.14.6` and `0.17.1` is broken.
