### ISSUE TITLE
estimatesmartfee testnet=1 always -1?

### ISSUE THREAD

**Issue by knoxcard** [Bitcoin-ABC/bitcoin-abc#204]
estimatesmartfee call in testnet mode true is always returning -1, even though my blockcount is showing 1,231,644.

**testnet=0 works fine**.

```
estimatesmartfee 1
{
  "feerate": -1,
  "blocks": 25
}
```

```
getblockcount
1231664
```

**Comment by knoxcard** [comment]
Seems to be working all of a sudden!  Closing ticket...

**Comment by schancel** [comment]
Note: estimatesmartfee is being removed next release.  It's not particularly useful to bitcoin cash.  I am currently working on better ways to handle fees.

**Comment by knoxcard** [comment]
Okay, I was going to say my website relies heavily on this feature, but Bitcoin cash transaction fees are so ridiculously inexpensive, what's the point I guess, lol.  Now Bitcoin on the other hand....

Do you have a name for this new command line function at the moment, so I can keep a lookout when it gets released?  Thanks for the great work!

**Comment by schancel** [comment]
Can you use estimatefee?  The API is pretty similar.  I was planning to swap out the logic to use the minrelayfee

**Comment by knoxcard** [comment]
LOL, I had not realized I posted bcash-cli.  I simply copy and pasted the output of my Linux terminal.  I did this because it absolutely required in order to run both Bitcoin and Bitcoin Cash full node on the same server, they conflict with one another.  Funny, how I read an article today and it stated that some take offense to referencing Bitcoin Cash as BCash.  Those were not my intentions, lol.
