### ISSUE TITLE
BCH 3rd party wallet

### ISSUE THREAD

**Issue by eugeneives** [Bitcoin-ABC/bitcoin-abc#206]
Hi guys. Im Eugene from Guarda Wallet. Right now, we are doing a non-custodial BCH wallet for android/web. I have some questions. 

1. We need upgrade daemon to bitcoinabc?
2. Our SVP libs and bitcoincashjs will work correctly after the upgrade? 

Thnks

**Comment by knoxcard** [comment]
I am not part of the official team, but I am sure you will be just fine.  Just setup a test server and go wild, bet it all works the same.

**Comment by knoxcard** [comment]
@eugeneives - Close Ticket?

**Comment by eugeneives** [comment]
@knoxcard yes, pls
We successfully updated!

**Comment by knoxcard** [comment]
@eugeneives - great to hear and congrats!
