### ISSUE TITLE
Please pgp sign commits and releases

### ISSUE THREAD

**Issue by gabegattis** [Bitcoin-ABC/bitcoin-abc#208]
Signed releases and signed git commits would improve the confidence and perceived legitimacy of this project. Core, BU, XT, and others have done pretty well in this regard. Bitcoin ABC should do the same. 
On our teams, we have made pgp signing of git commits mandatory.

Even if you do not have a plan for who should be performing and signing gitian builds, you can still sign your git commits. https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by knoxcard** [comment]
I think this will increase the number of nodes quite a bit and should be done ASAP

**Comment by jasonbcox** [comment]
I know the other ticket is old, but it is being talked about through other channels: https://github.com/Bitcoin-ABC/bitcoin-abc/issues/48 Until someone has the time to build proper signing infrastructure, we'll need to rely on devs publishing their signatures themselves (which is far from ideal).

**Comment by strotter** [comment]
https://download.bitcoinabc.org/0.18.0/linux/bitcoin-abc-0.18.0-x86_64-linux-gnu.tar.gz.schancel.asc

Where can I find the public key to verify this signature?  I don't see it on the website anywhere..  For example, tor browser gives you instructions on which key to import for verification and which commands to run but the Bitcoin ABC website has nothing anywhere that I can find.
