### ISSUE TITLE
Missing difficulty reset

### ISSUE THREAD

**Issue by RHavar** [Bitcoin-ABC/bitcoin-abc#21]
After the HF it's quite possible there will not be enough mining hash power behind bitcoin ABC to ensure it's survival. For this reason I suggest a difficulty reset system in the same light as testnet, until after the first proper difficulty reset period. (Or something like that?)

**Comment by deadalnix** [comment]
Like this: https://reviews.bitcoinabc.org/rABC7ad1105f43d7bff158d4b5c882ab9bf1b74d6cce ;)

**Comment by RHavar** [comment]
Oh awesome! Looks like I missed that. Guess it should be added to the spec and marketing too then?

**Comment by deadalnix** [comment]
Yes, this is ongoing.
