### ISSUE TITLE
BitcoinABC stuck at block #530361 after upgrade 0.16.2   to 0.17.1

### ISSUE THREAD

**Issue by baawithme** [Bitcoin-ABC/bitcoin-abc#213]
After upgrading bitcoinABC 0.16.2   to 0.17.1 it never gets new blocks  and throws 
 PROCESSMESSAGE: INVALID MESSAGESTART version 
messages frequently.
I've tried to delete chanstate&blocks and resync chain  it downloaded chain until block #530361 and did same thing i wrote above . 
I downloaded bitcoinAbc binaries from https://download.bitcoinabc.org/0.17.1/linux/bitcoin-abc-0.17.1-x86_64-linux-gnu.tar.gz
My machine:
Debian 9 stretch,
2 CPU
8 GB RAM 
150 GB HDD

**Comment by jasonOramo** [comment]
see the answer from  "ftrader" by 'invalidateblock and invalidateblock a previous block'.
https://github.com/Bitcoin-ABC/bitcoin-abc/issues/209

**Comment by jasonOramo** [comment]
Here is the answer I copy from ftrader.

----------COPY FROM https://github.com/Bitcoin-ABC/bitcoin-abc/issues/209 ----------

I tried it out by synching to the minority chain with a 0.16.2 client.

Then I did as follows to get onto the majority chain:

Invalidate a pre-fork block:

$ bitcoin-cli invalidateblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e

Stop the client:

$ bitcoin-cli stop

Upgrade to 0.17.1 and restart the daemon (not shown)

Reconsider the block I previously invalidated:

$ bitcoin-cli reconsiderblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e

I did not need to manually change my peers.dat or banlist.dat, but I didn't leave much time for all my peers to become banned. It may be wise to delete those files (or move them out the way) before restarting the upgraded daemon.

----------COPY FROM https://github.com/Bitcoin-ABC/bitcoin-abc/issues/209 ----------

**Comment by baawithme** [comment]
it did not work for me. fully syncing a fresh machine  with 0.17.1

**Comment by rosmo01** [comment]
Incomprehensible there is no upgrade notification in GUI - that is a fundamental best practice!!

With it there would not be a huge number (16-17%) of non-updated nodes, but I guess the developers don't care..

This worked for me: 
reconsiderblock 0000000000000000011ada8bd08f46074f44a8f155396f43e38acf9501c49103
restart 
and the sync to main started immediately.

**Comment by johnzweng** [comment]
Hi! 

I also experience the same problem.
I am running `Bitcoin ABC version v0.17.1.0-e1fa952` (downloaded from 
https://download.bitcoinabc.org/0.17.1/linux/src/bitcoin-abc-0.17.1.tar.gz)

sha256sum of the binary:
`93860ee0d1683968d88157c56c52c590bf05e803dd1d4608fc4089e24139b93f  /opt/bitcoin-abc-0.17.1/bin/bitcoind`

The node also seems to be stuck at block-height **530361**. But when I compare my blocks with these public block-explorers it seems that my node is on a different chaintip:

- https://www.blocktrail.com/BCC
- https://bch-insight.bitpay.com/
- https://blockchair.com/bitcoin-cash/blocks?s=id(desc)

My node shows a current height of `530361`

And the hashes of the last 4 blocks:

`bitcoin-cli getblockhash 530361`: `000000000000000001863cc51b8c32b4e1a6105253cbab88e8e9335a92bff84d`

`bitcoin-cli getblockhash 530360`
`000000000000000000e2620c245f007f49fb08a51e3f412c436a98ae173dfcb4`

`bitcoin-cli getblockhash 530359`
`0000000000000000012f7ed499fd8f51fa6b9ea0c1e35ed24d11b5bee8c8b0fe`

`bitcoin-cli getblockhash 530358`
`00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83`

If you compare these hashes with the ones from public block-explorers, it seems like **530358** was the last common blocks and the latest 3 blocks (530359 - 530361) diverged from the main chain.

If I try the tip posted above and invalidate and reconsider the latest common block, my node immediately syncs again to the *wrong* chain-tip:

**Invalidate latest common ancestor block:**
`bitcoin-cli invalidateblock 00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83`

```
2018-05-22 09:53:06 UpdateTip: new best=000000000000000000e2620c245f007f49fb08a51e3f412c436a98ae173dfcb4 height=530360 version=0x20000000 log2_work=87.29091 tx=249419214 date='2018-05-16 01:02:07' progress=0.992990 cache=2.1MiB(15243txo)
2018-05-22 09:53:08 UpdateTip: new best=0000000000000000012f7ed499fd8f51fa6b9ea0c1e35ed24d11b5bee8c8b0fe height=530359 version=0x20000000 log2_work=87.290889 tx=249416576 date='2018-05-15 19:16:03' progress=0.992727 cache=1.6MiB(11180txo)
2018-05-22 09:53:08 UpdateTip: new best=00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83 height=530358 version=0x20000000 log2_work=87.290869 tx=249415371 date='2018-05-15 18:17:47' progress=0.992683 cache=1.4MiB(9785txo)
2018-05-22 09:53:08 UpdateTip: new best=000000000000000000f59580044b235c4f46381cacd319d29e8bb21c517a771d height=530357 version=0x20000000 log2_work=87.290848 tx=249415086 date='2018-05-15 18:08:18' progress=0.992676 cache=1.4MiB(9507txo)
2018-05-22 09:53:12 InvalidChainFound: invalid block=00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83  height=530358  log2_work=87.290869  date=2018-05-15 18:17:47
2018-05-22 09:53:12 InvalidChainFound:  current best=000000000000000000f59580044b235c4f46381cacd319d29e8bb21c517a771d  height=530357  log2_work=87.290848  date=2018-05-15 18:08:18
```

**And reconsider the block again:**
`bitcoin-cli reconsiderblock 00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83`

```
2018-05-22 09:54:58 UpdateTip: new best=00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83 height=530358 version=0x20000000 log2_work=87.290869 tx=249415371 date='2018-05-15 18:17:47' progress=0.992681 cache=1.4MiB(9785txo)
2018-05-22 09:54:58 UpdateTip: new best=0000000000000000012f7ed499fd8f51fa6b9ea0c1e35ed24d11b5bee8c8b0fe height=530359 version=0x20000000 log2_work=87.290889 tx=249416576 date='2018-05-15 19:16:03' progress=0.992726 cache=1.6MiB(11180txo)
2018-05-22 09:54:59 UpdateTip: new best=000000000000000000e2620c245f007f49fb08a51e3f412c436a98ae173dfcb4 height=530360 version=0x20000000 log2_work=87.29091 tx=249419214 date='2018-05-16 01:02:07' progress=0.992988 cache=2.1MiB(15243txo)
2018-05-22 09:54:59 UpdateTip: new best=000000000000000001863cc51b8c32b4e1a6105253cbab88e8e9335a92bff84d height=530361 version=0x20000000 log2_work=87.290929 tx=249419841 date='2018-05-16 02:30:22' progress=0.993055 cache=2.2MiB(16195txo)
```

I also tried stopping and restarting in between, but this doesn't change anything.

When looking up, to which other nodes I am connected to:
`bitcoin-cli getpeerinfo | grep subver | sort | uniq -c`
I see at least some other 0.17.1 nodes:
```
      2     "subver": "/Bitcoin ABC:0.16.1(EB8.0)/",
      2     "subver": "/Bitcoin ABC:0.16.2(EB8.0)/",
      5     "subver": "/Bitcoin ABC:0.17.1(EB32.0)/",
      1     "subver": "/bitnodes.coin.dance:0.1/",
      1     "subver": "/bitnodes.earn.com:0.1/",
      1     "subver": "/cashnodes.io:0.0.1/",
```


**QUESTIONS:**
- Shouldn't my node automatically reorg to the chain with the highest work?
- What is going on here? 
- And how can I resolve this situation?

**Comment by johnzweng** [comment]
What.. the hell.. ? It works for me now (but I don't know why):

After posting the previous comment I once again (I did it 2 times before) did the same steps as described in previous comment (invalidating and reconsidering 00000000000000000031687b7320832e5035abe8e3f81fb71517fc541765de83) and suddenly it syncs again?

This looks scary to me.. Why didn't it reorg before automatically? Hmm..

**Comment by knoxcard** [comment]
Close Ticket?

**Comment by deskal** [comment]
I am a crypto user and not a programmer, so the above is not helpful to me.
I upgraded to 0.17.1 on my MacPro (OSX) and got "connecting to peers" and a halt at block 530361 as above. I am highly alarmed that this supposedly very safe way of storing coin in a node on my Mac suddenly gives a problem and there is apparently no way of asking for help on Bitcoin ABC.org. Very grateful to anyone who can help with an explanation suitable for non programmer ears. I just want to get my money out into a wallet that is reliable, Many thanks in advance.

**Comment by schancel** [comment]
You will need to start bitcoin-qt in -server mode via `Terminal.app`

```
> curl -o- https://download.bitcoinabc.org/0.17.1/osx/out/bitcoin-abc-0.17.1-osx64.tar.gz | tar -zxf-
> ./bitcoin-abc-0.17.1/bin/bitcoin-qt -server &
> ./bitcoin-abc-0.17.1/bin/bitcoin-cli invalidateblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e
> ./bitcoin-abc-0.17.1/bin/bitcoin-cli reconsiderblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e
```

Please let me know if this works for you.  I can possibly do a video call to show you what needs to be done in more detail.  I would recommend using an SPV wallet in the future.

- Cheers

**Comment by pandabr** [comment]
Hi.. I am Stucked...

**Comment by Notexpert** [comment]
A bit late to this. Understand nothing of this. However also stuck in 350358... Dont understand how to "invalidate a block". Just a short question. What happens if I download the whole chain again.
Will I get stuck when coming there? Thanks , if anyone sees this. :)

**Comment by MartinSolie** [comment]
I've done invalidate/update/reconsider process, but I was still stuck at 530361.
Then I added IPs of several nodes from https://cashnodes.bitcoinunlimited.info/nodes, running Bitcoin-ABC 0.17.1+ and restarted bitcoin.
Then sync process continued.
I don't know whether just adding nodes helps, but combination worked in my case.

( To say your bitcoin node to try to connect to some specific nodes use [addnode](https://en.bitcoin.it/wiki/Running_Bitcoin) field in your bitcoin.conf file e.g.
```
server=1
daemon=1
txindex=1
...

addnode=106.15.52.170
addnode=96.126.122.17
```
)

**Comment by Notexpert** [comment]
Thanks, I went through the process of starting off fresh. Downloading the whole thing. Worked fine with 0.17.2

**Comment by sriharikapu** [comment]
This is crazy guys!! It's killing me. 

```
# if you are struck with at a block 530361
git checkout v0.18.2
bitcoin-cli stop
./autogen.sh
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --with-gui
make
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/" --with-gui
#############################################################################################
# if you have this issue : configure: error: libdb_cxx headers missing, Bitcoin ABC requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
make
Possible Error > Makefile:618: recipe for target 'config.status' failed
Possible Error > make: *** [config.status] Error 1
sudo apt-get install libdb++-dev
./configure
sudo make install
#############################################################################################
src/qt/bitcoin-qt
```

**Comment by JesseBusman** [comment]
I had the same problem at 530361 with Bitcoin Limited. Invalidating a previous block, restarting, then reconsidering it solved it.

Thank you. :)

**Comment by jasonbcox** [comment]
Closing since this is 2-3 major version numbers behind and instructions have been provided on how to remedy the issue.
