### ISSUE TITLE
Get cash address from legacy

### ISSUE THREAD

**Issue by TAiS46** [Bitcoin-ABC/bitcoin-abc#214]
We keep a database with our legacy addresses as user still send BCH to them. Is there a simple way to convert the legacy address to the new format?

**Comment by schancel** [comment]
Hi @TAiS46 , You can turn off cashaddr in the node via `usecashaddr=0` in the bitcoin.conf.  However, if you let me know what programming language your backend is in, I can point you to an appropriate library for doing conversations.

**Comment by TAiS46** [comment]
but `usecashaddr=0` will turn it of in general right? We are using rails

**Comment by schancel** [comment]
Yes, it will.  Here is a ruby gem maintained by coinbase engineer @zquestz

https://rubygems.org/gems/cash-addr/versions/0.1.1

**Comment by TAiS46** [comment]
should work, thanks
