### ISSUE TITLE
how can i create old address 

### ISSUE THREAD

**Issue by wang628625** [Bitcoin-ABC/bitcoin-abc#216]
i compile the new wallet ,but i get the address is the new format ,now i want create old format address ,how to do it

**Comment by knoxcard** [comment]
I wish there was an rpc command, but it's deprecated so they probably wont do it.

Go here...use blockdozer.com
https://www.blockdozer.com/address/bitcoincash:qzuds3g9rx0f0w4yvqqc46wn67zawrd9dv2ugxklt0

**Comment by knoxcard** [comment]
Here is the better answer programmatically speaking...

https://github.com/bitcoincashjs/bchaddrjs

**Comment by wang628625** [comment]
think you

**Comment by knoxcard** [comment]
Here is the code I used, works like a charm...

```
					if(symbol == 'bch') {
						var toLegacyAddress = require('bchaddrjs').toLegacyAddress
						dep_address_rec.update({
							blob: {
								legacy: toLegacyAddress(new_dep_address)
							}
						}).then(dep_address_rec => {
						})
					}
```

**Comment by knoxcard** [comment]
@wang628625 - close ticket?

**Comment by jasonbcox** [comment]
Please see https://github.com/Bitcoin-ABC/bitcoin-abc/issues/175
