### ISSUE TITLE
Addressindex in Bitcoin ABC v0.17.2

### ISSUE THREAD

**Issue by vserpokryl** [Bitcoin-ABC/bitcoin-abc#217]
I'm used Bitcoin ABC Daemon version 0.16.2.0-ce02b04
v0.16.2.0 has rpc methods for address&txs
```
== Addressindex ==
getaddressbalance
getaddressdeltas
getaddressmempool
getaddresstxids
getaddressutxos
```

But v0.17.2 does not have these rpc methods...

My config:
```
server=1
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcallowip=127.0.0.1
rpcuser=user
rpcpassword=pass
```

How to enable addressindex in v0.17.2?

**Comment by dexX7** [comment]
While there is a rather old patch flying around for adding an address index, I'm pretty sure it was never part of ABC. This patch also has different commands than the one you posted.

However, they seem to refer to Bitcore:

https://bitcore.io/guides/bitcoin/
