### ISSUE TITLE
Cannot install 0.17.2 on macos since Avira always say that there is an virus in the software

### ISSUE THREAD

**Issue by jasonOramo** [Bitcoin-ABC/bitcoin-abc#219]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

Cannot install the 0.17.2 or 0.17.1 version in macos because of Avira scan. There is an file 'PUA/OSX.CoinMiner.juiax' and that's why Avira block the installer.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. install and start the Avira in a mac.
2. download the dmg install from bitcoinabc.com (version 0.17.1 or 0.17.2)
3. The installer would be moved by Avira.

### Expected behaviour

What's the point of the CoinMiner? It's a virus or  as expected?

### Actual behaviour

Cannot install the bitcoin-abc in mac. I stop the avira and install the new version, and start the Avira, the software cannot be started.

**Comment by jasonbcox** [comment]
Sounds like Avira is detecting bitcoin-abc as a false positive.  CoinMiner is not a part of bitcoin-abc and is likely the behavior name given by Avira rather than an actual file.  Please report this to Avira.  Since there is no action item for ABC, I'm closing this ticket.
