### ISSUE TITLE
Bitcoincash Testnet

### ISSUE THREAD

**Issue by rahulEth** [Bitcoin-ABC/bitcoin-abc#223]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by rahulEth** [comment]
I am trying to sync bch test node on ubuntu but did not getting any source or instruction how to do it. is someone here can help me?

**Comment by jasonbcox** [comment]
See doc/developer-notes.md.  It instructs you to run with the `-testnet` option.  Please reopen this ticket if you continue to have issues.
