### ISSUE TITLE
How to run BCH full node on ubuntu and configuration file format for BCH?

### ISSUE THREAD

**Issue by ishwarchandratiwari** [Bitcoin-ABC/bitcoin-abc#224]
How to install and Launch Bitcoin Cash daemon on machine?
And  what should be the correct BitcoinCash configuration file format for BCH Mainnet, I want to run BCH node with USERNAME and PASSWORD

**Comment by jasonbcox** [comment]
See the docs:
doc/README.md
doc/init.md

**Comment by ishwarchandratiwari** [comment]
Download the appropriate binary from here: https://download.bitcoinabc.org/

tar xzvf bitcoin-abc-0.17.2-x86_64-linux-gnu.tar.gz


cd bitcoin-abc-0.17.2/
cd bin/

rename 's/bitcoin/bitcoinCash/' *

sudo install -m 0755 -o root -g root -t /usr/local/bin *

bitcoinCashd -version 

bitcoind -version 
bitcoinCash-cli getblockchaininfo
bitcoinCashd -daemon
