### ISSUE TITLE
The block Difficulty is equal to powLimit at block height `1189033` in testnet. Is it valid?

### ISSUE THREAD

**Issue by qshuai** [Bitcoin-ABC/bitcoin-abc#226]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

#### If so, please list the steps to reproduce below:
1. bitcoin-cli getblock 0000000000e7cea7e3dcfe74f93e99437ea0452351deecf68c0dfa23a5b2fee7 and you will get the same sitiuation.

So why this block was accepted?

**Comment by deadalnix** [comment]
https://test-bch-insight.bitpay.com/block/0000000000e7cea7e3dcfe74f93e99437ea0452351deecf68c0dfa23a5b2fee7
