### ISSUE TITLE
Need BCH Testnet Coins

### ISSUE THREAD

**Issue by knoxcard** [Bitcoin-ABC/bitcoin-abc#227]
Need BCH Testnet Coins

bchtest:qr4cq9hlkum6mweuecs8q7wrm3f0sj3kwcmatezufu

**Comment by xiaods** [comment]
faucet needed. anyone can provide it.

**Comment by markblundeberg** [comment]
Hmm, not sure why this hasn't been closed yet. There are two functioning faucets I'm aware of right now:

* https://coinfaucet.eu/en/bch-testnet/
* https://testnet.wormhole.cash/faucet/
