### ISSUE TITLE
Build client through Windows Subsystem for Linux errors

### ISSUE THREAD

**Issue by rickal** [Bitcoin-ABC/bitcoin-abc#228]
I've attempted to build the client in cross compilation for windows following the instructions many times, troubleshooting some errors until I got to this error I can't solve:

`CXX      seeder/bitcoin_seeder-main.o
seeder/main.cpp: In function ‘int main(int, char**)’:
seeder/main.cpp:471:12: error: ‘SIGPIPE’ was not declared in this scope
     signal(SIGPIPE, SIG_IGN);
            ^~~~~~~
Makefile:8351: recipe for target 'seeder/bitcoin_seeder-main.o' failed
make[2]: *** [seeder/bitcoin_seeder-main.o] Error 1
make[2]: Leaving directory '/home/xxxx/bitcoin-abc/src'
Makefile:9875: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/xxxx/bitcoin-abc/src'
Makefile:721: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

The (very) strange thing is that if I `make clean` and try again using number of threads parameter `make -j` I get a different error

` CXX      seeder/libbitcoin_seeder_a-dns.o
cc1plus: fatal error: seeder/dns.cpp: Permission denied
compilation terminated.
Makefile:5677: recipe for target 'seeder/libbitcoin_seeder_a-dns.o' failed
make[2]: *** [seeder/libbitcoin_seeder_a-dns.o] Error 1
make[2]: *** Waiting for unfinished jobs....
seeder/bitcoin.cpp: In member function ‘void CSeederNode::Send()’:
seeder/bitcoin.cpp:90:23: error: ‘close’ was not declared in this scope
             close(sock);
                       ^
seeder/bitcoin.cpp: In member function ‘bool CSeederNode::Run()’:
seeder/bitcoin.cpp:306:19: error: ‘close’ was not declared in this scope
         close(sock);
                   ^
Makefile:5649: recipe for target 'seeder/libbitcoin_seeder_a-bitcoin.o' failed
make[2]: *** [seeder/libbitcoin_seeder_a-bitcoin.o] Error 1
seeder/main.cpp: In function ‘int main(int, char**)’:
seeder/main.cpp:471:12: error: ‘SIGPIPE’ was not declared in this scope
     signal(SIGPIPE, SIG_IGN);
            ^~~~~~~
Makefile:8351: recipe for target 'seeder/bitcoin_seeder-main.o' failed
make[2]: *** [seeder/bitcoin_seeder-main.o] Error 1
make[2]: Leaving directory '/home/xxxxx/bitcoin-abc/src'
Makefile:9875: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/xxxxx/bitcoin-abc/src'
Makefile:721: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

Some background: I'm currently using Debian as Ubuntu gave me errors already installing Ubuntu packages. Debian is also smaller file in windows store and was way faster to download packages. I strongly suggest turning off windows defender and adding the distro package to the windows defender exceptions, it will look like

C:\Users\{your **windows** username}\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4

After minimal set up, this is what I did:

- start debian as administrator

- install all necessary packages and exit (was getting some errors before doing this)

- first step again

-  added to path PATH=$PATH:/usr/include:/home/{your **linux** username}/bitcoin-abc just in case (*after* clean up with `PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')` (notice you need to properly reset the path every time you exit debian)

- `sudo apt install software-properties-common` anyway since this package is lacking in debian as well (though the guide only refers to Ubuntu Xenial 16.04)

- up to `CONFIG_SITE=$PWD/depends/i686-w64-mingw32/share/config.site ./configure --prefix=/` no problems, but the next `make` returned error over `#include <arpa/inet.h>` header not found; notice that dns.cpp in the seeder folder uses this;

Now I noticed that the new error is in the seeder libraries, and I look at dns.cpp and notice that

`#include <sys/socket.h>
#include <sys/types.h>`

do not exist in Windows Subsystem for Linux actual folders. They are actually under \usr\include\linux. So I copy the "linux" folder and rename the copy as "sys". Then I get to the point where apparently the libraries compile but I get either of the first two errors above.

I don't know what else to do. I assume that it can be related to other .h and .cpp misplaced inside the distro's folders.

**Comment by jasonbcox** [comment]
Looks related to #190

**Comment by vermorel** [comment]
In order to get the linter of arcanist to work, I had to change the setting in `/etc/update-manager/releases-upgrades` from `lts` to `normal` to finally get Ubuntu to succeed with `sudo apt-get install clang-format-4.0`.

**Comment by jasonbcox** [comment]
Thanks @vermorel, much appreciated: https://reviews.bitcoinabc.org/D1602

**Comment by jasonbcox** [comment]
This fix will be in the upcoming release.
