### ISSUE TITLE
Consensus bug with sighash single

### ISSUE THREAD

**Issue by azure-tom** [Bitcoin-ABC/bitcoin-abc#23]
While testing my implementation of the UAHF I found that Bitcoin ABC does not follow the specification in a corner case.

> In the original algorithm, a `uint256` of `0x0000......0001` is committed if the input index for a `SINGLE` signature is greater than or equal to the number of outputs. In this BIP a `0x0000......0000` is committed, without changing the semantics.

https://github.com/Bitcoin-UAHF/spec/blame/master/replay-protected-sighash.md#L82

But instead of signing a 0 Bitcoin-ABC hashes the data again and signs some hash.  This is confusing and needlessly slow. It should just use an explicit 0 just like the original case in Bitcoin today uses an explicit 1. It is an easy change to match the spec especially because the HF isn't active yet. I hope Bitcoin-ABC will demonstrate that the spec is the spec, unlike the actions of some less professional teams.

Thank you for your hard work, it amazes.

**Comment by deadalnix** [comment]
It set 0 for the hash of the outputs, which is what it does. Signing 0 would allow anyone to spend your coins once you signed once, which is obviously undesirable.
