### ISSUE TITLE
Bitcoind shut off unexpectedly

### ISSUE THREAD

**Issue by assafadar** [Bitcoin-ABC/bitcoin-abc#233]
Info:
1. Run bitcoin abc node (no gui) 0.17.2 from PPA on ubuntu 16.04.04 LTS

After installation and few days of testing everything should work fine - everything was checked in terms of address creation, transaction sending and receiving.

BUG:
After few days suddenly bitcoind starts shutting itself off automatically without me being able to restart it using my custom data dir - I was able to start it after changing the data dir.

- OS: Ubuntu 16.04 LTS
- RAM: 16 GRAM
- Disk size: 200 GB
- Disk Type (HD/SDD): SSD

**Comment by jasonbcox** [comment]
We're going to need more info than this.  Do you have an error message or debug log to provide?

**Comment by assafadar** [comment]
No I tried to figure it out myself but with no luck so I deleted the data dir and re synced it. Now its working, I wouldn't call this a solution.. But I guess this can be closed.
