### ISSUE TITLE
Issue compiling - Debian 9

### ISSUE THREAD

**Issue by knoxcard** [Bitcoin-ABC/bitcoin-abc#243]
./autogen.sh produces the following output...

configure.ac:10: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:73: installing 'build-aux/compile'
configure.ac:33: installing 'build-aux/missing'
Makefile.am:15: warning: user variable 'GZIP_ENV' defined here ...
**/usr/share/automake-1.15/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:544: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here**

**Comment by knoxcard** [comment]
I also ran a **make clean** before starting

**Comment by knoxcard** [comment]
Think this is a similar issue...

https://github.com/bitcoin/bitcoin/pull/11013

**Comment by jasonbcox** [comment]
Closing due to old issue. Please reopen if you're still experiencing this with 0.20.x
