### ISSUE TITLE
Bitcoin ABC version v0.18.1.0-5e02f75  doesn't accept block 530560  ( 00000000000000000195edc6e094ae1db6a274f1188127390a74a727db9a2717 )

### ISSUE THREAD

**Issue by avl42** [Bitcoin-ABC/bitcoin-abc#249]
I had been running an out-of-date version of BitcoinUnlimited before.  That gut stuck at #530561 on a minority fork.

So I got master from this repo  ( v0.18.1.0-5e02f75 )  and it still got stuck at that height.

I then compared blockhashes with a public block-explorer (yes, an BCH one) and noticed that #530360 was first "wrong" one.  I did invalidateblock on the wrong block-hash, now getblockcount returns 530359 but no matter how often I call bitcoin-cli reconsiderblock 00000000000000000195edc6e094ae1db6a274f1188127390a74a727db9a2717, it just doesn't like it, and despite debug=1 it doesn't tell me why it doesn't like it.

### Expected behaviour
it should accept this block https://explorer.bitcoin.com/bch/block/00000000000000000195edc6e094ae1db6a274f1188127390a74a727db9a2717
(shouldn't it?)

### Actual behaviour
it ignores all attempts to "reconsiderblock" it.

### What version of bitcoin-abc are you using?
v0.18.1.0-5e02f75

### Machine specs:
- OS: Linux
- CPU: intel i7
- RAM: 8GB
- Disk size:  ~500GB left on relevant device. 
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
$ bitcoin-cli getblockheader 00000000000000000195edc6e094ae1db6a274f1188127390a74a727db9a2717 
{
  "hash": "00000000000000000195edc6e094ae1db6a274f1188127390a74a727db9a2717",
  "confirmations": -1,
  "height": 530360,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "d722081321a8350df85b4661779f3cac7777c87a31fa5b70fcf89a02a5f29512",
  "time": 1526410326,
  "mediantime": 1526406711,
  "nonce": 3919073716,
  "bits": "1801c29f",
  "difficulty": 624628286707.5839,
  "chainwork": "0000000000000000000000000000000000000000009c98be9d8c7f3fe555222a",
  "previousblockhash": "0000000000000000011ada8bd08f46074f44a8f155396f43e38acf9501c49103"
}

**Comment by avl42** [comment]
PS: I did read about past hardforks (since the big one), but #530360 happened some time in may '18 -- I really thought, that dust would have settled since then.

In the log I see nodes claiming to run  "/Bitcoin ABC:0.17.2(EB32.0)/" and to know 545701 blocks at this time, and other nodes  running "BUCash:1.1.2" and "Bitcoin XBC:0.16.1" claiming that height was mere 530361, and offering me 000000000000000000e2620c245f007f49fb08a51e3f412c436a98ae173dfcb4 which on my node is now marked invalid.

**Comment by avl42** [comment]
$ bitcoin-cli getinfo
{
  "version": 180100,
  "protocolversion": 70015,
  "walletversion": 60000,
  "balance": censored,
  "blocks": 530359,
  "timeoffset": 0,
  "connections": 0,
  "proxy": "",
  "difficulty": 620262324730.7861,
  "testnet": false,
  "keypoololdest": 1514587024,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
$ bitcoin-cli getexcessiveblock
{
  "excessiveBlockSize": 32000000
}

**Comment by avl42** [comment]
one more thing:   bitcoin-cli getchaintips knows about the correct chain:
'''
  {
    "height": 545710,
    "hash": "00000000000000000091e21e5a94e272fc5bf99b9f9a3934f3475c7a7c6efea7",
    "branchlen": 15351,
    "status": "valid-headers"
  },
'''
just why doesn't it jump on it?

**Comment by avl42** [comment]
FWIW, checking out 0.17.2 from github, building it and running it "resolved" my problem at hand.

So, it seems like v0.18.1 has a regression in it that makes it no-longer-accept that one block ...0195... at 530360.  I'd rather not want to believe that v0.18.1 was meant to flip back to that chain tip from May 15th.

**Comment by deadalnix** [comment]
Let me investigate.

**Comment by deadalnix** [comment]
Also, in any case, when facing this kind of issue, it's likely that a previous version of the software flagged the block in some manner. In that case, running the client with reindex should fix it.

**Comment by avl42** [comment]
Is there any **other** such mechanism of flagging than the one of
invalidateblock and reconsiderblock, that I've kept mentioning throughout
this issue so far?



deadalnix <notifications@github.com> schrieb am Fr., 7. Sep. 2018, 17:50:

> Also, in any case, when facing this kind of issue, it's likely that a
> previous version of the software flagged the block in some manner. In that
> case, running the client with reindex should fix it.
>

**Comment by deadalnix** [comment]
There isn't. I suspect BU is setting flags differently from ABC.

**Comment by avl42** [comment]
Well, even if it did, then bitcoin-abc 0.17.2 *was* able to recover from it, whereas 0.18.1 *wasn't*, so there's a regression.

I suspect, that 0.18.1 wasn't ever tested to catch up from a block height around 530360 -- maybe the code to accept block "...0195..." never went into 0.18 branch,  but most people only upgraded to 0.18 at a much later height, and at that point maybe 0.18.1 just skips some checks for such blocks as old as 530360.

Eventually I'll retry 0.18.1 and see if I can still reproduce the problem either by the mere re-upgrade, or at least by invalidating and reconsidering the crucial block manually.  For now, however, I'm just happy that 0.17.2 seems to work fine for me.

**Comment by avl42** [comment]
I do expect enough cooperation between different bch-wallets, that any disagreement on bch details ought to be resolveable by invalidate- and reconsiderblock. if that wasn't the case, then I'd like to know if that was the official stance by bitcoin-abc devels.

As it seems, bitcoinabc 0.17.2 works fine with BU's leftovers, just 0.18.1 didn't.

one doesn't simply re-download these hundreds of gigs without a compelling reason.

**Comment by jasonbcox** [comment]
As @deadalnix said, you can reindex and do not have to redownload the entire chain.

**Comment by avl42** [comment]
just for the record: back then i ran 17.2, which worked, and some time later i went to 18.something again, and then it worked.  not sure if anything had been fixed on 18.* branch, or time itself solved it, but the problem disappeared.
