### ISSUE TITLE
Release 18.1 for Windows, files missing

### ISSUE THREAD

**Issue by jpis** [Bitcoin-ABC/bitcoin-abc#253]
Binaries download folder for 18.1 windows (https://download.bitcoinabc.org/0.18.1/win/) does not contain the expected binaries. I also see there some suspicious files that, according to their names, seem to belong to osx and should be elsewhere.

AFAIK, download folders for previous versions are OK.

**Comment by cculianu** [comment]
Yes.  Where are the windows binaries?

**Comment by jpis** [comment]
The link is my post

**Comment by cculianu** [comment]
FYI -- the Windows Binaries are up now at http://www.bitcoinabc.org.  Apparently deadalnix just forgot to post them!

**Comment by jpis** [comment]
Thanks for the info, I see the files now 😊

 

jpis

 

De : Calin Culianu <notifications@github.com> 
Envoyé : mercredi 12 septembre 2018 22:19
À : Bitcoin-ABC/bitcoin-abc <bitcoin-abc@noreply.github.com>
Cc : jpis <jpis@free.fr>; Author <author@noreply.github.com>
Objet : Re: [Bitcoin-ABC/bitcoin-abc] Release 18.1 for Windows, files missing (#253)

 

FYI -- the Windows Binaries are up now at http://www.bitcoinabc.org. Apparently deadalnix just forgot to post them!
