### ISSUE TITLE
Need BCH Testnet Coins

### ISSUE THREAD

**Issue by dKrishtal** [Bitcoin-ABC/bitcoin-abc#254]
all the faucets do not work, help :)

bchtest:qqqwj6e7609g0v8pvm773xs67lt9sdj45yfh26zn7w

**Comment by DesWurstes** [comment]
https://www.wormhole.cash/test/ works. When you're done, please send it back to bchtest:qpytyr39fsr80emqh2ukftkpdqvdddcnfg9s6wjtfa, which is their wallet.

**Comment by dKrishtal** [comment]
Thanks!

**Comment by FUckAdamCharlieVioletVossyoudo** [comment]
How do i get a test net address?????

**Comment by schancel** [comment]
It's right up on https://www.bitcoincash.org/

**Comment by FUckAdamCharlieVioletVossyoudo** [comment]
OH um ... lols

**Comment by FUckAdamCharlieVioletVossyoudo** [comment]
Sham sir I still don't see it?

**Comment by schancel** [comment]
Scroll down a bit.

https://docs.google.com/spreadsheets/d/1Wg2ciYk7efDFpUD9qIz2Q9-Qp4H8i0Io8ThdDbGdyPU/edit#gid=299033565
