### ISSUE TITLE
need some test coin in testnet3

### ISSUE THREAD

**Issue by AllenYaoya** [Bitcoin-ABC/bitcoin-abc#259]
Hi,

Could anyone tell me how to get some test coins in BCH testnet3? I can't find a valid BCH testnet faucet.

Or someone can send me some to below:
bchtest:qqt0n9z3y27jjdkq7uj25ml8vlww8vmaqsmkx4jgvk

Thanks a lot,
Ya

**Comment by schancel** [comment]
https://twitter.com/gepaoletti/status/1049319563681255424

**Comment by schancel** [comment]
That should have all the information you need.
