### ISSUE TITLE
Migration from Bitcoin Unlimited

### ISSUE THREAD

**Issue by tuxayo** [Bitcoin-ABC/bitcoin-abc#26]
We could gather here instructions and feedback about migrating a node from BU to Bitcoin ABC.

So, anything in particular to do in order to migrate besides installing Bitcoin ABC and running it?
- Anything about the config?
- Any caveats?

Other places where this question has been asked:
[subreddit /r/BitcoinABC/](https://www.reddit.com/r/BitcoinABC/comments/6p7glu/how_to_migrate_a_node_from_bitcoin_unlimited_to/)
[subreddit /r/btc/](https://www.reddit.com/r/btc/comments/6p7iw8/migration_from_bitcoin_unlimited_to_bitcoin_abc/)
[Arch Linux unofficial package](https://aur.archlinux.org/packages/bitcoin-abc/#news)

**Comment by ftrader** [comment]
@thezerg has already announced that BU will issue a compatible version.

For those who want to switch, before the fork activates it is just a matter of changing the client.

After the fork, you need to make sure you run the right client (UAHF-compatible, i.e. ABC or special BU/Classic/XT versions) on the right blockchain data (i.e. the Bitcoin Cash / UAHF chain data).

ABC supports the `excessiveblocksize` parameter used by BU config, so there is nothing to change there at the moment.

Please help to forward this info to other places.

---

Switching to the Bitcoin Cash chain *after* the fork will require some more actions.
Once there are good instructions, I'll try to remember to link them here too.

**Comment by naconner** [comment]
This is what I've used on Ubuntu 14.04:

```
sudo add-apt-repository --remove -y ppa:bitcoin-unlimited/bu-ppa
sudo apt-get remove -y bitcoind
sudo add-apt-repository -y ppa:bitcoin-abc/ppa
sudo apt-get update -y
sudo apt-get install -y bitcoind
start bitcoind
```

**Comment by tuxayo** [comment]
> For those who want to switch before the fork activates - it is just a matter of changing the client. They can work on the same blockchain data files right now

Thanks, it worked for me :)
