### ISSUE TITLE
datadir specified in conf file but didn't take effect

### ISSUE THREAD

**Issue by huahuayu** [Bitcoin-ABC/bitcoin-abc#261]
### Describe the issue
-datadir configured in conf file but not used

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1.
my config file:
as you can see datadir is specified
``` bash
# This config should be placed in the following path:
# ~/.bitcoincash/bitcoincash.conf

# [core]
# Specify the location of the configuration file. To use non-default location, create a default location config file containing this setting.
conf=~/.bitcoincash/bitcoincash.conf
# Specify a non-default location to store blockchain and other data.
datadir=/mnt/bitcoincash

# [debug]
# Run this node on the Bitcoin Test Network.
testnet=1

# [rpc]
# Accept command line and JSON-RPC commands.
server=1
# Accept public REST requests.
rest=1
# RPC user
rpcuser=rpcuser
# RPC password
rpcpassword=rpcpass
# RPC allow ip (allow all)
rpcallowip=0.0.0.0/0
# RPC bind
rpcbind=0.0.0.0
# get all transaction
txindex=1
```
2. run bitcoincash node with below command:
`bitcoincashd -conf=~/.bitcoincash/bitcoincash.conf -deamon`
no error occurs

3. check the process is indeed runing with `ps -ef | grep bitcoincash` or `htop`, yeah, I can see the process is runing

4. cd to the datadir I specified (/mnt/bitcoincash/bitcoincashd) and **found there is no data**, and then I checked ~/.bitcoind, ~/.bitcoincashd, without lucy, **there is no data too**

5. but if I specific the datadir as command line option `bitcoincashd -conf=~/.bitcoincash/bitcoincash.conf -datadir=/mnt/bitcoincash` this is work 

### Expected behaviour
if I specific datadir in conf file then it should be work as same as the command line option

### Actual behaviour
conf in conf file didn't take effect

### Screenshots.
n/a

### What version of bitcoin-abc are you using?
v0.18.2.0-6a51d4f

### Machine specs:
- OS: ubuntu 16.04
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
I have bitcoin core running in the same server, so I change the binary name of bitcoincash while install(from bitcoin to bitcoincash) to differential them

**Comment by schancel** [comment]
Unfortunately, this is intended behavior.  The config file is found in the data dir, and at that point the config has already been loaded.  It's not possible to change the data dir from a config which resides in the default datadir.

**Comment by huahuayu** [comment]
> Unfortunately, this is intended behavior. The config file is found in the data dir, and at that point the config has already been loaded. It's not possible to change the data dir from a config which resides in the default datadir.
> 
> You will need to change your startup script to set the `-datadir` flag.

sorry, I can't understand, why can't I specify the datadir in conf file? I don't think it's  intended behavior, I think the real problem is I run bitcoin core and bitcoin cash in the same server with the same user.  
 
Because yesterday I created another linux user for test(that's say user B), I install bitcoin core for user A and bitcoin abc for user B, so that they don't mix up. 

I run bitocoin abc with below conf:
```
# This config should be placed in following path:
# ~/.bitcoin/bitcoin.conf

# [core]
# Specify the location of the configuration file. To use non-default location, create a default location config file containing this setting.
conf=~/.bitcoin/bitcoin.conf
# Specify a non-default location to store blockchain and other data.
datadir=/mnt/bitcoincash/

# [debug]
# Run this node on the Bitcoin Test Network.
testnet=1

# [rpc]
# Accept command line and JSON-RPC commands.
server=1

# Accept public REST requests.
rest=1

# RPC user
rpcuser=rpcuser

# RPC password
rpcpassword=rpcpass

# listen for connections
port=17333

# RPC prot
rpcport=17332 #for testnet
#rpcport=7332 #for mainnet

# RPC allow ip (allow all)
rpcallowip=0.0.0.0/0

# RPC bind
rpcbind=0.0.0.0

# get all transaction
txindex=1
```

run it with below command: 
```
bitcoind -reindex -daemon
```

and it works, the data is written to /mnt/bitcoincash. So, you see, I can change the datadir by conf, no need put it as a command option.

I am confused, why not to differential the command/port with bitcoin core...  which make life easier

**Comment by schancel** [comment]
Bitcoind looks for the conf file in the datadir.  If the conf file is what specifies the datadir, how can it find the conf file in the first place?  Since this is not possible to know; the conf file may not specify the datadir at all.
