### ISSUE TITLE
hi, ios developer how to get bch address by privateKey?

### ISSUE THREAD

**Issue by QA411** [Bitcoin-ABC/bitcoin-abc#267]
hi, ios developer how to get bch address by privateKey?

**Comment by jasonbcox** [comment]
You probably don't want to be running ABC on a mobile device, but that said, you can import the private key, adding it to an account, and then retrieve the address.  Just make sure to turn rescanning off or it will take a while to scan for funds.

importprivkey <my-private-key> <my-account-name> false
getaccountaddress <my-account-name>
