### ISSUE TITLE
Checksums for Windows binary download files are incorrect for 0.18.3

### ISSUE THREAD

**Issue by KyrosKrane** [Bitcoin-ABC/bitcoin-abc#271]
The checksum for multiple Windows download files is incorrect. The reported checksum in bitcoin-abc-0.18-win-res.yml does not match the calculated checksum from the downloaded binary.

File: **bitcoin-abc-0.18.3-win64-setup-unsigned.exe**
Reported: 9b038d52ca907cbec941c3d312d40754f48eee9327f7d8b885fe1f71504bfe6e
Calculated: 4b9eaef6118d416062c58c72fd235a089930ed23b5d1ca76857ab9d5095a1333

File: **bitcoin-abc-0.18.3-win-unsigned.tar.gz**
Reported: c18498ab94ddebe40443d98f2f30a7fd6fd1e7b6176b4aa0b5a7457928fa93cf
Calculated: 0e617eb8bc91dd9dee7717e5053e065f6653baba133c062fd4c78502610afac1

File: **bitcoin-abc-0.18.3-win32-setup-unsigned.exe**
Reported: 8579febb82a1fcdf98a327e9657dfa9b667ba90d82650727dcae4cbde4df3835
Calculated: 075980274215617fbbf9c55ee9df4ae72b189b16e4ee45d3da758bf9f4a0d3bd

I tested the binary download on both my local machine, and a VM that used a VPN to another country, to help rule out transfer error. The checksum was the same in both cases.

The following files have a calculated checksum that matches the reported checksum.

**bitcoin-abc-0.18.3-win32-debug.zip
bitcoin-abc-0.18.3-win32.zip
bitcoin-abc-0.18.3-win64-debug.zip
bitcoin-abc-0.18.3-win64.zip
src/bitcoin-abc-0.18.3.tar.gz**

I did not test non-Windows files.

**Comment by jasonbcox** [comment]
Hey, sorry about this. There was an incorrect version uploaded early during the release, but it was quickly caught and fixed.  It appears you managed to download it during that short window.  Please try downloading the binaries again: https://download.bitcoinabc.org/0.18.3/win/ the hashes should match.
