### ISSUE TITLE
Is either side (SV or ABC) planning to provide replay protection?

### ISSUE THREAD

**Issue by lacksfish** [Bitcoin-ABC/bitcoin-abc#276]
All fun aside, if these two chains will compete long-term and no replay protection is present there will be a lot of pitfalls ending with unknowing users loosing their coins.

Is there any information on SV or ABC implementing replay protection on the protocol level?    
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/abc/replay-protected-sighash.md

**Comment by xiaods** [comment]
attention

**Comment by ta32** [comment]
also address format changes would be nice

**Comment by c0deright** [comment]
address format change should be implemented at BSV since they forked away from BCH not the other way around.

**Comment by jasonbcox** [comment]
ABC will not be adding replay protection, as this breaks existing wallets.
