### ISSUE TITLE
bad-txns-undersize issue

### ISSUE THREAD

**Issue by enVolt** [Bitcoin-ABC/bitcoin-abc#279]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

#### If so, please list the steps to reproduce below:
1. Created an offline transaction (using bitcoincashjs
2. Submit to network
3. Getting the error

### Expected behaviour
Tell us what should happen
NA
### Actual behaviour
Tell us what happens instead
Getting Error 
```
{"result":null,"error":{"code":-26,"message":"64: bad-txns-undersize"},"id":1}
```
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA. 
Latest as on 16 Nov via PPA

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

I'm getting following error - 
```
{"result":null,"error":{"code":-26,"message":"64: bad-txns-undersize"},"id":1}
```
And I couldn't find any info about it. Looking at the source code, I can only figure out that it is related to something being undersized, but don't know exactly what that is.

Here is the raw transaction - 
`0100000001567064f8be447f51510dd516a60303cebfc5ba03c31f6503f95c7d9fdbdda1a30000000000ffffffff018e9598000000000017a914305c00bdadbd8a9186c98fe665d92efabfe356018700000000`

Let me know if I need to add anything else.

Thanks

**Comment by markblundeberg** [comment]
This is trying to spend output #0 from testnet transaction https://tbch.blockdozer.com/tx/a3a1dddb9f7d5cf903651fc303bac5bfce0303a616d50d51517f44bef8647056 , which is a P2SH address. It looks like you forgot to fill in the scriptSig however, so the transaction ended up extremely small.

Right now [Bitcoin rules have been changed to refuse transactions smaller than 100 bytes](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2018-nov-upgrade.md). If you're still stuck with a small transaction, try adding another output (like OP_RETURN with some random message) to bump it above the 100 byte limit.

**Comment by jasonbcox** [comment]
Please reopen if the above does not fix your issue.
