### ISSUE TITLE
Add replay protection

### ISSUE THREAD

**Issue by gmaxwell** [Bitcoin-ABC/bitcoin-abc#28]
ABC claims to have replay protection but it seems to go out of its way to not have replay protection. E.g. it changes to use the segwit sighash scheme but then needs extra code to support bitcoin sighashing.

You could have very strong replay protection with roughly a single line code change: simply require all transactions after the point where you fork off bitcoin to have a negative version number.  If you don't have the resources to implement this-- or something like it-- right now, I'm sure I can talk someone into doing it for you.

A failure to do this will cause severe monetary losses in the event that this new asset you're issuing becomes worth anything and these losses are avoidable with the most minimal of considerations on your part.

**Comment by NiKiZe** [comment]
Normally it is good practice to check for already open issues (#24) before creating new ones and create duplicates.
