### ISSUE TITLE
node can not synchronize

### ISSUE THREAD

**Issue by bixf** [Bitcoin-ABC/bitcoin-abc#281]
when use getblockcount to get height of the chain,it stop at 556766. at first,my program is 0.17.2. then i upgraded to 0.18.4 and 0.18.5.nothing changed.so is there something i need to configure to make things right?

**Comment by CarilKing** [comment]
me too

**Comment by c0deright** [comment]
556766 was the last block before the fork.

0.18.4 contains a checkpoint for block 556767 (first block that caused the BCH/BSV split) so your client should know the right hash for block 556767.

Please share some lines from your debug.log

**Comment by c0deright** [comment]
@bixf @CarilKing 

Please let us know whether my outlined approach was successfull or not. Others might find that information useful.

**Comment by downpouring** [comment]
yes, it does. like a charm
block height: 582680 

bitcoin-cli reconsiderblock 000000000000000001b4b8e36aec7d4f9671a47872cb9a74dc16ca398c7dcc18

appreciates
