### ISSUE TITLE
help: BCH sent to BTC sw address How to get back?

### ISSUE THREAD

**Issue by linuxMengfan** [Bitcoin-ABC/bitcoin-abc#291]
BCH sent to BTC sw address How to get back?

**Comment by Laraoj** [comment]
This happened to me once, thank goodness for a recovery expert that I met from one of the forums here who was able to help me recover my funds, you can reach out to him on cheng66@protonmail.ch for him to help you out with this issue you've got, he's going to be more than willing to help you out.

**Comment by jasonbcox** [comment]
Deleted the last comment because it looked like spam.  You'll need to contact a miner that provides recovery service.
