### ISSUE TITLE
watch-only address not recognized while in mempool, only visible after included in block. worked with 0.18.2

### ISSUE THREAD

**Issue by c0deright** [Bitcoin-ABC/bitcoin-abc#292]
### Describe the issue

We have a bitcoin ABC daemon running with txindex=1 for a long time, let's call that node monitoring node. In the past several addresses were added to it's wallet.dat as watch-only addresses, let's call these monitoring addresses.

### Expected behaviour with 0.18.2

With 0.18.2 as soon as a third party broadcasted a TX to the network transferring coins to one of these monitoring addresses and the TX entering the mempool of our monitoring node the TX could successfully be queried with RPC call `gettransaction` from that monitoring node. This is expected behaviour.

### Actual behaviour with 0.18.5

After upgrading that monitoring node from 0.18.2 to 0.18.5 some TX affecting watch-only addresses can be queried via `gettransaction` like explained above while still being in the mempool and not added to a block yet (and of course when added to a block, too). But some TX when queried via `gettransaction` just return "Invalid or non-wallet transaction id" while not being included in a block yet. Only after that TX was included in a block the RPC call will return infos about that TX.

Any ideas what might cause this?

**Comment by mohammadpourzaker** [comment]
برای استفاده از ورودی لینک BTC  استفاده کنم همه در تماشا گیر کردن و نمیتونم نه انتقال به کیف بدم نه لینکBTC 1Bf9sZvBHPFGVPX71WX2njhd1NXKv5y7v5                                                                           این هم لینک کیف دیگه من هست که هر دوتاش واقعا حالت تماشا دراومده.                                               3MseH3Rik4GyoDnhD4HdfGTu97mGaT6BKp

**Comment by jasonbcox** [comment]
This issue is stale. Please try the latest version of ABC.
