### ISSUE TITLE
bchabc sent to btc address 

### ISSUE THREAD

**Issue by blatechen** [Bitcoin-ABC/bitcoin-abc#298]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

### Describe the issue
bchabc sent to btc address 

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Actual behaviour
bchabc sent to btc address.
how can I retrieve it?

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by deadalnix** [comment]
There is a reason why there is a form. There is nothing that can be done with that report given the information enclosed.
