### ISSUE TITLE
Warning: Unknown block versions being mined! It's possible unknown rules are in effect

### ISSUE THREAD

**Issue by AdvancedStyle** [Bitcoin-ABC/bitcoin-abc#299]
Running bitcoinabc 0.18.5 I'm constantly getting warning "Warning: Unknown block versions being mined! It's possible unknown rules are in effect"

```
{
  "version": 180500,
  "protocolversion": 70015,
  "walletversion": 160300,
  "balance": 0.00000000,
  "blocks": 564227,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 213312377593.4143,
  "testnet": false,
  "keypoololdest": 1536284962,
  "keypoolsize": 2,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: Unknown block versions being mined! It's possible unknown rules are in effect"
}

```

**Comment by gsurbey** [comment]
I am getting this message as well.  I am running bitcoinabc 0.19.4
Does this have to do with some Bitcoin Cash miners running AsicBoost and the bitcoinabc code not handling that case in a graceful manner?
https://www.reddit.com/r/btc/comments/a8ejk6/warning_unknown_block_versions_being_mined_its/

**Comment by Pummelchen** [comment]
same with 0.19.4

**Comment by markblundeberg** [comment]
This warning is basically meaningless, and it has been removed as of 0.19.8.
