### ISSUE TITLE
nulldummy feature (and test) contingent on SegWit activation

### ISSUE THREAD

**Issue by ftrader** [Bitcoin-ABC/bitcoin-abc#3]
Ok, so the situation with NULLDUMMY:

> Signaling for the null dummy soft fork is done by signaling support for segwit, and the null dummy soft fork will activate at the same time as segwit.

> For more information, please see BIP147.

I do not know about a technical justification for placing this on the same bit (1) as SegWit, but if there isn't, and if this feature is able to offer benefit independent of SegWit, then I would suggest not removing it from ABC, but allocating a separate activation bit for it.

A decision will have to be reached - if it is to remove NULLDUMMY entirely, then there is some leftover C++ code that also needs to be adjusted.

**Comment by ftrader** [comment]
Adding this here because for some reason I cannot edit my post above right now. The quote in the previous comment is from https://bitcoin.org/en/release/v0.13.1 .

https://github.com/bitcoin/bips/blob/master/bip-0147.mediawiki#Deployment

**Comment by deadalnix** [comment]
Let's just blast segwit realted test cases. See https://github.com/Bitcoin-ABC/bitcoin-abc/pull/9 . Will do for now.
