### ISSUE TITLE
new "debuglogfile" in 0.18.7 can break startup from 0.18.6 when using 'printtoconsole'

### ISSUE THREAD

**Issue by jkister** [Bitcoin-ABC/bitcoin-abc#309]
on versions of bitcoinabc <=0.18.6, I could start bitcoind with:
 /home/bch/testnet/bin/bitcoind \
   -testnet \
   -printtoconsole \
   -datadir=/home/bch/.bitcoin \
   -conf=/home/bch/.bitcoin/testnet3/bitcoin.conf

bitcoind did not have write permissions to /home/bch/.bitcoin/testnet3/debug.log (et al.)

the -debuglogfile flag was introduced in 0.18.7 that requires debug.log to be writable, even when it will not be used because of the -printtoconsole flag.

> 2019-03-10T00:29:58Z Bitcoin ABC version v0.19.0.0-e619210f8
> 2019-03-10T00:29:58Z InitParameterInteraction: parameter interaction: -listen=0 -> setting -upnp=0
> 2019-03-10T00:29:58Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
> 2019-03-10T00:29:58Z Warning: Config setting for -port only applied on test network when in [test] section.
> 2019-03-10T00:29:58Z Warning: Config setting for -rpcbind only applied on test network when in [test] section.
> 2019-03-10T00:29:58Z Warning: Config setting for -rpcport only applied on test network when in [test] section.
> 2019-03-10T00:29:58Z Assuming ancestors of block 000000000000030bee568d677b6b99ee7d2d00b25d1fe95df5e73b484f00c322 have valid signatures.
> 2019-03-10T00:29:58Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000416ad051088ff75074
> 2019-03-10T00:29:58Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
> 2019-03-10T00:29:58Z Using RdRand as an additional entropy source
> 2019-03-10T00:29:58Z Error: Could not open debug log file /home/bch/.bitcoin/testnet3/debug.log
> Error: Could not open debug log file /home/bch/.bitcoin/testnet3/debug.log
> 2019-03-10T00:29:58Z Shutdown: In progress...
> 2019-03-10T00:29:58Z Shutdown: done

for compatibility during upgrade (and strict permissions), i think debug.log should be able to exist, not exist, or be writeable/not writable when printtoconsole is used.

**Comment by Fabcien** [comment]
You can use the `-nodebuglogfile` option to avoid the error.
In the end `-printtofile` and `-debuglogfile` can be two independent options, and each can be settable without impacting the other one. In this case your configuration (including `-nodebuglogfile`) will remain valid in the future versions.

**Comment by jkister** [comment]
closing, no one is upgrading from 0.18.6 any more.
