### ISSUE TITLE
node can't start rpc service

### ISSUE THREAD

**Issue by purplecity** [Bitcoin-ABC/bitcoin-abc#312]
this is the node configuration file.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/38914615/54741922-d80abb80-4bfa-11e9-8a74-2a2ae851bedb.png">

the command line is ok. but don't listen (configure file port ) 18412

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/38914615/54742022-29b34600-4bfb-11e9-9804-fcc338f719bf.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/38914615/54742058-451e5100-4bfb-11e9-9659-e496e8f51517.png">

the node version is : 0.19.1
machine: vmware fusion: centos7

**Comment by jasonbcox** [comment]
Can you provide expected behavior?  What happens when you use default settings, etc?

**Comment by jasonbcox** [comment]
#314 is the same issue. Please see the described solution I provided there.
