### ISSUE TITLE
Add deprecatedrpc=signrawtransaction information to release notes

### ISSUE THREAD

**Issue by c0deright** [Bitcoin-ABC/bitcoin-abc#316]
@jasonbcox 

Please add some information regarding `-deprecatedrpc=signrawtransaction` to 0.19.3 release notes like you did with `-deprecatedrpc=estimatefee` for 0.19.1 release.

It's not good style to let run users into the error message.

**Comment by jasonbcox** [comment]
Thanks for catching this.  The fix is up for review: https://reviews.bitcoinabc.org/D2802

**Comment by jasonbcox** [comment]
The fix has been landed on master.

**Comment by c0deright** [comment]
Sorry for being pedantic but I was talking about the text here:

https://github.com/Bitcoin-ABC/bitcoin-abc/releases/tag/v0.19.3

;-)

**Comment by jasonbcox** [comment]
It should be done in both places or not at all. :) Thanks for pointing this out.  I've fixed it on the Github release as well.
