### ISSUE TITLE
Is the order of outputs preserved when calling 'createrawtransaction'?

### ISSUE THREAD

**Issue by elvinsophus** [Bitcoin-ABC/bitcoin-abc#319]
The 'createrawtransaction' RPC interface accepts the 'outputs' parameter as a JSON object.  Is there any guarantee that the order of the items will be preserved as they are in the JSON string when the transaction is created?
If not, will there be an option to use an array as outputs in the future?
Thanks.

**Comment by elvinsophus** [comment]
I looked into the code and found that the order _is_ preserved when the items are iterated over. But that's implementation-specific therefore should not be relied upon unless there's some explicit documentation which I have not yet found.
Bitcoin Core 0.17.0 has altered the interface to accept an array as the second parameter. I think we can support that too.

**Comment by jasonbcox** [comment]
Can you link to Core's pull request that implements support for arrays? We can add it to our backlog.

**Comment by elvinsophus** [comment]
Here:
https://github.com/bitcoin/bitcoin/pull/11872

**Comment by elvinsophus** [comment]
And could you please support multiple pushes in OP_RETURN as well?

**Comment by markblundeberg** [comment]
Hey, I'm backporting this now: https://reviews.bitcoinabc.org/D3075

**Comment by jasonbcox** [comment]
The change has been landed on master.  Thanks for bringing it to our attention.
