### ISSUE TITLE
gitian-build.py does not run properly

### ISSUE THREAD

**Issue by jguthrie7** [Bitcoin-ABC/bitcoin-abc#321]
### Describe the issue
gitian-build.py does not run properly

### Expected behaviour
Script should run and create a Gitian build

### Actual behaviour
Receive the following stack trace:
```
./gitian-build.py --detach-sign --no-commit -b satoshi 0.19.4 --os=lw
Traceback (most recent call last):
  File "./gitian-build.py", line 290, in <module>
    main()
  File "./gitian-build.py", line 264, in main
    os.chdir('bitcoin')
FileNotFoundError: [Errno 2] No such file or directory: 'bitcoin'
```

**Comment by jasonbcox** [comment]
We're aware that this script doesn't work in it's current state.  It has not been maintained by us for some time.  That said, working on fixing it is in our backlog.  I'm going to close this for now since we do not have a timeline set.
