### ISSUE TITLE
v0.19.6 release

### ISSUE THREAD

**Issue by lyless** [Bitcoin-ABC/bitcoin-abc#326]
hi.  was the version v0.19.6 related 20190516 hard fork?, should i need update to this version. 
can not access this site https://reviews.bitcoinabc.org/D3054, could you please release the executable file. i m not capable for build the program.

**Comment by jasonbcox** [comment]
While the 0.19.6 release is not related to the May 15th upgrade, it does fix a critical vulnerability for miners.  You can download the binaries here: https://download.bitcoinabc.org/0.19.6/
