### ISSUE TITLE
Node reindex is too slow and memory leak maybe exist for v0.19.5

### ISSUE THREAD

**Issue by tangweijun** [Bitcoin-ABC/bitcoin-abc#328]
### Reindex data is too slow and memory keeps increase.
For update to v0.19.5, I unfortunately use command "bitcoind -reindex -daemon", then the node reindex its data and failed at the beginning because my memory is 4GB.  After know this reason, I cost 12 hrs, and then increase my memory to reindex again, after 20 hrs, it only reach the height of 458517.  
During the course, I want to know, why not reindex must begin from block 0? Since the reindex course is so so slow, why not add some checkpoints to save the status and begin from the checkpoint status(block height) to reindex? If failed, I have to reindex again from the block 0 and cost  large time, it's crazing!  
I heard once reindex , the data can't use again, it must be reindex to ensure the right. I've to continue this work. Is't right?

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. download v0.19.5 linux package in centos7 machine.
2. start "bitcoind -reindex -daemon", or "bitcoind -reindex -datadir=[Your old data dir] -daemon"
3. notice using the old data directory. Backup your data first if you test, once reindex , the data can't use again.

### Expected behaviour
1. memory is not keep increase.
2. once failed, reindex can continue from the last block height status. not 0. it 's very import to reduce the cost time. 
### Actual behaviour
1. memory keep increase, when it reach 458517, 5.2GB is used.  I suspect memory leak maybe exists.
2. if restart again, it reindex begin from block 0.  I think it's unreasonable.

### What version of bitcoin-abc are you using?
v0.19.5

### Machine specs:
- OS: linux centos 7
- CPU: Intel
- RAM: 16GB
- Disk size: 1T
- Disk Type (HD/SDD):SDD

**Comment by tangweijun** [comment]
More details: the reindex speed become slower. The beginning 38x,xxx blocks  cost about 12hr, the following speed becomes slower. It cost 8hr to reach 45x,xxx block height.

**Comment by jasonbcox** [comment]
We're aware that reindexing is slow.  At this time however, there is simply not enough manpower to work on this.  Please let us know if you are able to provide patches towards this effort.
