### ISSUE TITLE
Potentially unsafe: GUI facing error message shows string from untrusted server source

### ISSUE THREAD

**Issue by cculianu** [Bitcoin-ABC/bitcoin-abc#332]
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/dc0adb7b18f854a6b076824e4edb8b02ce62e5bd/src/qt/paymentserver.cpp#L759

I also posted this to core: https://github.com/bitcoin/bitcoin/issues/16154

In light of recent phishing attempts on eg the Electrum network, it's probably not the best idea to show this error message in the GUI.

Granted this is a corner case and the attack surface is exceedingly small -- it still probably should be handled.

Best regards,

-Calin

**Comment by jasonbcox** [comment]
Thanks.  Will track the issue from here: https://reviews.bitcoinabc.org/T666
