### ISSUE TITLE
OpenAlias support in wallet

### ISSUE THREAD

**Issue by janowitz** [Bitcoin-ABC/bitcoin-abc#334]
OpenAlias is an open standard developed in 2014-2015 which offers the possibility to match E-Mail like addresses "user@domain.tld" or subdomain like Addresses "user.domain.tld" to be matched with a corresponding Cryptocurrency address. Something similar, but less complicated and more secure than the recently published proposal "bsvalias/paymeil"

It is simply based on a TXT record for the specific subdomain, and so supports DNSSEC and DNSCrypt and anyone can extend it. For BTC at least Electrum wallet supports it, but it would be nice to see more cooperation among crypto related projects instead of more and more segmentation.

For example a TXT record for the Bitcoin ABC donation address would be simply:
`oa1:bch recipient_address=qq29gww57twmvq07las39p3m65x8nw2ngvvuq6adpn; recipient_name=BitcoinCash Development Fund;`

You'll find the specification here: https://openalias.org/

_This topic has also been raised recently on reddit (no flair): https://www.reddit.com/r/btc/comments/boxd4a/openalias_for_bitcoin_cash/_

**Comment by janowitz** [comment]
Just as an additional note, Electron Cash has already fixed their OpenAlias implementation inherited from Electrum for BTC: https://github.com/Electron-Cash/Electron-Cash/pull/1442

It would be even nicer to see it in Bitcoin ABC to be compatible!

**Comment by jasonbcox** [comment]
The wallet is primarily maintained for testing purposes at the moment. While we'd like to add new features to the wallet, it would take focus away from the building the node software.

PRs are welcome, but you may find that complex changes will be difficult to get reviewed until backports are up-to-date.  We also welcome help on that front.

Closing this for now.
