### ISSUE TITLE
Multi wallet support?

### ISSUE THREAD

**Issue by hieutvan** [Bitcoin-ABC/bitcoin-abc#335]
Does Bitcoin ABC support multi-wallet like Bitcoin Core? If not, consider this a feature request, or I will close it myself.

**Comment by jasonbcox** [comment]
yes, Bitcoin ABC supports multi-wallet functionality.

**Comment by hieutvan** [comment]
Thank you. Can you please give me some documentation on this functionality? For example I'm used to _loadwallet_ function in Core but I don't know its counterpart in ABC.

Perhaps it's not really multi-wallet, but _account_ feature?

**Comment by jasonbcox** [comment]
`loadwallet` appears to be an RPC for loading new wallets without needing to restart bitcoind.  If you simply need multi-wallet support, you can start bitcoind with multiple `-wallet=xxx` args.  We do not yet have support for `loadwallet`, but we can look into it.

**Comment by espriweb** [comment]
Hi, I apologize in advance for not being sufficiently prepared, with bitcoin core I create a new wallet using RPC using the "createwallet" command but with bitcoin abc I can't find a similar command, when I use "createwallet" it returns the error " Method not found ".

You can help me?

**Comment by jasonbcox** [comment]
We are still in the process of backporting some of Bitcoin Core's wallet RPC commands, so `createwallet` is not yet available for creating new wallets at runtime.  However, you can call `bitcoind -wallet=<path-to-current-wallet> -wallet=<path-to-new-wallet>` and the new wallet file will be created for you.

**Comment by espriweb** [comment]
Thanks for the support, but to create a new wallet I have to stop and restart the blockchain, isn't there a trick to avoid restarting the blockchain?

Another thing, but where do I find the complete list of json-rpc commands?

Thanks for your patience

> We are still in the process of backporting some of Bitcoin Core's wallet RPC commands, so `createwallet` is not yet available for creating new wallets at runtime. However, you can call `bitcoind -wallet=<path-to-current-wallet> -wallet=<path-to-new-wallet>` and the new wallet file will be created for you.

**Comment by jasonbcox** [comment]
Currently, we don't have a way to load a wallet at runtime, so even if you could create one, the software would not pick it up.  We'll be looking into this.

For a list of RPC commands, see `bitcoin-cli help`.

**Comment by espriweb** [comment]
Thank you very much, I am creating a multiwallet and I only need BCH I would like to use bitcoin-abc because yours is a nice community of developers.

Thanks and good future to all!

**Comment by espriweb** [comment]
Jason @jasonbcox  thanks for the changes in v0.20.4 version, really good and fast work, congratulations to all the staff of programmers

**Comment by jasonbcox** [comment]
Cheers @espriweb. Just note that 0.20.4 only includes `createwallet`, but `loadwallet` won't be ready likely until 0.20.5.  `createwallet` will both create and load the wallet the first time, but successive calls on the same file will not work.  In the mean time, if you need to restart bitcoind, just pass in as many `-wallet <file>` arguments as needed.

**Comment by hieutvan** [comment]
Haven't updated for a long time. Thank all of you for all the work! :tada:
