### ISSUE TITLE
decommissioning criptolayer seed nodes, please remove

### ISSUE THREAD

**Issue by molecular** [Bitcoin-ABC/bitcoin-abc#336]
I'm decommissioning my seed nodes

 * seeder.criptolayer.net
 * testnet-seeder.criptolayer.net

Because I fail to keep the crawlers running and hence the lists fresh, I feel they are doing more harm than good.

Can someone please remove them from src/seeder/main.cpp and src/chainparams.cpp?

**Comment by jasonbcox** [comment]
https://reviews.bitcoinabc.org/D3639

**Comment by jasonbcox** [comment]
The change has been landed on master.  Sorry to see you go, and thanks for supporting the Bitcoin Cash network.

**Comment by molecular** [comment]
*I* am not going anywhere ;-). Just too low on time due to private circumstances to keep this stuff up and running healthily. Makes me a bit sad, it was pretty cool to have my server hardcoded in abc ;-)

Thanks for making the change.
