### ISSUE TITLE
Home-brew installation of dependencies fails

### ISSUE THREAD

**Issue by dzwiener** [Bitcoin-ABC/bitcoin-abc#338]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please contact people privately.

#### If so, please list the steps to reproduce below:
1. I followed the steps in doc/build-osx.md
2. Got to brew install ...
3. When I run the command Brew says that: Error: invalid option: --c++11

### Expected behaviour
Tell us what should happen
Home-brew should install all the required dependencies

### Actual behaviour
Tell us what happens instead
Home-brew does not recognize the options provided. I am not familiar with what that option should invoke either.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
Official
Self compiled
commit f8cbc0e2b439aa4030430a7b1ecbdafede0dd072

### Machine specs:
- OS: MacOS 10.14.6
- CPU: Intel Core i7
- RAM: 16 GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
Version: Homebrew 2.1.8
xcode-select --install had already been run as well

**Comment by jasonbcox** [comment]
This may fix the issue. https://reviews.bitcoinabc.org/D3908

**Comment by dzwiener** [comment]
I am following the readme file in docs/build-osx.md and when I run "make check" it fails with an error. I initially assumed it was due to my dependencies considering that I had run the brew line and received an error. But if there is no issue with my dependencies, should I post the error here or create a new issue?

**Comment by Fabcien** [comment]
Did you run the brew dependencies installation successfully before running `make check` ?
  - If yes, then you should open another issue as it might be unrelated and this one can be closed;
  - If no, then you should try again by following the documentation from the latest master. If you still encounter issues installing the dependencies please post the error output here.

The `make check` command will fail if the dependencies are not installed first.

**Comment by dzwiener** [comment]
I ran the command the link provided before I got this response, I assumed there was something different that the option --c++11 added that I wasn't able to find in the documents.

When I run 'brew install automake berkeley-db libtool boost miniupnpc openssl pkg-config protobuf qt5 libevent librsvg'

I receive:

`Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
Warning: berkeley-db 18.1.32 is already installed and up-to-date
To reinstall 18.1.32, run `brew reinstall berkeley-db`
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
Warning: boost 1.70.0 is already installed and up-to-date
To reinstall 1.70.0, run `brew reinstall boost`
Warning: miniupnpc 2.1 is already installed and up-to-date
To reinstall 2.1, run `brew reinstall miniupnpc`
Warning: openssl 1.0.2s is already installed and up-to-date
To reinstall 1.0.2s, run `brew reinstall openssl`
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: protobuf 3.7.1 is already installed and up-to-date
To reinstall 3.7.1, run `brew reinstall protobuf`
Warning: qt 5.13.0 is already installed and up-to-date
To reinstall 5.13.0, run `brew reinstall qt`
Warning: libevent 2.1.11 is already installed and up-to-date
To reinstall 2.1.11, run `brew reinstall libevent`
Warning: librsvg 2.44.14_1 is already installed and up-to-date
To reinstall 2.44.14_1, run `brew reinstall librsvg``

**Comment by Fabcien** [comment]
The dependencies are almost all installed, you are still missing some. Please run the complete command line from the latest documentation (https://reviews.bitcoinabc.org/source/bitcoin-abc/browse/master/doc/build-osx.md) which is:
`brew install automake berkeley-db libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode`

You will get the same warnings as before, which is normal. If the installation is successful as it should be, you can continue with the next instructions up to `make check`. Please file in another issue if you still get errors from `make check`.

**Comment by dzwiener** [comment]
I have opened up a new issue #340
