### ISSUE TITLE
Please do a github release of 0.19.11

### ISSUE THREAD

**Issue by c0deright** [Bitcoin-ABC/bitcoin-abc#339]
https://github.com/Bitcoin-ABC/bitcoin-abc/releases/latest redirects to https://github.com/Bitcoin-ABC/bitcoin-abc/releases/tag/v0.19.10 but https://download.bitcoinabc.org/ has 0.19.11.

Please do a proper 0.19.11 release on github.

**Comment by jasonbcox** [comment]
Forgot to hit publish ;)
