### ISSUE TITLE
network unreachable

### ISSUE THREAD

**Issue by carryon** [Bitcoin-ABC/bitcoin-abc#342]
version: bitcoin-abc-0.19.11
OS: centos 7

![image](https://user-images.githubusercontent.com/2255313/64008827-6a6b9f80-cb49-11e9-9c75-30735ccee423.png)

![image](https://user-images.githubusercontent.com/2255313/64008956-9850e400-cb49-11e9-9f6c-9c88dede6450.png)

![image](https://user-images.githubusercontent.com/2255313/64009025-b0286800-cb49-11e9-9d8b-a9286d4e136a.png)

![image](https://user-images.githubusercontent.com/2255313/64009049-bddded80-cb49-11e9-8129-ecef1213bf53.png)

this picture was head of latest 1000 lines log:
![image](https://user-images.githubusercontent.com/2255313/64009428-6a1fd400-cb4a-11e9-8682-85e5e94d2155.png)

why it was happening? @jasonbcox

**Comment by carryon** [comment]
start command:
./bitcoind -datadir=/v1/apps/bch/bitcoin-abc-0.19.11/bin/data -txindex=1 -dbcache=1000 -rpcuser=yourrpcuser -rpcpassword=yourrpcpass -server=1 -daemon

**Comment by carryon** [comment]
![image](https://user-images.githubusercontent.com/2255313/64011238-dea84200-cb4d-11e9-865c-6d0b7b9cefa1.png)

**Comment by carryon** [comment]
after a restart, it was the same error, logs were bellow.

![image](https://user-images.githubusercontent.com/2255313/64011365-1f07c000-cb4e-11e9-9e23-93c935b48d05.png)

**Comment by carryon** [comment]
@markblundeberg @jasonbcox  Would you help us to solve this bug?

**Comment by SalleryWang** [comment]
hello body,i can't sync after the 582680 block,like: ERROR: AcceptBlockHeader: block 000000000000000001b4b8e36aec7d4f9671a47872cb9a74dc16ca398c7dcc18 is marked invalid
i tried  invalidateblock and reconsiderblock,but it doesn't work.  i'm on the 0.20.0

**Comment by carryon** [comment]
solved, https://github.com/bitcoin/bitcoin/issues/8491

**Comment by carryon** [comment]
@SalleryWang restart maybe help
