### ISSUE TITLE
Multi wallet adn json-rpc

### ISSUE THREAD

**Issue by espriweb** [Bitcoin-ABC/bitcoin-abc#349]
Thanks for the support, but to create a new wallet I have to stop and restart the blockchain, isn't there a trick to avoid restarting the blockchain?

Another thing, but where do I find the complete list of json-rpc commands?

Thanks for yours patience

> We are still in the process of backporting some of Bitcoin Core's wallet RPC commands, so `createwallet` is not yet available for creating new wallets at runtime. However, you can call `bitcoind -wallet=<path-to-current-wallet> -wallet=<path-to-new-wallet>` and the new wallet file will be created for you.

_Originally posted by @espriweb in https://github.com/Bitcoin-ABC/bitcoin-abc/issues/335#issuecomment-536201182_

**Comment by jasonbcox** [comment]
https://github.com/Bitcoin-ABC/bitcoin-abc/issues/335#issuecomment-541257753 should answer your first question. You can do `bitcoin-cli help` for a list of RPC commands.
