### ISSUE TITLE
No checksum for Linux (v0.20.4)

### ISSUE THREAD

**Issue by g574** [Bitcoin-ABC/bitcoin-abc#352]
v0.20.4 [Checksum file](https://download.bitcoinabc.org/0.20.4/jasonbcox-sha256sums.0.20.4.asc) does not contain [Linux packages](https://download.bitcoinabc.org/0.20.4/linux/)
### Expected behaviour
The checksum file should list the linux packages, e.g. in the previous release, v0.20.3, "bitcoin-abc-0.20.3-x86_64-linux-gnu.tar.gz" was there in https://download.bitcoinabc.org/0.20.3/jasonbcox-sha256sums.0.20.3.asc

### Actual behaviour
Linux packages are not listed in the checksum file.

### What version of bitcoin-abc are you using?
0.20.4

**Comment by gracenoah** [comment]
Until this is resolved, we have to assume that @jasonbcox has been kidnapped and the linux binary has been backdoored, so we can't upgrade.

**Comment by jasonbcox** [comment]
Sorry about this guys, I copied the wrong hashes when I signed. I'll provide some new sigs ASAP.

**Comment by jasonbcox** [comment]
I've updated my sigs:
http://jasonbcox.com/bitcoin-abc/SHA256SUMS.0.20.4.asc
This should contain all of the signed linux hashes.

I'll get the download.bitcoinabc.org hashes fixed soon as well.

**Comment by g574** [comment]
Hi @jasonbcox, I see the file on bitcoinabc.org hasn't been updated yet. Is there any ETA when it will happen? Many thanks.

**Comment by jasonbcox** [comment]
Got it fixed today as part of a migration we've been planning for a while. Cheers.
