### ISSUE TITLE
API listtransactions deprecation issues

### ISSUE THREAD

**Issue by Saicere** [Bitcoin-ABC/bitcoin-abc#354]
This issue was previously pointed out and addressed in [Bitcoin Core Issue #14382](https://github.com/bitcoin/bitcoin/issues/14382). As such, I'll just be copy/pasting a slightly modified post from there. I did a cursory check to see if ABC addressed this issue in a different way without finding one, but please point it out if I missed anything.

While most of the additional functionality the old account system had over the label system were irrelevant, there is one critical functionality that no longer seems to be possible with labels - specifically, the ability to request a list of transactions (TXID + amount) that pay to addresses with a given account/label. As per the [release notes for 0.20](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes.md) the _listtransaction_ method was changed as follows;

> The account named parameter has been renamed to dummy. If provided, the dummy parameter must be set to the string *, unless running with the -deprecatedrpc=accounts argument (in which case functionality is unchanged).

_getreceivedbylabel_ and _getreceivedbyaddress_ only returns the balance, while _listreceivedbylabel_ and _listreceivedbyaddress_ do not actually filter; additionally, the former does not list transactions at all, while the latter does not include the amounts per TXID. While you could use _getaddressesbylabel_ to iterate over addresses, there is no corresponding method to get the TXIDs and amounts from this list of addresses. None of these can therefore be used as a direct replacement for this method.

The only way I can see to get anything resembling the old functionality with the API changes is to dump the entire transaction history with _listreceivedbyaddress_, filter the result by label manually, then use _gettransaction_ on each listed TXID. This is both very fiddly and very inefficient, and likely impossible when you go past a certain number of lifetime transactions.

Unlike Core, running an old version of ABC past the next hard fork is obviously not possible, so hopefully the fix in Core can be merged or the deprecation can be reverted.

**Comment by jasonbcox** [comment]
Hey @Saicere thanks for bringing this to our attention.  In the mean time while we look into backporting this fix, have you tried running with `-deprecatedrpc=accounts` as the help text describes?  If that doesn't fix the issue temporarily, you can run any version 0.20.0 - 0.20.5 and still be prepared for the upgrade tomorrow with the old listtransactions behavior (the release notes you linked is specifically for 0.20.6).  Please let me know if the deprecatedrpc argument doesn't resolve the issue for you, as I'd like to add that our investigation.

**Comment by Saicere** [comment]
I forgot to mention that, but I do run 0.20.6 with deprecatedrpc=accounts set, and that does restore the old functionality.

**Comment by jasonbcox** [comment]
Thanks.  It's on our radar to get fixed before then.

**Comment by Saicere** [comment]
Just curious what the status is on this? Looking at 0.21.1, the argument is still marked as deprecated, but `deprecatedrpc=accounts` still seems to work even though `help listtransactions` still states it will be removed in V0.21.

**Comment by Saicere** [comment]
So with 0.21.2, the workaround was removed. `listtransactions` can no longer list transactions filtered by label/account, and there are no remaining functions that fulfill this functionality. Are there still any plans to fix this?

**Comment by jasonbcox** [comment]
Sorry, this fell off our plate. We're working on getting it in the next release: https://reviews.bitcoinabc.org/D5507 I'll be sure to update when the fix is available.

**Comment by jasonbcox** [comment]
If you would like to build from source to test, the fix is now available on master.  It should go out with the 0.21.3 release on March 31st.

**Comment by Saicere** [comment]
Thanks for the fix. I don't have a working build environment for this at the moment, but I'll test it out as soon as 0.21.3 is released.

**Comment by jasonbcox** [comment]
0.21.3 has been released: https://download.bitcoinabc.org/0.21.3/ Please try it out and let us know if the fix is working as you expect.

**Comment by Saicere** [comment]
Unfortunately 0.21.3 is not runnable on my systems as it requires glibc 2.18, while CentOS 7 (EOL 2024) only has glibc 2.17 which cannot be updated. For the record, Core will require glibc 2.17 in 0.20.0 specifically because of this (see [#17538](https://github.com/bitcoin/bitcoin/pull/17538); I believe they were briefly targeting 2.18 as well. Should I open a separate issue for this?

**Comment by jasonbcox** [comment]
Yes, please open a separate issue. I have some questions about the glibc issue.  If you'd prefer, we can also chat on the ABC dev Telegram channel: https://t.me/joinchat/HCYr50mxRWjA2uLqii-psw

Closing this issue since it is resolved.
