### ISSUE TITLE
Fontconfig 2.12.6 is broken - Static Dependency compile files 

### ISSUE THREAD

**Issue by KeyFiDennis** [Bitcoin-ABC/bitcoin-abc#356]
# Describe the issue

Static Dependency compile files 
```
/bitcoin-abc-0.20.6/depends/work/build/x86_64-linux-gnu/fontconfig/2.12.6-f99e4be604c/missing: line 81: gperf: command not found
WARNING: 'gperf' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing 'gperf' program.
Makefile:916: recipe for target 'fcobjshash.h' failed
```
### Can you reliably reproduce the issue?
``` 
cd depends
make -j4 HOST=x86_64-linux-gnu
```

### Expected behaviour
All dependencies should build without error

### Actual behaviour
Font config throws an error

### What version of bitcoin-abc are you using?
Latest source code `bitcoin-abc-0.20.6` from release page

### Machine specs:
- OS: Ubuntu (clean)

### Any extra information that might be useful in the debugging process.
https://gitlab.kitware.com/paraview/paraview/issues/17845

Update to newest release or downgrade below. https://github.com/freedesktop/fontconfig/releases
Transient dependency to freetype needs a look then too.

**Comment by Fabcien** [comment]
You need to install some dependencies on your machine to successfully run the static build, and `gperf` is one of these.
Look at https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/contrib/gitian-descriptors/gitian-linux.yml and install everything from the `packages` list first. The package names may be slightly different as they are targeting Debian and not Ubuntu.
