### ISSUE TITLE
Has bitcoin-abc a testnet?

### ISSUE THREAD

**Issue by SwimmingTiger** [Bitcoin-ABC/bitcoin-abc#36]
I need a testnet for bitcoin-abc or Bitcoin Cash (with big block activated). So I can test my software if it works with the >1M blocks.

Has bitcoin-abc or Bitcoin Cash a testnet? And how can my node join it?

**Comment by ftrader** [comment]
We do testing on testnet. Please contact me via email at freetrader@tuta.io .

**Comment by YihaoPeng** [comment]
Ok. I have joined the slack team as username "SwimmingTiger".

**Comment by SwimmingTiger** [comment]
Ok. I have joined the slack team and my username is "SwimmingTiger" too.

**Comment by smno1** [comment]
Is there any place I can get bcc testnet faucet?

**Comment by ftrader** [comment]
@smno1 : there is something apparently working on a faucet, but I'm not sure how long until it's finished.
Please join us on BTCfork slack if you can, to get assistance with testnet coins in the meantime.

**Comment by deadalnix** [comment]
Launching ABC with the testnet flag will end up on testnet.

**Comment by Polve** [comment]
Has the testnet forked from (bitcoin legacy) testnet3 too?
In this case, may I know at which block number?
I need this to develop the code to split accounts.

**Comment by ftrader** [comment]
@Polve : yes, testnet3 also forked according to the UAHF rule changes.

The last common block is 1155875 , the fork block is 1155876 .

https://www.blocktrail.com/tBCC/block/00000000000e38fef93ed9582a7df43815d5c2ba9fd37ef70c9a0ea4a285b8f5

**Comment by knoxcard** [comment]
BCC Testnet Faucet: https://testnet.manu.backend.hamburg/bitcoin-cash-faucet

**Comment by AlexanderMazaletskiy** [comment]
Hi, guys! https://testnet.manu.backend.hamburg/bitcoin-cash-faucet doesnt work. Can you send me some test coins BCH to mkjtJ6PLTYzfG2RYpp6UoMaczdVy1SV48b?

**Comment by knoxcard** [comment]
I need BCH testnet coins as well now, testnet.manu.... stopped working!
Please sen to: mvU1PaRm9RgKzBCaeFdGVNhcDNNf69odmx

**Comment by PM-kate** [comment]
I also need some test coins for testing. Can anybody help me? here is my test Bitcoin Cash address : qpl32d2ymguy0c9yyegymp7tcn0y5ruawc4akplsmn

**Comment by knoxcard** [comment]
I gave up asking for testnet coin and ended just running the live net bitcoin cash chain in my dev environment and bought a $100 of BCH. Ridiculous. lol

**Comment by Polve** [comment]
The service unfortunately does not accept bech32 cash addresses: use old ones, it should work fine.

**Comment by YihaoPeng** [comment]
@dovancao running a `bitcoin-qt` or `bitcoind` with `--testnet`, then call RPC `getnewaddress`.
