### ISSUE TITLE
getbalance RPC command does not accept account-related arguments even though they have not yet been removed in v0.20.7

### ISSUE THREAD

**Issue by alex-georgiou** [Bitcoin-ABC/bitcoin-abc#360]
# Describe the issue

I have built bitcoin-abc from tag `v0.20.7` (commitish `ee9ec9700`). When I issue the command

    ./bitcoin-cli getbalance "*" 6

I get back the help screen for the `getbalance` command. However, the help screen clearly states that this command should be accepted in versions prior to V0.21 (where the deprecated account feature is going to be removed).

    The total amount in the wallet at least 6 blocks confirmed
    > bitcoin-cli getbalance "*" 6

#### If so, please list the steps to reproduce below:
1. Build from tag `v0.20.7`
2. Run the daemon
3. Run the command `bitcoin-cli getbalance "*" 6`

### Expected behaviour
The command should return the wallet balance for all wallet keys regardless of whether they are assigned to accounts or not.

In addition, even after the deprecated feature will be removed in version V0.21, the command should still be accepted, to maintain backwards compatibility of the RPC API. This is the behavior of Bitcoin core, where the feature has now been completely removed.

### Actual behaviour
The help screen for the `getbalance` command is returned.

### What version of bitcoin-abc are you using?
Built from tag `v0.20.7` (`ee9ec9700`)

**Comment by jasonbcox** [comment]
Thanks for bringing this to our attention. I've backported the related fix and it will be going out with our next release: https://reviews.bitcoinabc.org/D4639

**Comment by alex-georgiou** [comment]
Thank you!
