### ISSUE TITLE
Error compiling master branch on test_bitcoin_main.cpp

### ISSUE THREAD

**Issue by e-scavo** [Bitcoin-ABC/bitcoin-abc#362]
Hello:
We are trying to compile from sources but an error has occurred compiling tests_bitcoin_main.cpp

I googled and I couldn't find how to solve it.
We are running Ubuntu 18.04 LTS and compilation are made with depends as prefix.

```
usuario@ubuntu:~/crypto/bitcoin-abc$ make
Making all in src
make[1]: se entra en el directorio '/home/usuario/crypto/bitcoin-abc/src'
make[2]: se entra en el directorio '/home/usuario/crypto/bitcoin-abc/src'
make[3]: se entra en el directorio '/home/usuario/crypto/bitcoin-abc'
make[3]: se sale del directorio '/home/usuario/crypto/bitcoin-abc'
  CXX      test/test_test_bitcoin-test_bitcoin_main.o
test/test_bitcoin_main.cpp: In function ‘int main(int, char**)’:
test/test_bitcoin_main.cpp:46:46: error: ‘init_unit_test’ was not declared in this scope
     return boost::unit_test::unit_test_main(&init_unit_test, argc, argv);
                                              ^~~~~~~~~~~~~~
test/test_bitcoin_main.cpp:46:46: note: suggested alternative: ‘init_unit_test_suite’
     return boost::unit_test::unit_test_main(&init_unit_test, argc, argv);
                                              ^~~~~~~~~~~~~~
                                              init_unit_test_suite
Makefile:9905: recipe for target 'test/test_test_bitcoin-test_bitcoin_main.o' failed
make[2]: *** [test/test_test_bitcoin-test_bitcoin_main.o] Error 1
make[2]: se sale del directorio '/home/usuario/crypto/bitcoin-abc/src'
Makefile:11514: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio '/home/usuario/crypto/bitcoin-abc/src'
Makefile:765: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
usuario@ubuntu:~/crypto/bitcoin-abc$
```

**Comment by jasonbcox** [comment]
What version of boost are you using?
`less /usr/include/boost/version.hpp | grep "#define BOOST_LIB_VERSION"`

**Comment by e-scavo** [comment]
> What version of boost are you using?
> `less /usr/include/boost/version.hpp | grep "#define BOOST_LIB_VERSION"`

#define BOOST_LIB_VERSION "1_64"

Boost are compiled from depends (as well as any other dependency requirements).

Thanks for your reply

**Comment by gituser** [comment]
I'm having same issue on the latest tagged release `v0.20.8`, please fix this ASAP.

**Comment by jasonbcox** [comment]
I'm still digging at this issue and have not been able to reproduce it myself.  In the mean time, can you both provide more details?
```
lsb_release -a
make --version
gcc --version
less /usr/include/boost/version.hpp | grep "#define BOOST_LIB_VERSION"
```
Please try building against latest master as well.

I also invite you to try the new CMake build instead of autotools.  Latest master has the new build instructions.

Failing those, try building with clang instead of gcc and see if that provides any additional info:
`./configure CC=clang CXX=clang++`

**Comment by Fabcien** [comment]
Can you please provide your configure command line ? For which platform are you trying to build ?

**Comment by gituser** [comment]
@jasonbcox 

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

>less /usr/include/boost/version.hpp | grep "#define BOOST_LIB_VERSION"

There is no system boost installed boost is used defined in the depends.

**Comment by gituser** [comment]
> Can you please provide your configure command line ? For which platform are you trying to build ?

```
#build dependencies (bitcoinabc specific)
CC=/usr/bin/gcc CXX=/usr/bin/g++ make -j4 -C depends HOST=x86_64-linux-gnu NO_ZMQ=1 NO_QT=1 NO_UPNP=1

DEPENDS="$(pwd)/depends/x86_64-linux-gnu"
./autogen.sh
./configure CC=/usr/bin/gcc CXX=/usr/bin/g++ --without-gui --enable-cxx --with-incompatible-bdb --disable-zmq --without-seeder --without-miniupnpc --prefix=$DEPENDS
```

**Comment by Fabcien** [comment]
I confirm the bug.
Until this is fixed, you can still build the latest version without the seeder and the unit tests suite:
`./configure --prefix=${DEPENDS} [...] --without-seeder --disable-tests`

**Comment by Fabcien** [comment]
This is fixed on current master and should be part of the next release.

**Comment by gituser** [comment]
@Fabcien thank you. Will be waiting for the new release.

**Comment by jasonbcox** [comment]
Closing this issue now that it's resolved. If you encounter similar issues on the latest master, feel free to reopen.
