### ISSUE TITLE
getblocktemplate doesn't return 'vbavailable' and 'vbrequired' fields for BIP9 voting

### ISSUE THREAD

**Issue by sha256d** [Bitcoin-ABC/bitcoin-abc#368]
Pool server software uses the 'vbavailable' field to vote on BIP9 deployments, which is not present on bitcoin-abc 0.21. Also unless the deployment is in the LOCKED_IN or ACTIVE state, the 'version' field should not signal for any deployment.

For instance, when segwit was being voted on on bitcoin 0.14, the nVersion returned by getblocktemplate DID NOT signal for segwit by default: the nVersion bit was being cleared [here](https://github.com/bitcoin/bitcoin/blob/43a987c1cbcd04b9c59052606c3c31c56abc826e/src/rpc/mining.cpp#L630) because segwit had [gbt_force=false](https://github.com/bitcoin/bitcoin/blob/43a987c1cbcd04b9c59052606c3c31c56abc826e/src/versionbits.cpp#L20). Mining pools that decided to cast a vote for segwit had to either (1) read the 'vbavailable' field and set the corresponding bit or (2) call getblocktemplate with 'rules':['segwit']. Segwit was clearly opt-in.

Please note that pool server sw respects most bits from the 'version' field from getblocktemplate and NEVER clears any bit. This is important to avoid wasting work on invalid block templates. The conclusion here is that all deployments being voted on are neither opt-in nor opt-out, they are just being force activated. I believe this was not the intention with this release. It seems commit 02de5cf34 missed some critical BIP9 code in the getblocktemplate rpc call.

As a side note, mining asics too are never allowed to clear any nVersion bit. Stratum recent [version rolling extension](https://github.com/slushpool/stratumprotocol/blob/master/stratum-extensions.mediawiki) (aka asicboost) allows a mining asic to set bits in a given bitfield, but never clear them. ckpool's version_mask, for instance, defaults to "1fffe000".

Thanks in advance for looking into this.

**Comment by jasonbcox** [comment]
Do you mind elaborating on which pool software you're referring to? It's not clear to me why vbrequired (always set to 0 in Bitcoin Core) or vbavailable are necessary.

The nVersion issue has since been fixed in 0.21.1

**Comment by jasonbcox** [comment]
Closing since this issue is old and there appears to be nothing further to investigate.
