### ISSUE TITLE
I just sent my Bitcoins to a Bitcoin Cash wallet.Did i lost my coins?

### ISSUE THREAD

**Issue by Cryptobird01** [Bitcoin-ABC/bitcoin-abc#37]
I just sent my Bitcoins to a Bitcoin Cash wallet by mistake, did i lost my coins? or will they be converted to Bitcoin Cash coins after August the first ? Thanks

**Comment by ftrader** [comment]
What wallet did you send them to?

**Comment by mpatc** [comment]
Do you have a transaction hash?

**Comment by Cryptobird01** [comment]
Thanks guys :+1: , i just figure out that Bitcoin ABC generates a **compressed** public key . Now every think is working fine . [ I'm hyped for Aug 1st :-) ]
