### ISSUE TITLE
after './configure' script removed, please return/document how to set those configuration options

### ISSUE THREAD

**Issue by dchmelik** [Bitcoin-ABC/bitcoin-abc#370]
### Describe the issue
Can no longer use './configure' script when compiling.

#### If so, please list the steps to reproduce below:
1. Start to compile bitcoin-abc (as in doc/build-unix.md with either all dependencies, or appropriate exclusion arguments/flags/switches)
2. Don't have './configure' script anymore.
3. Can't set suffix to avoid installation overwriting BTC bitcoin-qt BCH forked from, and many other options people wanted (hope similarly wallet directory in src/util/system.cpp also changed; don't want to be overwriting people's original BTC wallets...)

### Expected behaviour
Tell us what should happen

Let you use all past './configure' options people want and document all.

### Actual behaviour
Tell us what happens instead

Apparently no './configure' options unless replaced with zero way for people to know/read documentation.

### What version of bitcoin-abc are you using?
0.20.9 or everything newer that has the new build process (okay, well stuck on 0.20.8 for now but want to upgrade.)

**Comment by jasonbcox** [comment]
It's not at all clear what is broken here. The autotools build is certainly usable and no features have been stripped out.

That said, the autotools build is deprecated.  I highly recommend moving to cmake.

I'm closing this issue because there's no actionable information to go on.
