### ISSUE TITLE
rpcRunLater race in walletpassphrase

### ISSUE THREAD

**Issue by kryvel** [Bitcoin-ABC/bitcoin-abc#375]
Hi,
I encountered with deadlock on concurrent walletpassphrase rpc call in bitcoin wallet. The same behavior in bitcoin-abc too.
Here is a description of the issue https://github.com/bitcoin/bitcoin/issues/18482

Could you please backport the fix to bitcoin-abc ?

**Comment by jasonbcox** [comment]
Thanks for bringing this to our attention. We'll keep tabs on the that developing issue and it's associated fix.

**Comment by kryvel** [comment]
I could confirm, that test case, provided in #18482, shows that issue is present in bitcoin-abc latest version, and the suggested fix is working. After compiling with fixed rpcwallet.cpp issue is gone.

**Comment by kryvel** [comment]
HI, @jasonbcox 
Any update on this? Is it planned to include it to the next release ?

**Comment by jasonbcox** [comment]
The change has landed on master. If you want to test it before the 0.22.5 release, can you try latest master and confirm the fix?
