### ISSUE TITLE
./bitcoin-cli importwallet does not work

### ISSUE THREAD

**Issue by livingrock7** [Bitcoin-ABC/bitcoin-abc#377]
This issue tracker is only for technical issues related to bitcoin-abc.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see [DISCLOSURE_POLICY](DISCLOSURE_POLICY.md).

### Describe the issue

I am trying to import backed up wallet.dat file into other node. Can anyone guide me through whole process please?

#### If so, please list the steps to reproduce below:
1. Installed 0.17.2 
2. Took backup of existing wallet by backupwallet and imported new wallet.dat file using importwallet
3. Restarted the service. Logs indicate update the version of Bitcoin-ABC and shuts down

I am not sure which version to use. When I tried 0.21.x version my service always fails to start

### Expected behaviour
Tell us what should happen

Should import the wallet and showaccounts for ""

### Actual behaviour
Tell us what happens instead

shutdown

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

https://download.bitcoinabc.org/0.17.2/

**Comment by livingrock7** [comment]
`2020-04-08T10:06:40Z Loaded best chain: hashBestChain=000000000000000001e80364b1cece853041582307a7f99645f23650b32157df height=609161 date=2019-11-18T17:03:27Z progress=0.877706
2020-04-08T10:06:40Z init message: Rewinding blocks...
2020-04-08T10:06:42Z init message: Verifying blocks...
2020-04-08T10:06:42Z Verifying last 6 blocks at level 3
2020-04-08T10:06:42Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2020-04-08T10:06:42Z No coin database inconsistencies in last 7 blocks (7 transactions)
2020-04-08T10:06:42Z  block index            6490ms
2020-04-08T10:06:42Z init message: Loading wallet...
2020-04-08T10:06:42Z Error: Error loading wallet.dat: Wallet requires newer version of Bitcoin ABC
2020-04-08T10:06:42Z Shutdown: In progress...
2020-04-08T10:06:42Z scheduler thread interrupt
2020-04-08T10:06:42Z Shutdown: done
2020-04-08T10:06:43Z
`

**Comment by jasonbcox** [comment]
From the error message, it sounds like you're trying to export a wallet from 0.21.x and import it into 0.17.2.  This will not work because newer wallet formats are incompatible with older versions of the software.

**Comment by livingrock7** [comment]
Is there a way to update the version from 0.17.2 to 0.21.x on the node where I am importing? Without having to reindex again keeping all block information in data directory

**Comment by livingrock7** [comment]
@jasonbcox I was able to check node I am migrating from has 0.15.2 version and on the new node I have used 0.19.x (which version is recommended? as it is still getting stuck at block 609161) 

What would you suggest for wallet import after sync is resolved?  Since direct import will fail only option is to import individual private keys?

**Comment by jasonbcox** [comment]
Try `-upgradewallet` to not initiate a rescan.

It's difficult to recommend a version to use when it's completely unclear what version you're actually running or what your goal is.  Typically, running any of the latest major version numbers is recommended (0.21.x).
