### ISSUE TITLE
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

### ISSUE THREAD

**Issue by rex4539** [Bitcoin-ABC/bitcoin-abc#378]
Latest master.

Steps:
Launch BitcoinABC-Qt.app on macOS.

What happened:
The following is logged in the console:
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.`

Expected result:
What the message says.

**Comment by Fabcien** [comment]
This diff is expected to fix the issue: https://reviews.bitcoinabc.org/D5744.
Can you please try it and confirm it works ? I don't have the warning on my machine.

**Comment by Fabcien** [comment]
Thanks for the review, this is fixed in current master.
