### ISSUE TITLE
My Bitcoin ABC  v0.19.9.0-2f1adeefb  is stuck on block 609161

### ISSUE THREAD

**Issue by mtb-pro** [Bitcoin-ABC/bitcoin-abc#383]
I have been stuck at block 609161 
I use invalidateblock and reconsiderblock  but not working

 bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 609134,
  "headers": 632877,
  "bestblockhash": "000000000000000000d03bd9b9a7d3b734b3910d8ae59d8ed237174517e8aaf9",
  "difficulty": 385174366036.6172,
  "mediantime": 1573818748,
  "verificationprogress": 0.8596174690370024,
  "initialblockdownload": true,
  "chainwork": "000000000000000000000000000000000000000001090e4d53d34155da3b17f3",
  "size_on_disk": 164169544647,
  "pruned": false,
  "warnings": ""
}

**Comment by jasonbcox** [comment]
According to your getblockchaininfo output, you're actually stuck at this block: https://blockchair.com/bitcoin-cash/block/000000000000000000d03bd9b9a7d3b734b3910d8ae59d8ed237174517e8aaf9 with height 609134

This is expected, as Bitcoin Cash undergoes protocol upgrades every 6 months on May 15th and November 15th each year. Note the date the above block was mined.

We provided information on the November 2019 upgrade here: https://www.bitcoinabc.org/2019-08-21-bitcoin-abc-0.20.0/
And note the upcoming May 2020 upgrade (~2 weeks from now): https://www.bitcoinabc.org/2020-02-18-bitcoin-abc-0.21.0/

To stay compatible with these upgrades, you would need to run a newer release. All current 0.21.x versions of Bitcoin ABC are compatible with the upcoming May 2020 upgrade. Check out our latest here: https://download.bitcoinabc.org/latest/

Feel free to ask followup questions in this thread, but I'll be closing this issue for now.
