### ISSUE TITLE
Script error string parity with Bitcoin Core

### ISSUE THREAD

**Issue by rkalis** [Bitcoin-ABC/bitcoin-abc#393]
Hey guys. I compared the different kinds of Script errors in Bitcoin ABC and Bitcoin Core. Of course there are differences due to different functionality (e.g. ABC has `CHECKDATASIGVERIFY` and Core has `WITNESS_MALLEATED`). But I noticed two cases (`SIG_PUSHONLY` and `CLEANSTACK`) where the same error has a slightly different error string (because they were added or fixed independently of each other).

ABC:
```cpp
case ScriptError::SIG_PUSHONLY:
    return "Only push operators allowed in signature scripts";
case ScriptError::CLEANSTACK:
    return "Script did not clean its stack";
```

Core:
```cpp
case SCRIPT_ERR_SIG_PUSHONLY:
    return "Only push operators allowed in signatures";
case SCRIPT_ERR_CLEANSTACK:
    return "Extra items left on stack after execution";
```

These are small differences, but when testing the same scripts on BCH and BTC it is useful if the same errors give the same messages. Are you open to changing these error messages to match Core?

**Comment by jasonbcox** [comment]
Thanks for bringing this to our attention.  I've submitted patches to fix both:
https://reviews.bitcoinabc.org/D6696
https://reviews.bitcoinabc.org/D6697

**Comment by rkalis** [comment]
Awesome! Thanks for picking it up @jasonbcox!

**Comment by jasonbcox** [comment]
Cheers. Both error messages should be fixed on master now.
