### ISSUE TITLE
sendrawtransaction rpc command - maxfeerate data type

### ISSUE THREAD

**Issue by miki208** [Bitcoin-ABC/bitcoin-abc#394]
When I pass a string as the second argument for rpc command sendrawtransaction, I'm getting the next error **"second argument (maxfeerate) must be numeric"**, even if the documentation says this argument can be numeric or string.

I think the problem is in the next fragment of the code (src/rpc/rawtransaction.cpp):
```
    if (request.params[1].isBool()) {
        throw JSONRPCError(RPC_INVALID_PARAMETER,
                           "Second argument must be numeric (maxfeerate) and "
                           "no longer supports a boolean. To allow a "
                           "transaction with high fees, set maxfeerate to 0.");
    } else if (request.params[1].isNum()) {
        size_t sz = tx->GetTotalSize();
        CFeeRate fr(AmountFromValue(request.params[1]));
        max_raw_tx_fee = fr.GetFee(sz);
    } else if (!request.params[1].isNull()) {
        throw JSONRPCError(RPC_INVALID_PARAMETER,
                           "second argument (maxfeerate) must be numeric");
    }
```
Here we see that only numeric param will be accepted.
I think this should be fixed. Even better, this param can be represented in satoshi instead of btc to avoid ieee-754 representation problems since **AmountFromValue** expects up to 8 digits after decimal point. For example, 1.001 will be represented as 1.00099999999999999, and this leads to a problem when we try to convert it to int (error message - Invalid amount).

I'm using Bitcoin ABC 0.21.9.

**Comment by PiRK** [comment]
Closed by 5669673ce7b6476e0c63c894214aa8ce8c1a505d
