### ISSUE TITLE
BitcoinABC stuck at block #53036

### ISSUE THREAD

**Issue by velipx** [Bitcoin-ABC/bitcoin-abc#398]
Syncing is stuck on block #213123, i tried to -research, -resync, remove whole folder then again start new fresh bitcoin abc but every time i got stuck. I also tried to invalidateblock and then reconsiderblock but with no success.

Here is my logs:
![Screenshot_1](https://user-images.githubusercontent.com/17400336/87598325-6578f580-c6f3-11ea-83fe-41e6b82853b1.png)

### Machine specs:
- OS: Cent OS 7 (64 Bit)
- CPU: AMD EPYC 7282 16-Core Processor, 6 cores
- RAM: 16 GB
- Disk size: 500 GB
- Disk Type (HD/SDD): SSD

**Comment by jasonbcox** [comment]
Closing because this issue is old and pertains to an old version.  But just at a glance, block `213123` should be `0000000000000046690d157d719a597870ab0efcf3abaeae62435d4ffb2daed2` which doesn't appear in that log screenshot.
