### ISSUE TITLE
Help: Need BCH Testnet (Faucet)

### ISSUE THREAD

**Issue by Droppix** [Bitcoin-ABC/bitcoin-abc#399]
Hi,

I need to do advanced testing on testnet, but I would need between 10-15 BCH, could someone send me to the following address: bchtest:qzxfwen5w3p99whn2gmkpgcdkj63rwf2xy9ldnlr9c

Many thanks

**Comment by Mengerian** [comment]
Hi @Droppix I just sent 50 tBCH to your address: https://texplorer.bitcoincash.org/tx/438cc8ac4aeb4a007c4581ec266fa3b21107a912864ebb17ef14a204678abb0d

**Comment by Droppix** [comment]
ah, many thanks...
