### ISSUE TITLE
Can't build v0.22.2

### ISSUE THREAD

**Issue by gituser** [Bitcoin-ABC/bitcoin-abc#400]
### Describe the issue

With new build system introduced in v0.22.2 it seems some dependencies / libraries are still checked from the system instead of the depends directory, there might be an error in CMake / Ninja scripts.

Before new compilation system I was using old one (autotools) and it was working just fine on the same system.

#### If so, please list the steps to reproduce below:
1. Get v0.22.2 tag.
2. Use this script for building Bitcoin-ABC by using depends system:
```
#!/bin/bash
VER=$(git describe --tags)
daemon=$(pname=$(pwd); echo ${pname##/*/})

# build dependencies (bitcoin-abc specific)
CC=/usr/bin/gcc CXX=/usr/bin/g++ make -j4 -C depends HOST=x86_64-linux-gnu NO_ZMQ=1 NO_QT=1 NO_UPNP=1

DEPENDS="$(pwd)/depends/x86_64-linux-gnu"
mkdir build -p
cd build
cmake -GNinja .. -DENABLE_QRCODE=OFF -DENABLE_UPNP=OFF -DBUILD_BITCOIN_ZMQ=OFF -DBUILD_BITCOIN_QT=OFF -DCMAKE_TOOLCHAIN_FILE=../cmake/platforms/Linux64.cmake
if [ "$?" != 0 ]; then
    echo "[-] Configure FAILED"
    exit 1
fi
#make -j8
ninja
if [ "$?" == 0 ]; then
       echo "Build succeeded!"
else
	echo "Build Failed."
fi

```

3. Instead of using libevent inside depends directory Bitcoin-ABC tries to use system libevent-2.0.21-stable:
```
$ ./build.sh
make: Entering directory '/home/build/bitcoinabc/source/depends'
copying packages: native_protobuf boost openssl libevent bdb protobuf jemalloc
to: /home/build/bitcoinabc/source/depends/x86_64-linux-gnu
make: Leaving directory '/home/build/bitcoinabc/source/depends'
-- Using ccache: /usr/bin/ccache
-- Looking for __builtin_clz
-- Looking for __builtin_clz - found
-- Looking for __builtin_clzl
-- Looking for __builtin_clzl - found
-- Looking for __builtin_clzll
-- Looking for __builtin_clzll - found
-- Looking for __builtin_popcount
-- Looking for __builtin_popcount - found
-- Check if jemalloc needs libdl - FALSE
-- Found Boost 1.70.0 at /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS chrono;filesystem;thread
-- Found boost_headers 1.70.0 at /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/lib/cmake/boost_headers-1.70.0
-- Found boost_chrono 1.70.0 at /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/lib/cmake/boost_chrono-1.70.0
--   libboost_chrono-mt-x64.a
-- Adding boost_chrono dependencies: headers
-- Found boost_filesystem 1.70.0 at /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem-mt-x64.a
-- Adding boost_filesystem dependencies: headers
-- Found boost_thread 1.70.0 at /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/lib/cmake/boost_thread-1.70.0
--   libboost_thread-mt-x64.a
-- Adding boost_thread dependencies: headers
CMake Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Event: Found unsuitable version "2.0.21-stable", but
  required is at least "2.0.22" (found
  /home/build/bitcoinabc/source/depends/x86_64-linux-gnu/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:443 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindEvent.cmake:84 (find_package_handle_standard_args)
  src/CMakeLists.txt:391 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/build/bitcoinabc/source/build/CMakeFiles/CMakeOutput.log".
See also "/home/build/bitcoinabc/source/build/CMakeFiles/CMakeError.log".
[-] Configure FAILED
```

4. There is libevent installed globally:

```
$ dpkg -l|grep libevent-
ii  libevent-2.0-5:amd64                  2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library
ii  libevent-core-2.0-5:amd64             2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (core)
ii  libevent-dev                          2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (development files)
ii  libevent-extra-2.0-5:amd64            2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (extra)
ii  libevent-openssl-2.0-5:amd64          2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (openssl)
ii  libevent-pthreads-2.0-5:amd64         2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (pthreads)
```

5. Inside the depends system libevent has the correct version:
```
$ ls -al depends/built/x86_64-linux-gnu/libevent/libevent-2.1.11-stable-b91e0c623cd.tar.gz
-rw-rw-r-- 1 build build 461274 Sep 22 15:06 depends/built/x86_64-linux-gnu/libevent/libevent-2.1.11-stable-b91e0c623cd.tar.gz
```

### Expected behaviour
Bitcoin-ABC should be compiling using depends system fine ignoring libraries installed globally.

### Actual behaviour
Bitcoin-ABC compilation fails

### What version of bitcoin-abc are you using?
v0.22.2

### Machine specs:
- OS: Ubuntu 16.04.6 LTS

**Comment by gituser** [comment]
Ping @jasonbcox

**Comment by laakie** [comment]
Having a lot of trouble building with cmake as well Ubuntu 18.04 
Found unsuitable version "1.58.0", but required is at
  least "1.59"

Latest boost for 18.04 is 1.58.0
Prefered the old build procedure where the depends where used properly.

**Comment by jasonbcox** [comment]
We're looking into it. Thanks for the bug report.

**Comment by Fabcien** [comment]
The bug has been fixed on current master, unfortunately too late to make it in the coming 0.22.4 release so it will be part of 0.22.5.

If the problem persists, please re-open this issue.

**Comment by Fabcien** [comment]
@biatwc CentOS 7 has a glibc version which is too old for the software, so this fix won't be enough to let you complete the build. A solution is to upgrade to CentOS 8; if it is not possible and you can run a Docker container I suggest you take a look at the [Bitcoin ABC containers](https://hub.docker.com/u/bitcoinabc) which will let you run the release version or build yourself inside a container. You may want to read [these instructions](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/depends/README.md) to build against the static libraries.

Feel free to open a separate issue if you find another bug.

**Comment by gituser** [comment]
@Fabcien any ETA on v0.22.5 release?

**Comment by Fabcien** [comment]
@gituser 0.22.5 should be available on October 27th.
You can also pull the current master branch which has the fix if you don't want to wait, or use the [Bitcoin ABC development container](https://hub.docker.com/r/bitcoinabc/bitcoin-abc-dev) which is not affected by this bug.

**Comment by gituser** [comment]
@Fabcien I've tried building latest master - still no luck, same error.

**Comment by Fabcien** [comment]
@gituser Please clear your cmake cache and try again (in doubt you can delete your build directory).
If the issue persists please post your full cmake output.

**Comment by gituser** [comment]
@Fabcien 

Yes, that was it, I forgot to remove existing `build` directory before building new version.

Thank you, it worked!

**Comment by M8BWNN** [comment]
same error here..
started with a fresh git clone, checkout master

> cmake -GNinja ..
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: /usr/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5") found components: Interpreter 
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Performing Test have_CXX__Werror_unused_command_line_argument
-- Performing Test have_CXX__Werror_unused_command_line_argument - Failed
-- Performing Test have_linker__fuse_ld_gold
-- Performing Test have_linker__fuse_ld_gold - Success
-- Performing Test have_C__g3
-- Performing Test have_C__g3 - Success
-- Performing Test have_CXX__g3
-- Performing Test have_CXX__g3 - Success
-- Performing Test have_C__ftrapv
-- Performing Test have_C__ftrapv - Success
-- Performing Test have_CXX__ftrapv
-- Performing Test have_CXX__ftrapv - Success
-- Performing Test have_C__fstack_reuse_none
-- Performing Test have_C__fstack_reuse_none - Success
-- Performing Test have_CXX__fstack_reuse_none
-- Performing Test have_CXX__fstack_reuse_none - Success
-- Performing Test have_CXX__fstack_protector_all
-- Performing Test have_CXX__fstack_protector_all - Success
-- Performing Test have_CXX__Wstack_protector
-- Performing Test have_CXX__Wstack_protector - Success
-- Performing Test have_C__U_FORTIFY_SOURCE
-- Performing Test have_C__U_FORTIFY_SOURCE - Success
-- Performing Test have_CXX__U_FORTIFY_SOURCE
-- Performing Test have_CXX__U_FORTIFY_SOURCE - Success
-- Performing Test have_linker__Wl___dynamicbase
-- Performing Test have_linker__Wl___dynamicbase - Failed
-- Performing Test have_linker__Wl___nxcompat
-- Performing Test have_linker__Wl___nxcompat - Failed
-- Performing Test have_linker__Wl___high_entropy_va
-- Performing Test have_linker__Wl___high_entropy_va - Failed
-- Performing Test have_linker__Wl__z_relro
-- Performing Test have_linker__Wl__z_relro - Success
-- Performing Test have_linker__Wl__z_now
-- Performing Test have_linker__Wl__z_now - Success
-- Performing Test have_C__Wnested_externs
-- Performing Test have_C__Wnested_externs - Success
-- Performing Test have_C__Wstrict_prototypes
-- Performing Test have_C__Wstrict_prototypes - Success
-- Performing Test have_C__Wall
-- Performing Test have_C__Wall - Success
-- Performing Test have_C__Wextra
-- Performing Test have_C__Wextra - Success
-- Performing Test have_C__Wformat
-- Performing Test have_C__Wformat - Success
-- Performing Test have_C__Wvla
-- Performing Test have_C__Wvla - Success
-- Performing Test have_C__Wcast_align
-- Performing Test have_C__Wcast_align - Success
-- Performing Test have_C__Wunused_parameter
-- Performing Test have_C__Wunused_parameter - Success
-- Performing Test have_C__Wmissing_braces
-- Performing Test have_C__Wmissing_braces - Success
-- Performing Test have_C__Wthread_safety
-- Performing Test have_C__Wthread_safety - Failed
-- Performing Test have_C__Wshadow
-- Performing Test have_C__Wshadow - Success
-- Performing Test have_C__Wshadow_field
-- Performing Test have_C__Wshadow_field - Failed
-- Performing Test have_C__Wrange_loop_analysis
-- Performing Test have_C__Wrange_loop_analysis - Failed
-- Performing Test have_C__Wredundant_decls
-- Performing Test have_C__Wredundant_decls - Success
-- Performing Test have_CXX__Wall
-- Performing Test have_CXX__Wall - Success
-- Performing Test have_CXX__Wextra
-- Performing Test have_CXX__Wextra - Success
-- Performing Test have_CXX__Wformat
-- Performing Test have_CXX__Wformat - Success
-- Performing Test have_CXX__Wvla
-- Performing Test have_CXX__Wvla - Success
-- Performing Test have_CXX__Wcast_align
-- Performing Test have_CXX__Wcast_align - Success
-- Performing Test have_CXX__Wunused_parameter
-- Performing Test have_CXX__Wunused_parameter - Success
-- Performing Test have_CXX__Wmissing_braces
-- Performing Test have_CXX__Wmissing_braces - Success
-- Performing Test have_CXX__Wthread_safety
-- Performing Test have_CXX__Wthread_safety - Failed
-- Performing Test have_CXX__Wshadow
-- Performing Test have_CXX__Wshadow - Success
-- Performing Test have_CXX__Wshadow_field
-- Performing Test have_CXX__Wshadow_field - Failed
-- Performing Test have_CXX__Wrange_loop_analysis
-- Performing Test have_CXX__Wrange_loop_analysis - Failed
-- Performing Test have_CXX__Wredundant_decls
-- Performing Test have_CXX__Wredundant_decls - Success
-- Performing Test have_C__Wformat__Wformat_security
-- Performing Test have_C__Wformat__Wformat_security - Success
-- Performing Test have_CXX__Wformat__Wformat_security
-- Performing Test have_CXX__Wformat__Wformat_security - Success
-- Performing Test have_CXX__Wredundant_move
-- Performing Test have_CXX__Wredundant_move - Success
-- Performing Test have_C__Wno_unused_parameter
-- Performing Test have_C__Wno_unused_parameter - Success
-- Performing Test have_CXX__Wno_unused_parameter
-- Performing Test have_CXX__Wno_unused_parameter - Success
-- Performing Test have_C__Wno_implicit_fallthrough
-- Performing Test have_C__Wno_implicit_fallthrough - Success
-- Performing Test have_CXX__Wno_implicit_fallthrough
-- Performing Test have_CXX__Wno_implicit_fallthrough - Success
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Looking for include file sys/endian.h
-- Looking for include file sys/endian.h - not found
-- Looking for htole16
-- Looking for htole16 - found
-- Looking for htobe16
-- Looking for htobe16 - found
-- Looking for be16toh
-- Looking for be16toh - found
-- Looking for le16toh
-- Looking for le16toh - found
-- Looking for htobe32
-- Looking for htobe32 - found
-- Looking for htole32
-- Looking for htole32 - found
-- Looking for be32toh
-- Looking for be32toh - found
-- Looking for le32toh
-- Looking for le32toh - found
-- Looking for htobe64
-- Looking for htobe64 - found
-- Looking for htole64
-- Looking for htole64 - found
-- Looking for be64toh
-- Looking for be64toh - found
-- Looking for le64toh
-- Looking for le64toh - found
-- Looking for include file byteswap.h
-- Looking for include file byteswap.h - found
-- Looking for bswap_16
-- Looking for bswap_16 - found
-- Looking for bswap_32
-- Looking for bswap_32 - found
-- Looking for bswap_64
-- Looking for bswap_64 - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/prctl.h
-- Looking for include file sys/prctl.h - found
-- Looking for __builtin_clz
-- Looking for __builtin_clz - found
-- Looking for __builtin_clzl
-- Looking for __builtin_clzl - found
-- Looking for __builtin_clzll
-- Looking for __builtin_clzll - found
-- Looking for __builtin_popcount
-- Looking for __builtin_popcount - found
-- Looking for M_ARENA_MAX
-- Looking for M_ARENA_MAX - found
-- Looking for malloc_info
-- Looking for malloc_info - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for daemon
-- Looking for daemon - found
-- Looking for getentropy
-- Looking for getentropy - not found
-- Looking for getentropy
-- Looking for getentropy - not found
-- Looking for include files sys/types.h, vm/vm_params.h
-- Looking for include files sys/types.h, vm/vm_params.h - not found
-- Looking for include files sys/types.h, sys/vmmeter.h
-- Looking for include files sys/types.h, sys/vmmeter.h - not found
-- Looking for include files sys/types.h, sys/resources.h
-- Looking for include files sys/types.h, sys/resources.h - not found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for freeifaddrs
-- Looking for freeifaddrs - found
-- Performing Test HAVE_SYS_GETRANDOM
-- Performing Test HAVE_SYS_GETRANDOM - Success
-- Performing Test HAVE_SYSCTL_ARND
-- Performing Test HAVE_SYSCTL_ARND - Failed
-- Performing Test CHAR_EQUALS_INT8
-- Performing Test CHAR_EQUALS_INT8 - Failed
-- Performing Test HAVE_LARGE_FILE_SUPPORT
-- Performing Test HAVE_LARGE_FILE_SUPPORT - Success
-- Performing Test HAVE_FUNC_ATTRIBUTE_VISIBILITY
-- Performing Test HAVE_FUNC_ATTRIBUTE_VISIBILITY - Success
-- Performing Test HAVE_FUNC_ATTRIBUTE_DLLEXPORT
-- Performing Test HAVE_FUNC_ATTRIBUTE_DLLEXPORT - Failed
-- Looking for std::system
-- Looking for std::system - found
-- Looking for ::wsystem
-- Looking for ::wsystem - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Jemalloc component jemalloc: /usr/lib/x86_64-linux-gnu/libjemalloc_pic.a
-- Check if jemalloc needs libdl - FALSE
-- Found Jemalloc: /usr/include/jemalloc (found suitable version "3.6.0", minimum required is "3.6.0")  
-- Performing Test ENABLE_SSE41
-- Performing Test ENABLE_SSE41 - Success
-- Performing Test ENABLE_AVX2
-- Performing Test ENABLE_AVX2 - Success
-- Performing Test ENABLE_SHANI
-- Performing Test ENABLE_SHANI - Success
-- Performing Test have_C__Wno_inconsistent_missing_override
-- Performing Test have_C__Wno_inconsistent_missing_override - Success
-- Performing Test have_C__Wno_maybe_uninitialized
-- Performing Test have_C__Wno_maybe_uninitialized - Success
-- Performing Test have_C__Wno_shadow
-- Performing Test have_C__Wno_shadow - Success
-- Performing Test have_C__Wno_sign_compare
-- Performing Test have_C__Wno_sign_compare - Success
-- Performing Test have_C__Wno_unused_const_variable
-- Performing Test have_C__Wno_unused_const_variable - Success
-- Performing Test have_CXX__Wno_inconsistent_missing_override
-- Performing Test have_CXX__Wno_inconsistent_missing_override - Success
-- Performing Test have_CXX__Wno_maybe_uninitialized
-- Performing Test have_CXX__Wno_maybe_uninitialized - Success
-- Performing Test have_CXX__Wno_shadow
-- Performing Test have_CXX__Wno_shadow - Success
-- Performing Test have_CXX__Wno_sign_compare
-- Performing Test have_CXX__Wno_sign_compare - Success
-- Performing Test have_CXX__Wno_unused_const_variable
-- Performing Test have_CXX__Wno_unused_const_variable - Success
-- Performing Test have_C__Wno_strict_prototypes
-- Performing Test have_C__Wno_strict_prototypes - Success
-- Looking for C++ include atomic
-- Looking for C++ include atomic - found
-- Performing Test ENABLE_HWCRC32
-- Performing Test ENABLE_HWCRC32 - Success
-- Performing Test have_C__pedantic
-- Performing Test have_C__pedantic - Success
-- Performing Test have_C__Wundef
-- Performing Test have_C__Wundef - Success
-- Performing Test have_C__Wno_unused_function
-- Performing Test have_C__Wno_unused_function - Success
-- Performing Test have_C__Wno_overlength_strings
-- Performing Test have_C__Wno_overlength_strings - Success
-- Performing Test have_C__std_c89
-- Performing Test have_C__std_c89 - Success
-- Performing Test have_C__Wno_long_long
-- Performing Test have_C__Wno_long_long - Success
-- Performing Test USE_ASM_X86_64
-- Performing Test USE_ASM_X86_64 - Success
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") found components: Crypto 
-- Found Event component event: /usr/lib/x86_64-linux-gnu/libevent.so
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Event: Found unsuitable version "2.0.21-stable", but
  required is at least "2.0.22" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindEvent.cmake:85 (find_package_handle_standard_args)
  cmake/modules/NativeExecutable.cmake:25 (find_package)
  src/CMakeLists.txt:394 (non_native_target_link_libraries)
  src/CMakeLists.txt:397 (link_event)

**Comment by Fabcien** [comment]
@M8BWNN This is not the same error, and this is not a bug: you need a more recent version of libevent.

This bug is about [building using the static dependencies](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/depends/README.md), which provides a suitable libevent version for the build.
