### ISSUE TITLE
Help: Need BCH Testnet (Faucet)

### ISSUE THREAD

**Issue by andersonaraujo** [Bitcoin-ABC/bitcoin-abc#403]
Hi,

I need to do some testing on testnet and would need some BCH, could someone indicate a working testnet faucet or send me to the following address: bchtest:qzhylyl8v7gazffanzc9e8es62f5yuzgngshtw6760

Thanks!

**Comment by jasonbcox** [comment]
sent: https://texplorer.bitcoincash.org/tx/8060702472a04b3286244219de2e4e67ef286cd14111ee8714aea206832bbd0c

**Comment by andersonaraujo** [comment]
awesome, tks a lot!
