### ISSUE TITLE
Upcomining infrastructure mining hardfork.

### ISSUE THREAD

**Issue by laakie** [Bitcoin-ABC/bitcoin-abc#409]
We see there's a new field added to the coinbasetx in getblocktemplate.
Containing :
"coinbasetxn": { 
      "minerfund": { "addresses": [ ],
      "minimumvalue": 0 } 
},

Can anybody specify how to use this when activated ?

The "minerfund" is going to be 5%  ?
Do we pick one address from the minerFund ?

Maybe you can share  a usecase example ?

**Comment by Fabcien** [comment]
After activation, these fields will contain indications about the new coinbase rule. You can use the [upgrade testnet](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/workgroups/wg-testing/2020-11-15_upgrade_testnet.md) to see the output of these fields.

You can find the specifications for the new coinbase rule [here](https://www.bitcoincash.org/spec/2020-11-15-upgrade.html#coinbase-rule). For details on how to setup your mining pool, please refer to the section `Essential information for mining pool operators` from [this article](https://blog.bitcoinabc.org/2020/11/03/tech-checklist-preparing-your-node-for-the-network-upgrade/).

I hope this will give you all the information you need. I'm closing this as this is not an issue, but rather a support request. If you need further assistance, please [open a ticket](https://help.bitcoincash.org/support/tickets/new) and we will do our best to help you.
