### ISSUE TITLE
how to start up bcha or bchn node?

### ISSUE THREAD

**Issue by EthanHee** [Bitcoin-ABC/bitcoin-abc#411]
I have found two images(images: bitcoinabc/bitcoin-abc-bchn:0.22.6 and bitcoinabc/bitcoin-abc:0.22.6) from your official dockerhub, both them use the same execute file(bitcoin-abc-0.22.6-x86_64-linux-gnu.tar.gz)，and start up the container with the same command,.

so where is the differences between the  two images?
or am I missing something?

**Comment by Fabcien** [comment]
Bitcoin ABC is providing 2 versions of the node software, one with support for the new [coinbase rule](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2020-11-15-upgrade.md#coinbase-rule) and one without. This is the difference between these 2 images. You can learn more on the motivations by reading [this article](https://blog.bitcoinabc.org/2020/11/06/bitcoin-abc-will-support-both-bcha-and-bchn-after-the-chain-split/).
