### ISSUE TITLE
Mempool txs are not syncing automatically

### ISSUE THREAD

**Issue by JohnsonCaii** [Bitcoin-ABC/bitcoin-abc#417]
Hi all.

I use the `sendtoaddress` rpc method to transfer BCHA to another address, I got the txid returned. 

But I can't search the txid on https://blockchair.com/bitcoin-abc, so I think that mempool transaction is not syncing between our node and blockchair's node automatically.

What the problem could be? what should I do?

bitcoin-abc node version I am using: `0.22.7`

**Comment by Fabcien** [comment]
If you are using the BCHN version, then you are looking at the wrong chain in the explorer. You should use https://blockchair.com/bitcoin-cash instead.
You can look at [this page](https://blog.bitcoinabc.org/2020/11/06/bitcoin-abc-will-support-both-bcha-and-bchn-after-the-chain-split/) to get more information on the difference between the two chains. You can also l[earn more about the BCHA chain](https://www.bitcoinabc.org/bcha/).

**Comment by JohnsonCaii** [comment]
> If you are using the BCHN version, then you are looking at the wrong chain in the explorer. You should use https://blockchair.com/bitcoin-cash instead.
> You can look at [this page](https://blog.bitcoinabc.org/2020/11/06/bitcoin-abc-will-support-both-bcha-and-bchn-after-the-chain-split/) to get more information on the difference between the two chains. You can also l[earn more about the BCHA chain](https://www.bitcoinabc.org/bcha/).

Sorry I misspell the BCHA
