### ISSUE TITLE
Duplicate transaction in both BCH & BCHA chain

### ISSUE THREAD

**Issue by pmtoan** [Bitcoin-ABC/bitcoin-abc#418]
I am running a BCHA (version 0.22.6) full node. When I push a raw transaction (use sendrawtransaction RPC), but the transaction also broadcasted to the BCHN chain? Can anyone help me to explain what happens here?

Here my transaction broadcasted: https://blockchair.com/search?q=404cbfd8b6f44bb304ff3291a01ab5c7eb8297c021b988b8617c23aca49c66bf

**Comment by jasonbcox** [comment]
There is no replay protection, so if your UTXO is valid on both chains, the transaction will be also. See our splitting guide for help on splitting your coins: https://blog.bitcoinabc.org/2020/11/25/how-to-split-your-bch-bchn-and-bcha-coins-using-electrum-abc-and-electron-cash/
