### ISSUE TITLE
After installing bitcoinabc/bitcoin-abc-bchn:0.22.8 image it syncs testnet with bcha

### ISSUE THREAD

**Issue by enertom** [Bitcoin-ABC/bitcoin-abc#424]
After installing bitcoinabc/bitcoin-abc-bchn (https://hub.docker.com/r/bitcoinabc/bitcoin-abc-bchn) image it syncs testnet with bcha

Expect this sync to testnet of BCHN(e.g. https://www.blockchain.com/explorer?view=bch-testnet), but this sync to testnet of BCHA https://texplorer.bitcoinabc.org/.

Could you help me? I want to start BCHN testnet

Thanks.

**Comment by Fabcien** [comment]
The bitcoinabc/bitcoin-abc-bchn node software is not compatible with the BCHN testnet; the PoW rules for testnet differ, making them incompatible. The Bitcoin ABC node enforces the same PoW rules as mainnet, which is not the case for BCHN.
