### ISSUE TITLE
bitcoinabc 0.22.12 can't sync , stop on block 678694

### ISSUE THREAD

**Issue by ritech** [Bitcoin-ABC/bitcoin-abc#428]
show 3 days behind , not new block sync to my server.
where could get office node list?

**Comment by Fabcien** [comment]
Can you try to run these commands and see if it solves the problem ?:
```
parkblock 00000000000000004edd0db5451a0d28b4a1742da26afb1e8861e7a9cb7d43e6
unparkblock 000000000000000059982f6062828a7422f1fc4eb043e471269f9c8e71a130b7
```

If not please paste the output of `getchaintips`
