### ISSUE TITLE
ERROR: AcceptBlockHeader: block 00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148 is marked invalid, stuck at 478558

### ISSUE THREAD

**Issue by c0deright** [Bitcoin-ABC/bitcoin-abc#44]
Bitcoin ABC:0.14.6(EB8.0) is stuck at block 478558 (core, unlimited, btc1, uasf is at 478560) and logs:

```
2017-08-01 13:31:54 receive version message: /Satoshi:0.14.2/: version 70015, blocks=478560, us=XXX, peer=35, peeraddr=XXX
2017-08-01 13:31:54 ERROR: AcceptBlockHeader: block 00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148 is marked invalid
2017-08-01 13:31:54 ERROR: invalid header received
2017-08-01 13:31:54 ProcessMessages(headers, 163 bytes) FAILED peer=35
```

Error repeats, abc node is stuck at 478558

**Comment by c0deright** [comment]
```
2017-08-01 13:34:50 ERROR: AcceptBlockHeader: prev block invalid
2017-08-01 13:34:50 Misbehaving: XXXX:8333 peer=41 (0 -> 100) reason: bad-prevblk BAN THRESHOLD EXCEEDED
```

**Comment by AugustoResende** [comment]
Is not a issue, LOL

This is your "beautiful" scheduled fork.

**Comment by c0deright** [comment]
This is wrong

```
core: blockhash(478558) = 0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43)
abc: blockhash(478558) = 0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43)
```

so block 478558 is identical on ABC and core. but ABC doesn' accept the next block because of "prev block invalid".

So this clearly is a bug and not a fork.

**Comment by c0deright** [comment]
Have a look at https://www.btcforkmonitor.info/ where ABC is stuck at the same block.

**Comment by jlauwers** [comment]
The new block 478559 is not valid under ABC's new rules:
00000000000000000019f112ec0a9982926f1258cdcc558dd7c3b7e5dc7fa148 is marked invalid.
478558 (0000000000000000011865af4122fe3b144e2cbeea86142e8ff2fb4107352d43) is totaly fine.

**Comment by NiKiZe** [comment]
@c0deright in what way is it a bug when this is the expected behavior? block 478559 is the first block that will be different and "mark the start of the new chain"

**Comment by c0deright** [comment]
Ok, my bad. Then i miscalculated the median time from which on ABC is rejecting blocks smaller than 1 MByte.

**Comment by deadalnix** [comment]
@c0deright We are forking. That's the whole point. Closing :)
