### ISSUE TITLE
Question.) About CashTab Chrome Extension  

### ISSUE THREAD

**Issue by HamSungJun** [Bitcoin-ABC/bitcoin-abc#443]
Q.) Can the 12-word seed phrase of the CashTab wallet be treated the same as if I was completely disconnected from the network, as if I had written it all down on paper?

**Comment by BytesOfMan** [comment]
It's important to always physically back up your wallet seed. If you lose the device you keep your Cashtab wallet on, you will lose your Cashtab wallet unless you have backed it up.

Cashtab is completely non-custodial so you are responsible for you own backups.
