### ISSUE TITLE
Possible bug in pow.cpp difficulty adjustment

### ISSUE THREAD

**Issue by fransla** [Bitcoin-ABC/bitcoin-abc#45]
The modified difficulty adjustment code in pow.cpp checks the time to generate the last 6 blocks, no reference to the current time. As the last 6 blocks were on the original chain, they were fast, and the difficulty would therefore not adjust unless at least one other block is found first.

**Comment by deadalnix** [comment]
This is not a bug, this is as intended. Doing it over one block would be easy to cheat.

**Comment by psy0rz** [comment]
isnt this whole fork one big cheat?
