### ISSUE TITLE
Please don't use Google Analytics in Cashtab

### ISSUE THREAD

**Issue by aalfiann** [Bitcoin-ABC/bitcoin-abc#473]
This is not an issue, but just some suggestion for cashtab..

For privacy protection to user. please don't use Google Analytics in Cashtab.

eCash should having own analytics service in the future.

**Comment by BytesOfMan** [comment]
GA is used for minimal usage data collection and it's specific use may be reviewed in the open source code. It would be nice to do away with GA entirely, but at the moment there is not a practical replacement.

If you have a feature-parity replacement idea, please review the contribution guidelines and submit a diff.

Thanks!
