### ISSUE TITLE
Severe GUI blocking while synchronizing blockchain

### ISSUE THREAD

**Issue by brunophilipe** [Bitcoin-ABC/bitcoin-abc#49]
While synchronizing the blockchain, the GUI presents severe hangs and slow-downs, delayed click/keyboard events and other problems characteristic to running expensive code on the UI (main?) thread.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. Start bitcoin-qt with a very outdated blockchain state (mine was last updated with blocks from 2014 before switching to Bitcoin ABC). Maybe the bug also happens with a blank library state.
2. Let the synchronization run for about 15-30 minutes.
3. Attempt to use the GUI, which will be very slow, unresponsive and at times completely blocked.

### Expected behaviour

No hangs should happen. No UI Coe should be blocked.

### Actual behaviour

UI hangs constantly, sometimes for a few seconds, and every 3-5 seconds.

### Screenshots.
Screen capture: https://www.youtube.com/watch?v=HqWliB0S3AY

### What version of bitcoin-core are you using?
Bitcoin ABC v0.14.6.0-a46e63c
/Bitcoin ABC:0.14.6(EB8.0)/
Berkeley DB 4.8.30: (April  9, 2010)

### Machine specs:
- OS: macOS Sierra 10.12.6
- CPU: 3.3 GHz Intel Core i5
- RAM: 24 GB 1867 MHz DDR3
- Disk size: 2TB
- Disk Type (HD/SDD): Fusion Drive (HDD+SSD)

**Comment by nshopik** [comment]
Could be cherrypicked from here eventually
https://github.com/bitcoin/bitcoin/pull/10244
https://github.com/bitcoin/bitcoin/issues/10504

**Comment by xgiovio** [comment]
same problem

**Comment by archon5880** [comment]
I'm suffering from this too on Win10-x64.  The only way I know it is still syncing is to to right click on the icon in the system tray, and select Debug Window, which then lets me see the date and number of the last block synced.

**Comment by D4nte** [comment]
I have been trying to synchronize for the last 2 week. only 30 weeks of block remaining but it's getting even slower!

**Comment by brunophilipe** [comment]
I have found that quitting and restarting the software sometimes boosts the speed for an hour or two.

**Comment by D4nte** [comment]
I agree.

**Comment by archon5880** [comment]
I just upgraded to 15.0, the blockchain is fully synced, and I still can't see the value in my wallet.  In Win 10-64, there is a button on the taskbar and system tray, but I can only open the options and debug menus from it.

**Comment by schancel** [comment]
Is this still an issue?  I believe this was resolved by updating some of the seeding.

**Comment by schancel** [comment]
Closing as stale.
