### ISSUE TITLE
everything works fine, i made a mistake

### ISSUE THREAD

**Issue by cncuwebfvbvb** [Bitcoin-ABC/bitcoin-abc#494]

**Comment by cncuwebfvbvb** [comment]
Avalanche does not work well as a verification, there are structural defects in it

**Comment by cncuwebfvbvb** [comment]
Under certain circumstances, or in a sense, it has a lower threshold for replay attacks

**Comment by cncuwebfvbvb** [comment]
Avalanche is not currently up to the release standard.

**Comment by cncuwebfvbvb** [comment]
https://reviews.bitcoinabc.org/D10076

**Comment by cncuwebfvbvb** [comment]
Fatal error code associated with this module

**Comment by Fabcien** [comment]
In the event you found a bug, we have a disclosure policy that you can find at the root of the repository: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/DISCLOSURE_POLICY.md.
