### ISSUE TITLE
getblockchaininfo report incorrect verificationprogress after fork

### ISSUE THREAD

**Issue by nshopik** [Bitcoin-ABC/bitcoin-abc#53]
It easy to reproduce just run command `getblockchaininfo` from console. And notice even though node is fully synced `verificationprogress` will report values little below 1.0

**Comment by ftrader** [comment]
I reproduced this on two synchronized nodes. We noticed during testnet tests already that the progress calculation is flaky, at times showing above 1.0 .

We'll take a closer look at the `GuessVerificationProgress` function in src/validation.cpp .

**Comment by ftrader** [comment]
Data point - it has now come back to 1.0 at least for me:

2017-08-03 12:19:40 UpdateTip: new best=0000000000000000005c6d6ad5d3789f25429fa1c9bf3e2b5e03344072610256 height=478588 version=0x20000000 log2_work=86.862321 tx=243299828 date='2017-08-03 12:19:33' progress=1.000000 cache=339.5MiB(38277tx) warning='71 of last 100 blocks have unexpected version'

**Comment by nshopik** [comment]
Yeah, I've also see same, it correctly show-up on my 2 nodes.

**Comment by nshopik** [comment]
Looks like it happens if there long time between blocks

**Comment by schancel** [comment]
I'm not seeing this issue.
