### ISSUE TITLE
Misleading comments about new difficulty retarget constraints.

### ISSUE THREAD

**Issue by placeybordeaux** [Bitcoin-ABC/bitcoin-abc#55]
### Describe the issue

The current comment on the new difficulty adjustment does not reflect how the code works.

```
    // If producing the last 6 block took less than 12h, we keep the same
    // difficulty.
    const CBlockIndex *pindex6 = pindexPrev->GetAncestor(nHeight - 7);
    assert(pindex6);
    int64_t mtp6blocks =
        pindexPrev->GetMedianTimePast() - pindex6->GetMedianTimePast();
    if (mtp6blocks < 12 * 3600) {
        return nBits;
    }
```

GetMedianTimePast takes the median time for the last 11 blocks. An accurate comment would be 

```
    // If the difference between the median time for the last 11 blocks and blocks 7-18th from the tip is below 12 hours
    // then we keep the same difficulty.
```
### Can you reliably reproduce the issue?
Blocks 478565 and 478571 were more than 12 hours apart and there was no difficulty retarget.

### Expected behaviour
The comment should reflect the code

### Actual behaviour
The comment is misleading

**Comment by 0xfff** [comment]
we are looking at the difference of MTP of last 11 blocks and MTP of current block
see this for an explanation:
https://medium.com/@jimmysong/bitcoin-cash-difficulty-adjustments-2ec589099a8e

**Comment by placeybordeaux** [comment]
Yeah I now understand the code, but that comment is wrong and very misleading. The comment should either be updated or removed.

**Comment by schancel** [comment]
@placeybordeaux Please feel free to suggest some new wording.  Please reopen this issue when you do.

**Comment by placeybordeaux** [comment]
@schancel 

what about:
```
    // If the difference between the median time for the last 11 blocks and blocks 7-18th from the tip is below 12 hours
    // then we keep the same difficulty.
```
