### ISSUE TITLE
Cashtab oficial wallet

### ISSUE THREAD

**Issue by tonistrak** [Bitcoin-ABC/bitcoin-abc#556]
Hello, I deposited from bybit my xec to the Cashtab wallet fine, but now it won't let me return it to the bybit address where my xec were, why can't I withdraw my xec to the bybit address from the Cashtab wallet? When I put the address that Bybit gives me, it doesn't recognize my address and uses XEC network

**Comment by Fabcien** [comment]
There is no such thing as "ecash wallet", what wallet/version did you use exactly ?

**Comment by tonistrak** [comment]
Cash tab wallet , sorry

**Comment by tonistrak** [comment]
> There is no such thing as "ecash wallet", what wallet/version did you use exactly ?

Cashtab wallet , sorry , v2.52.1

**Comment by Fabcien** [comment]
According to https://scorecard.cash/ it appears that Bybit does not support the eCash address format. This means that you have to convert the address before it works on Cashtab. The coins go to the same destination, it's just a different representation of the same thing.

You can do this by using the address converter that is built into the Electrum ABC wallet: https://www.bitcoinabc.org/electrum/.
Another option is to use an online converter at https://converter.bitcoinabc.org: enter the address from Bybit, click "Convert" and you will get the converted address in the eCash tab.

If you don't feel like doing so, you should ask Bybit to add support for the eCash address format or to provide you the address in the correct format.

**Comment by Annawoody** [comment]
It sounds like there might be an issue with the compatibility between the Cashtab wallet and Bybit's address format has it been solved?
@tonistrak
