### ISSUE TITLE
Captcha Error: Cashtab "Claim Free XEC" on BRAVE Browser

### ISSUE THREAD

**Issue by gravouilj** [Bitcoin-ABC/bitcoin-abc#558]
FYI for Brave users who would like to try Cashtab and claim free XEC on it, there seems to be a problem with the captcha verification, you simply can't claim the free XEC and must use another browser. I Don't know if you can fix it or if it's linked Brave. Keep building ;)

<img width="331" alt="Capture d’écran 2024-11-22 à 15 25 35" src="https://github.com/user-attachments/assets/edb8b611-cae2-451a-93a4-0d66ce6e3fe8">

**Comment by BytesOfMan** [comment]
This error msg is related to API rate limiting. Right now this reward is rate limited to 3 rewards per week per IP address. This was implemented to fight scripted bots from making multiple claims.

You can see the setting here: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/apps/token-server/config.ts
