### ISSUE TITLE
How do I run this on Ubuntu?

### ISSUE THREAD

**Issue by deniskrop** [Bitcoin-ABC/bitcoin-abc#57]
I downloaded the binary but am unable to run bitcoin-cli on my ubuntu 16.04 Are there any instructions on how to properly install and run it?
Is there a qt version?

**Comment by ftrader** [comment]
Please see instructions in this post:

https://www.reddit.com/r/BitcoinABC/comments/6qb63a/bitcoin_abc_ubuntu_repo_has_been_updated_to_serve/

Yes, there is a Qt version .

**Comment by tkaczorro** [comment]
How to install Bitcoin ABC if I already have Bitcoin Core (Ubuntu)? Should I remove Bitcoin Core first? After it is installed, how do I return to Bitcoin Core if I want to?

**Comment by schancel** [comment]
You'll currently either need to run it in a container, or specify the datadir manually.
