### ISSUE TITLE
About nHashType on sign

### ISSUE THREAD

**Issue by matiu** [Bitcoin-ABC/bitcoin-abc#60]
On  the code, the sigHash seems to be pushed as it is before hashing:

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/e49826c1fcc36e5ae26de0ad4d06e2063a759e73/src/script/interpreter.cpp#L1399

But on the spec:

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/e49826c1fcc36e5ae26de0ad4d06e2063a759e73/src/script/interpreter.cpp#L1399

It says:
```
    ss << ((GetForkId() << 8) | nHashType);
```

Could someone help me to understand this? Thanks.

**Comment by deadalnix** [comment]
Current forkid is zero so it's all good.

Le 3 août 2017 16:06, "Matias Alejo Garcia" <notifications@github.com> a
écrit :

**Comment by matiu** [comment]
got it. thanks.
