### ISSUE TITLE
New Network Magic

### ISSUE THREAD

**Issue by TheBlueMatt** [Bitcoin-ABC/bitcoin-abc#62]
While nodes are already banning each other nicely, it would be much nicer to change the abc network magic to something else sooner rather than later. Barring that, we'd need to do some dirty hacks like https://github.com/bitcoin/bitcoin/pull/10982 to help the networks split more readily, as well as other things to avoid relaying addresses for nodes on other coins. This more fully and quickly prevents both sides from wasting time/network resources connecting to nodes that will never reach consensus with each other.

**Comment by deadalnix** [comment]
This is being worked on.

**Comment by deadalnix** [comment]
Next version of ABC will accept two magic as a first step toward migrating to a new magic.

**Comment by NiKiZe** [comment]
@deadalnix If there is a new magic implemented, where is it documented (remember there is multiple clients, and such a change should probably be discussed and documented before any one client implements it) I would expect a pr to the spec.

**Comment by deadalnix** [comment]
This has been discussed with other clients and is already implemented in classic.

**Comment by NiKiZe** [comment]
@deadalnix 
Where is that discussion?
And again Where is the spec?
Where is the commit where it is implemented? (no PRs, no Issues, and no commits found in classic for this as you claim)

**Comment by deadalnix** [comment]
This discussion is not getting any work done. Please keep things on tracks.

**Comment by NiKiZe** [comment]
It is hard to work on something when you claim that this is worked on or done, but refuse to give any information about what or how... How could anyone give feedback or even implement this in their own client when there is no spec or even basic information.

**Comment by ayeowch** [comment]
Commit where new magic was added in classic: https://github.com/bitcoinclassic/bitcoinclassic/commit/d893b7e62e2b54710b042315a0d0a0958c513834 (from https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-August/000072.html)

**Comment by schancel** [comment]
Thank you for reporting this.  It should now be resolved.
