### ISSUE TITLE
Zero balance

### ISSUE THREAD

**Issue by arnuschky** [Bitcoin-ABC/bitcoin-abc#66]
After switching to bitcoin abc, the balance of my wallet is zero.

I had to rebuild the chain index and then rescan the wallet. (Started out from my bitcoin core's data dir, but had to zap a few block files as it moved past fork date already.)

Afterwards, balance is zero. Wasn't zero before. Anyone seeing this?

**Comment by i3bitcoin** [comment]
I'm syncing at the moment, we'll see how much I have now.

**Comment by arnuschky** [comment]
Even better, I am now in debt:

```
bitcoin-cli listaccounts
{
  "": -1.29023870
}
```

**Comment by i3bitcoin** [comment]
I've synced the wallet and find that I lost 1 BCC. The things back to normal, when I submitted abandon transaction method for my recent transaction of 1 BCC. It seems, that the wallet deducted 2 BCC instead of 1 BCC.

**Comment by coinsmith** [comment]
Are you absolutely sure you sent 1?

**Comment by i3bitcoin** [comment]
Yes, I sent only 1 BCC.

**Comment by arnuschky** [comment]
I needed to wipe the wallet, then re-import the private keys. I now have a consistent balance.
