### ISSUE TITLE
URI scheme collision

### ISSUE THREAD

**Issue by erasmospunk** [Bitcoin-ABC/bitcoin-abc#68]
The URI scheme `bitcoin:` is used on the Bitcoin blockchain and makes it easy to accidentally send coins on the wrong blockchain.

A different scheme like `bitcoincash:` can solve this issue.

**Comment by ftrader** [comment]
@erasmospunk : Thanks for bringing this to attention.
We are aware and making plans to change over to a new URI prefix.

See also for ongoing discussion (and I encourage you to also get involved):
https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-August/000073.html

**Comment by erasmospunk** [comment]
Thanks @ftrader, if you change it to something other than `bitcoincash:` mention me so I can also change it from our side.

**Comment by schancel** [comment]
I'll work on a patch for changing this to `xbc:`

**Comment by ftrader** [comment]
@schancel : please make it easily configurable in the ABC source code if you can.

We've [opened a discussion around selecting a prefix on bitcoin-ml](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-August/000073.html) - xbc has not been settled on yet.

**Comment by zander** [comment]
I just got linked here. I'm the release manager of Bitcoin Classic and according to the discussion (which was how I first learned of this issue) I choose to use "bitcoincash" as a prefix.
This code is available on git and released in the ubuntu PPA 'nightly builds'.

Bitcoin XT is also using the "bitcoincash" prefix.

Please use the 'bitcoin-ml' list for such cross-industry details planning and coordination, I think things will go smoother that way.

**Comment by darkbluelight** [comment]
1) https://www.bitcoinplus.org (while not a relevant coin, but still) is already using XBC
2) I don't like all these attempts that try to take away, hide or replace the "Bitcoin" in "Bitcoin Cash".

**Comment by ftrader** [comment]
The discussion in all clients has converged on 'bitcoincash:' as a prefix.

**Comment by schancel** [comment]
Thank you for reporting this.  This should now be resolved.  Also, the CashAddr rollout should fix additional issues.
