### ISSUE TITLE
Proposal for a system of improvements to Bitcoin Cash

### ISSUE THREAD

**Issue by mpatc** [Bitcoin-ABC/bitcoin-abc#69]
I see there isn't a formalized method in place to improve Bitcoin Cash. 

I have forked the original bips repo and [refactored it as followed:
](https://github.com/mpatc/bcips)
- each relevant, active or final bip becomes a BCIP

- removed bips that have been withdrawn, or are no longer relevant to this project. Obviously, they can be resubmitted if need be.

- changed file names and links from bip to bcip, for **B**itcoin **C**ash **I**mprovement **P**roposal

- changed the mailing list for BCIP submission from bitcoin-dev to bitcoin-ml

- small edits of the original bip texts to reflect current 8MB maxblocksize where needed

- changed editor from Luke to myself

some links won't work because they are referencing a nonexistent https://github.com/Bitcoin-ABC/bcips repo that I am proposing here. 

The bips I removed for various reasons are: 2 10 12 15 17 18 19 20 33 36 40 41 42 43 62 68 74 75 101 102 103 109 125 141 142 144 145

I won't go into my reasoning for each here, it should be self evident, and of course they can be readded if I removed in error. 

I'm volunteering to be the BCIPs editor for now if that works for people, but no new bcips would be added before discussion and agreement, as in the bip process. 

This is just a first pass, I'm sure there is stuff that's wrong, or is missing, or should be missing I will examine/fix later but in the meantime:

Please feel free to review, comment or make PR here: https://github.com/mpatc/bcips

**Comment by checksum0** [comment]
Concept ACK

The BCIPS should not be located on any of the implementation repo, it should be a independent process for protocol development.

Also, there are value able information and development made in the BIPS that were removed. I'd leave it there as informational only.

**Comment by ftrader** [comment]
@mpatc : Thanks for raising this topic.

I agree with you about the importance of having a place where implementations can gather around new specifications (BCIPs is a decent name).

And I agree very much with @checksum0 that this should be independent from any particular implementation.

I will bump this topic to the bitcoin-ml mailing list since that's where the most "formal" discussion around future Bitcoin Cash protocol matters is happening now.
There are some additional comments I'll make there.

**Comment by schancel** [comment]
Agree with @checksum0 Closing this issue in favor of other groups currently attempting to organize this process.
