### ISSUE TITLE
Menu bar disappears in ubuntu

### ISSUE THREAD

**Issue by kharri1073** [Bitcoin-ABC/bitcoin-abc#72]
### Describe the issue
Upon starting bitcoin abc the menu bar is accessible however after it is minimized to the task bar then restored, the menu bar does not appear again until bitcoin abc is restarted.

#### If so, please list the steps to reproduce below:
1. Start bitcoin abc
2. minimize or close bitcoin abc to task bar
3. Click Show/Hide from bitcoin abc icon in task bar
4. Menu bar is missing

### Expected behaviour
The menu bar should be available after restoring the bitcoin abc wallet after it was minimized.

### Actual behaviour
The menu bar disappears and is not accessible after restoring a minimized bitcoin abc wallet. 

### Screenshots.
Menu bar immediately after startup -
![screenshot from 2017-08-16 14-58-37](https://user-images.githubusercontent.com/972280/29380606-4a1b4d34-8294-11e7-8946-deda1a662640.png)

Menu bar after minimizing and restoring -
![screenshot from 2017-08-16 14-58-54](https://user-images.githubusercontent.com/972280/29380617-584da8d4-8294-11e7-8f5d-879c9982b7f7.png)

(My mouse cursor is hovering in the menu bar in both instances. Upon the screen capture, the mouse cursor is hidden.)

### What version of bitcoin-core are you using?
bitcoin abc 0.14.6

### Machine specs:
- OS: Ubuntu running unity 7.4.0
- CPU: Intel® Core™ i7-2640M CPU @ 2.80GHz × 4 
- RAM: 4GB

### Any extra information that might be useful in the debugging process.
I don't see anything out of the ordinary in debug.log. Most if not all of the menu bar is alternatively available from the dropdown menu from the bitcoin abc icon in the task bar.

**Comment by jasonbcox** [comment]
This is a known bug in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/bamf/+bug/1532226  Closing this ticket as it's not related to bitcoin-abc.
