### ISSUE TITLE
Address change

### ISSUE THREAD

**Issue by axelay** [Bitcoin-ABC/bitcoin-abc#73]
This is not an issue per say but something really ought to be done to be able to generate addresses that are distinct from what Bitcoin core uses.
Running an exchange is an absolute nightmare - no matter how many warnings you put on the page, users will still mess up.

It will not solve all the issues we have due to legacy, and to be fair this should have not been rushed, but here we have it - we need something to be able to make the Bitcoin ABC addresses unique.

**Comment by SentinalBais** [comment]
already and issue

but please help get community support. Apparently this change is backwards compatible so it shouldn't be to hard to push out.

Change address version #35

**Comment by NxtChg** [comment]
> Running an exchange is an absolute nightmare

Do you have any stats about the number of mistakes?

**Comment by axelay** [comment]
The number of mistakes is very small compared to the volume of deposits - however for each BTC sent to a BCH address I have to export the private key from the BCH server, import it into the BTC server then wait for the server to fnish the rescan. Even though it does not sound like a massive overhead, we still have to spend time answering the user's ticket and manually do the above steps - which would be prevented if we had unique addresses :)

When BCH is sent to BTC that's another matter as Bitgo deals with it and their BCH support is virtually non-existent. But we still have to answer user's tickets.

Hope that answers your question

**Comment by NxtChg** [comment]
> I have to export the private key from the BCH server, import it into the BTC server then wait for the server to fnish the rescan

Ah, you see, it's just you're doing it wrong :)

I just use my lightweight wallets (https://tsbw.io) - it doesn't require rescan and I can quickly refund the users.

So it's a bit unfair to demand a major change of the protocol that requires lots of other software to update, just because you're doing things inefficiently, don't you think?

**Comment by axelay** [comment]
Was all that faff just for a shameless plug? seriously?

I don't want to refund the users, we hold the coins they sent us so we need to credit it to the right balance. There is no way we can do this automatically and whether or not we use a 3rd party, we still have to do ticket answering and we still have to do the manual input in whatever we use.

So no I am sorry your argument is not strong enough and we need a different key prefix.

**Comment by NxtChg** [comment]
> Was all that faff just for a shameless plug? seriously?

You think I did it for a plug? Seriously?

Thanks for insulting me while I was trying to help.

> I don't want to refund the users, we hold the coins they sent us so we need to credit it to the right balance. 

If you support both chains in your project the workload should be on _you_, not everyone else.

Create a solution that uses the same addresses for deposit on both chains or find some other way.

Instead you want to support both chains, but want everyone else to "pay" for it with _their_ time.

Still not fair.

**Comment by axelay** [comment]
You're right it's not fair - I apologise if I insulted you.
But I don't see the point in carrying on this conversation - thanks for your input though but it will not help us.

**Comment by NxtChg** [comment]
> thanks for your input though but it will not help us

I.e. "I would still want to give others more work, so _I_ could get more profits by supporting both chains  and to make _my_ life easier".

You're right, there is no point to continue arguing if that's your position.

**Comment by josephNLD** [comment]
This is already an open issue #35

**Comment by schancel** [comment]
Closing as a duplicate.  This is being resolved.
