### ISSUE TITLE
Script versioning

### ISSUE THREAD

**Issue by jwt27** [Bitcoin-ABC/bitcoin-abc#79]
One new feature added by Segwit is script versioning. As I understand it, this provides the ability to redefine opcodes without hard-forking. This seems like a useful feature to have, if only for future-proofing. 

Considering that another fork may be required soon to modify the difficulty adjustment algorithm (#75), perhaps this would be a good time to add a script versioning mechanism to the protocol?

**Comment by justicemate** [comment]
I'd personally prefer the flex-trans method for using tagged formats, as opposed to the Segwit fixed byte static format.

**Comment by DesWurstes** [comment]
Please note that SegWit added that feature, just because BlockStream wanted to add their own opcodes. (And make money of them.)

**Comment by jwt27** [comment]
Thanks, I wasn't aware of FlexTrans. Reading up on it right now, this looks like a far better proposal than any feature added by segwit.

Please excuse my ignorance, I should have done more research before opening an issue. Will close this for now.
