### ISSUE TITLE
Transaction Dates incorrect on transactions from imported wallets

### ISSUE THREAD

**Issue by redog** [Bitcoin-ABC/bitcoin-abc#80]
This issue tracker is only for technical issues related to bitcoin-abc

#### If so, please list the steps to reproduce below:
1.  Import new private key of wallet containing transactions in the past

### Expected behaviour
Dates should be correct or a warning displayed that they're inaccurate

### Actual behaviour
Dates seem randomly placed between other wallet's transactions

### What version of bitcoin-abc are you using?
 Bitcoin ABC version v0.14.6.0-ga46e63c (64-bit)

### Machine specs:
- OS: Linux
- CPU: x64
- RAM: 128G
- Disk size: 15T
- Disk Type (HD/SDD): both across zfs set

### Any extra information that might be useful in the debugging process.

**Comment by ftrader** [comment]
Hi @redog : 
I'll try to reproduce this - couple of questions:

1. did you use importprivkey RPC command to import the private keys?
2. how far back were the actual dates of these transactions? all before Aug 1 or some before & after?
3. what date is displayed for the most recent such transaction that was misplaced versus its supposed date?

**Comment by redog** [comment]
Yes, I used the debug window command importprivkey.

The actual list should look like:

2017-08-04 12:58 received
2016-11-18 21:08 sent 
2016-11-18 15:08 sent
2015-01-14 20:25 received
2014-04-02 09:09 received
2014-02-26 15:49 received

instead it's 

2017-08-24 17 23 received
2017-08-21 10:51 sent
2017-08-21 10:51 sent
2017-08-21 10:51 received
2017-08-21 10:51 received
2017-08-21 10:51 received

**Comment by redog** [comment]
So I tried the patched line from https://github.com/bitcoin/bitcoin/issues/6662 and reindexed with 
bitcoind -zapwallettxes=2

This got closer for all transactions except for the last but not quite spot on.
The last one is still listed at 2017-08-24 but now at 23:54 
The others that were earlier are on the correct dates , time I'm less certain about they all seem off by 4-6 hours
