### ISSUE TITLE
missing my bcc I need some help

### ISSUE THREAD

**Issue by wefdi** [Bitcoin-ABC/bitcoin-abc#84]
![1](https://user-images.githubusercontent.com/31162030/30240876-a6ae0e74-95b3-11e7-8fbc-1aa21199e3b0.png)

someone know about this problem???
I can not transfer to other address, 

So I tried make a new one with my private key,

![3](https://user-images.githubusercontent.com/31162030/30240887-cb027d82-95b3-11e7-829e-de68346eef23.png)

as you can see, same public key, but new one has no balance. old one 24 bcc.

![2](https://user-images.githubusercontent.com/31162030/30240895-fd074290-95b3-11e7-89f7-bf6266613e3b.png)

still my old wallet has 24 bcc... but not transfer. So I can't use it.

I tried electron 2.9.0, ~2.9.3 and bitcoin ABC wallet.

what can I do?? I want to get my bcc...

**Comment by schancel** [comment]
Have you been able to resolve this issue yet?
