### ISSUE TITLE
Connecting to peers forever with 0.15.0

### ISSUE THREAD

**Issue by NickTh1** [Bitcoin-ABC/bitcoin-abc#86]
### How to repro:
1. Create a virtual machine in VMWare or VirtualBox and install Windows 10 Home
2. Download and install BitcoinABC 0.15.0
3. Start it
4. Unblock firewall on prompt

### Expected behaviour
Expected behavior is that it should eventually find some peers and start synchronizing with the network.

### Actual behaviour
It appears to never find any peers. I tried rebooting the machine a couple of times, and I've tried to make sure that the firewall is letting everything through. I also tried on both VirtualBox and VMWare.

### What version of bitcoin-core are you using?
BitcoinABC version 0.15.0, downloaded from here 'https://download.bitcoinabc.org/0.15.0/win/bitcoin-abc-0.15.0-win64-setup-unsigned.exe'

### Machine specs:
- OS: Window 10 Home (both host and client) in VMWare and VirtualBox.
- CPU: Intel Core I7
- RAM: 8GB
- Disk size: 180GB (virtual)
- Disk Type (HD/SDD): HD (Virtual)

### Any extra information that might be useful in the debugging process.
I don't claim to be sure that this is a problem - I very much believed that I was doing something wrong with the firewall or something. After having scratched my head for quite a while (and double-checking firewall settings 17 times+), I decided to try the 0.14.6 version instead - and then it worked right away.
Again; I'm not sure I didn't make a mistake or two - I merely post this as FYI. Maybe someone could double-check that it actually works - but feel free to nuke if what I say cannot possibly be the true :-).

**Comment by wolfomat** [comment]
Same issue here.... the version 0.15.0 does not sync

**Comment by deadalnix** [comment]
We plan to refresh the peer list in the next version. We skipped it for
0.15 and, as a result, it doesn't start with a peer list of high quality :/

**Comment by ftrader** [comment]
@wolfomat , @NickTh1 : 

I made some adjustments to one of the DNS seeds, and this should improve the situation until we update peer lists in the next version.

Would be grateful if one of you could confirm.

**Comment by schancel** [comment]
This seems to be resolved

**Comment by scalahub** [comment]
It doesn't work now. Stuck at "finding peers" and around 80% complete. Using the latest 16 version.

**Comment by bazooka70** [comment]
Same issue here with version 0.16.0.2
Both testnet and main. Its just stuck on "Connecting to peers..."

**Comment by scalahub** [comment]
I solved it as follows. I had to do `reconsiderblock` for the BCH forked 1st block and `discardblock` for the BTC forked 1st block.
