### ISSUE TITLE
transaction reject error

### ISSUE THREAD

**Issue by wefdi** [Bitcoin-ABC/bitcoin-abc#88]
![1](https://user-images.githubusercontent.com/31162030/30336279-a7870274-981f-11e7-9239-42e704c81c0b.png)

and it's not sync to other wallet

![3](https://user-images.githubusercontent.com/31162030/30336290-b980974c-981f-11e7-9c3c-6892d89a006e.png)

**Comment by schancel** [comment]
This should probably go in the electron cash repository.  @fyookball @kyuupichan any ideas?

https://github.com/fyookball/electrum is the current Electron Cash repo
