### ISSUE TITLE
Maximizing from system tray does not restore window

### ISSUE THREAD

**Issue by PorlyBe** [Bitcoin-ABC/bitcoin-abc#91]
### Describe the issue
With "Minimize to tray instead of taskbar" it does as advertised but when I try to restore the window by clicking on the tray icon it doesn't fully show the window. It appears in my taskbar but I need to click it to view the window. 

This only happens if I minimize the window when I click the minimize, close or the taskbar icon. When I minimise the window by clicking the tray icon, clicking the tray icon again it shows the window fully.

#### If so, please list the steps to reproduce below:
1. Have window open and Minimize to tray selected in options
2a. Minimize window with minimise button from the title bar.
2b. Minimize window with close button (if closer to tray is selected in options) from the title bar.
2c. Minimize by clicking the taskbar icon.
3. Click tray icon to restore window.

### Expected behaviour
Clicking tray icon while window is minimized to tray should restore the window fully.

### Actual behaviour
Window does not show but appears minimized in taskbar

### What version of bitcoin-core are you using?
Bitcoin ABC version v0.15.0.0-67d83e7 (64-bit)

### Machine specs:
- OS: Windows 10 Pro
- CPU: x64
- RAM: 16G
- Disk size: 4TB
- Disk Type (HD/SDD): HD

**Comment by dagurval** [comment]
Perhaps fixed by cherry-picking https://github.com/bitcoin/bitcoin/pull/11335

**Comment by NxtChg** [comment]
Oh yeah, this one is quite annoying and all cloned clients have this...

**Comment by jasonbcox** [comment]
Created an associated task on Phabricator so we can more accurately track it: https://reviews.bitcoinabc.org/T318 If anyone has some extra cycles, can pick up this backport, and open a PR on Phabricator, we'll rebase it.  Looking at the noobies wanting to get involved, as this is a bootcamp ticket ;)

**Comment by jasonbcox** [comment]
I'm now working on this, because it blocks other backports in my queue.

**Comment by jasonbcox** [comment]
This is fixed on master: https://reviews.bitcoinabc.org/rABC4c4ca6c7c27c410d2d70ea8f97bb69f36d512d1c
