### ISSUE TITLE
Besides the reference version, we need another user-friendly complementary-version.

### ISSUE THREAD

**Issue by jli225** [Bitcoin-ABC/bitcoin-abc#93]
Although it's a common sense that the full nodes run by casual individuals contribute zero to the network, we have to admit that many people use the reference version as the stablest wallet.

Theoretically, the design of the reference version is not able to be user-friendly because of multiple unchangeable reasons. i.e. It can't have 2FA setting by default. 

Thus some negative effects are inevitable. i.e. the cybersecurity risks around holding bitcoin with reference version have been always a problem for normal people. Yes you can keep it offline, but many people are more accustomed to run the wallet with reference version online. So it's always a target for cyberattack.

The only simple solution is 2FA. Email verification codes or sms. There has been already some solutions provided by third parties. But the fact is, most people don't have much confidence in third parties.

Philosophically, reference version can't have 2FA or it will be seen as anti-libertarian by some people. So a complementary version should accompany with the reference version. At least we should be able to use gmail to receive the activation code.

We should have three versions: Reference version, User-friendly full-nodes, and user-friendly SPV.

**Comment by josephNLD** [comment]
Email and SMS are the most insecure factors used for 2FA today.
User-friendly and secure SPVs are very needed, not sure why another full-node-that-doesn't-mine client is merited, who is needing it, and for what purpose?

**Comment by jli225** [comment]
@josephNLD 
Yes Email and SMS are not very insecure, but much easier. And they are much safer than no 2FA. 

The only merit the full-node-that-doesn't-mine client has here is that it behaves as a kind of trustable SPV. Sounds weird? I will try to explain.

Current Bitcoin Cash has not trustable SPV servers for the average joe. It took years for electrum to become the trustable SPV. Many Bitcoin Cash SPV run by good people are emerging but it needs time to become trustable for the average joe. So the full-node-that-doesn't-mine client behaves as the trustable SPV.

As time passes, SPV providers will become trustable inevitably. Then, the full-node-that-doesn't-mine client will have zero more merits than SPV. So the User-friendly full-nodes are only needed temporarily.

Yes, even now, the User-friendly full-nodes version is not necessary. But I think the User-friendly SPV version is necessary. And this will express a sound that the reference version is never expected to be run by average-joe users as wallets.

**Comment by josephNLD** [comment]
Bitpay may fill some gaps here for SPV, maybe, we'll see.
ABC, BitcRust, BU, Classic...  Some nice variety in full-node choices.
These, and the others, can compete for better presentation layers and folks can form preferences.

**Comment by jli225** [comment]
I sincerely wish Bitcoin (cash) can have reference SPV version, since it's expected to have from early days.
Reference version should not be equal to 'full nodes version'.

**Comment by schancel** [comment]
We need as many good wallets and implementations as we can get :). However this repository is for Bitcoin ABC.  I'm going to close this issue, I would recommend moving to the ml, or one of the many other forums and see if you can't get some more developers to work on this.
