### ISSUE TITLE
Balance Issues, showing as 0 

### ISSUE THREAD

**Issue by paOol** [Bitcoin-ABC/bitcoin-abc#96]
### Describe the issue

Balance appears as 0 when there are funds.

### Can you reliably reproduce the issue? 
No
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour

I am doing small amounts 0.0005 bcc, and there is more than 2 coins in the balance.

`listaccounts` shows the account with a balance.
`sendtoaddress 1jklasjdfklja 0.0005` 

should send that amount to that address with no issues.

### Actual behaviour

results in
`Insufficient funds`

### What version of bitcoin-core are you using?
```
 "version": 150000,
  "protocolversion": 70015,
  "walletversion": 60000,
```

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.

the "" account had a negative balance. I used `move` to get it back to 0.
I have heard move causes problems and that may be the issue.

**Comment by paOol** [comment]
```
/srv/# bitcoin-cli getinfo
{
  "version": 150000,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 496206,
  "timeoffset": 0,
  "connections": 18,
  "proxy": "",
  "difficulty": 84768257679.68858,
  "testnet": false,
  "keypoololdest": 1508250357,
  "keypoolsize": 400,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
/srv/# bitcoin-cli listaccounts
{
  "": 0.20000000,
  "faucet": 0.19346375
}

```

i deleted wallet.dat and restarted `bitcoind`, only created one account and kept a balance on both.
balance still shows as 0 sometimes

**Comment by SaiX123** [comment]
getting the same issue, balance shows 0

**Comment by paOol** [comment]
haven't seen the issue recently. I'm assuming its fixed. 

closing
